Azure/Azure-AppServices-Diagnostics-Portal

app/supportbot/homepage/homepage.component.ts

Changes:
- Updated the MSDN and Stack Overflow links to use azure web apps tag

Update msdn and stack overflow links

---

app/app.module.ts
app/availability/analysis/app-analysis.component.ts
app/availability/analysis/availability-graph.component.ts
app/availability/analysis/memory-analysis/memory-analysis.component.ts
app/availability/analysis/perf-analysis.component.ts
app/availability/analysis/webapprestart/webapprestart.component.ts
app/availability/detector-view/detector-view-base/detector-view-base.component.ts
app/availability/tools-menu/tools-menu.component.ts
app/shared/components/support-tools/support-tools.component.ts
app/shared/models/icache.ts
app/shared/models/responsemessageenvelope.ts
app/shared/models/site.ts
app/shared/models/solution-ui-model/othersolutions.ts
app/shared/services/appanalysis.service.ts
app/shared/services/arm.service.ts
app/shared/services/cache.service.ts
app/shared/services/index.ts
app/shared/services/portal-action.service.ts
app/shared/services/rbac.service.ts
app/shared/services/server-farm-data.service.ts
app/shared/services/site.service.ts
app/shared/services/urielements.service.ts
app/shared/shared.module.ts
app/supportbot/message-flow/health-check/health-check.component.ts
app/supportbot/support-bot.component.ts
package.json

#32 I have updated to the new routes for diagnostic endpoints. 
I also added a cache service for all ARM calls, instead of just having a cache in app analysis service

Updating Routes and Adding Arm Cache

---

app/availability/availability.module.ts
app/availability/detector-view/detector-view.routeconfig.ts
app/availability/detector-view/detectors/docker-container-start-stop-detector/docker-container-start-stop-detector.component.html
app/availability/detector-view/detectors/docker-container-start-stop-detector/docker-container-start-stop-detector.component.ts
app/availability/tools-menu/tools-menu.component.ts
app/shared/components/support-tools/support-tools.component.ts
app/shared/models/site.ts
app/supportbot/homepage/homepage.component.ts
app/supportbot/message-flow/health-check/health-check.component.ts
app/supportbot/message-flow/main-menu/main-menu.component.ts
app/supportbot/message-flow/main-menu/mainmenumessageflow.ts

This includes some of Aspaan's changes

Filtering Homepage/Bot View for Linux

---

app/availability/analysis/app-analysis.component.ts
app/availability/analysis/perf-analysis.component.ts
app/shared/services/index.ts
app/shared/services/logging/availability.logging.service.ts
app/shared/services/logging/bot.logging.service.ts
app/shared/services/logging/logging.service.ts
app/shared/services/server-farm-data.service.ts

Moving the calls to get this information into logging.service, which
means all the other logging services will enherit it

Add Linux/Windows to all telemetry

---

app/shared/models/solution-ui-model/othersolutions.ts
app/shared/models/solution-ui-model/solutionfactory.ts

Added solution for container start stop

changes for linux workers

---

app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.css
app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.html
app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.ts

1.	Instances to be profiled
2.	Change double equals to 3
3.	Move the loading in the gray box
4.	Specify a line about 60 seconds
5.	Reformat the below table

Updating Profiler component UI

---

app/supportbot/message-flow/main-menu/main-menu.component.ts

change color for tcp connections tile

---

app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.html
app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.ts

1. Hiding table if no profiling Session found and displaying message "No sessions found"
2. Showing entries only for CLR Profiling sessions in the table
3. Added logging in Profiler Component

Slight Changes to Profiler UI

---

app/availability/analysis/tcpconnectionsanalysis/tcp-connections-analysis.component.ts
app/shared/components/expandable-summary/expandable-summary.component.html
app/shared/models/summary-view-model.ts
app/shared/utilities/metaDataHelper.ts

This is how it looks, open for any feedback \ suggestions

TCP Connections Analysis - Constructing message from abnormalTimePeriod's payload

---

app/shared/services/solution-factory.service.ts
app/solutions/components/common/solutions-widget/solutions-widget.component.ts
app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.ts

Use Server Farm Service to get the correct site, since if you rely on
the respond from the diag role, it will return the resource group of the
main site, but a neighboring site on the same server farm could have a
different resource group.

Profiling Solution Improvement

---

app/shared/services/solution-factory.service.ts
app/solutions/components/common/dynamic-solution/dynamic-solution.component.ts
app/solutions/components/common/solutions-widget/solutions-widget.component.ts
app/solutions/components/specific-solutions/revert-deployment-solution/revert-deployment-solution.component.css
app/solutions/components/specific-solutions/revert-deployment-solution/revert-deployment-solution.component.html
app/solutions/components/specific-solutions/revert-deployment-solution/revert-deployment-solution.component.ts
app/solutions/solutions.module.ts

Add RevertDeployment solution

---

app/availability/analysis/tcpconnectionsanalysis/tcp-connections-analysis.component.html
app/availability/analysis/tcpconnectionsanalysis/tcp-connections-analysis.component.ts
app/shared/components/expandable-summary/expandable-summary.component.html
app/shared/components/expandable-summary/expandable-summary.component.ts

Adding an option to view TCP Connection information for past days
Removing availability from this view as I couldnt find a way to get Availability graphs for older days...

Adding date selection for TCP Connections

---

app/shared/models/solution-ui-model/othersolutions.ts

This should fix the error where the kudu site would not open

Compare sitenames as lower case

---

app/availability/problem-solution/problem-solution.component.ts

Forgot to remove a couple lines I added just to test a no observations/solutions situation

Cleaning up test artifacts

---

app/solutions/components/specific-solutions/memorydump-solution/memorydump-solution.component.html
app/solutions/components/specific-solutions/memorydump-solution/memorydump-solution.component.ts

Just like the profiler solution

Fixing Memory Dump solution to handle errors and do retries

---

app/availability/availability.routeconfig.ts
app/shared/components/tools/daas-base/daas-base.component.ts
app/shared/components/tools/java-memorydump-tool/java-memorydump-tool.component.html
app/shared/components/tools/java-memorydump-tool/java-memorydump-tool.component.ts
app/shared/components/tools/java-threaddump-tool/java-threaddump-tool.component.html
app/shared/components/tools/java-threaddump-tool/java-threaddump-tool.component.ts
app/shared/services/solution-factory.service.ts
app/shared/shared.module.ts
app/solutions/components/common/dynamic-solution/dynamic-solution.component.ts
app/solutions/components/specific-solutions/java-threaddump-solution/java-threaddump-solution.component.html
app/solutions/components/specific-solutions/java-threaddump-solution/java-threaddump-solution.component.ts
app/solutions/solutions.module.ts

Adding the JAVA based tools from daas...

Adding Java based DAAS Tools as solutions and individual tools in Support Center

---

src/app/shared/components/daas/profiler.component.html

Fixing minor spelling mistake and updating text based on Jen's feedback

Profiler Text Changes

---

src/app/availability/availability.routeconfig.ts
src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html
src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.ts
src/app/shared/models/network-trace.ts
src/app/shared/services/urielements.service.ts
src/app/shared/shared.module.ts

**Initial Screen**
**After you click Collect Network Trace**
**If one trace is running and you clicked again**

Adding the Network Trace Tool

---

.angular-cli.json
src/app/app.component.html
src/app/app.module.ts
src/app/availability/availability.routeconfig.ts
src/app/shared/components/incident-notification/incident-notification.component.css
src/app/shared/components/incident-notification/incident-notification.component.html
src/app/shared/components/incident-notification/incident-notification.component.ts
src/app/shared/components/incident-summary/incident-summary.component.css
src/app/shared/components/incident-summary/incident-summary.component.html
src/app/shared/components/incident-summary/incident-summary.component.ts
src/app/shared/models/icm-incident.ts
src/app/shared/services/service-incident.service.ts
src/app/shared/shared.module.ts

Adding ICM incident notifications
Orange banner will pop up when we detect an incident:
Then will open new page with details:

Adding Incident Notification

---

src/app/shared/components/incident-notification/incident-notification.component.html
src/app/shared/components/incident-notification/incident-notification.component.ts
src/app/shared/components/incident-summary/incident-summary.component.css
src/app/shared/services/logging/events.enumerations.ts
src/app/shared/services/logging/logging.service.ts
src/app/shared/services/service-incident.service.ts
src/styles/bot.css
src/styles/global.css

I also adjusted view for small windows (ticket opening flow)

Add logging for incidents

---

src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.css
src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.html
src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.ts
src/app/shared/models/daas.ts

Fixing minor stuff and adding connection type (SQLAzure, Custom etc.) next to the connection string name and also adding logging in this component
Attaching a screenshot

Adding database connection type and pointer in Connection Checker Tool

---

src/app/availability/availability.routeconfig.ts
src/app/shared/components/daas/daas-validator.component.ts
src/app/shared/components/daas/daas.component.html
src/app/shared/components/daas/daas.component.ts
src/app/shared/components/daas/profiler.component.html
src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html
src/app/shared/models/problem-category.ts
src/app/shared/services/categories.service.ts
src/app/supportbot/message-flow/main-menu/main-menu.component.css
src/app/supportbot/message-flow/main-menu/main-menu.component.html
src/app/supportbot/message-flow/main-menu/main-menu.component.ts

1. Adding remaining DAAS tools in homepage
1. Caching the DAAS related tools and components.
1. Adding the Network Trace tool with a warning for VNET
1. Fixing DAAS issue to work with ASE (Isolated SKU)
1. Disabling check box'es for DAAS if a session in progress

Adding the remaining tools to support center and giving option to choose the stack

---

src/app/shared/components/daas-sessions/daas-sessions.component.html
src/app/shared/components/daas-sessions/daas-sessions.component.ts
src/app/shared/components/daas/daas.component.ts
src/app/shared/components/tools/daas-base/daas-base.component.ts
src/app/shared/components/tools/http-loganalysis-tool/http-loganalysis-tool.component.html
src/app/shared/components/tools/java-memorydump-tool/java-memorydump-tool.component.html
src/app/shared/components/tools/java-threaddump-tool/java-threaddump-tool.component.html
src/app/shared/components/tools/java-threaddump-tool/java-threaddump-tool.component.ts
src/app/shared/components/tools/memorydump-tool/memorydump-tool.component.html
src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html
src/app/shared/components/tools/php-logsanalyzer-tool/php-logsanalyzer-tool.component.html
src/app/shared/components/tools/php-processanalyzer-tool/php-processanalyzer-tool.component.html
src/app/shared/components/tools/profiler-tool/profiler-tool.component.html
src/app/shared/components/tools/profiler-tool/profiler-tool.component.ts
src/app/shared/services/daas.service.ts
src/app/solutions/components/specific-solutions/java-threaddump-solution/java-threaddump-solution.component.html
src/app/solutions/components/specific-solutions/java-threaddump-solution/java-threaddump-solution.component.ts
src/app/solutions/components/specific-solutions/memorydump-solution/memorydump-solution.component.html
src/app/solutions/components/specific-solutions/memorydump-solution/memorydump-solution.component.ts
src/app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.html
src/app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.ts

1) Minor changes to networktrace tool layout
2) Separating DAAS Sessions functionality in to its own component.

Toolsminor ui fixes and separating Daas Sessions stuff completely in a different component

---

src/app/shared/components/support-tools/support-tools.component.html
src/app/shared/components/support-tools/support-tools.component.ts
src/app/shared/services/portal-action.service.ts

Adding Perfmon Link to MDM metrics

---

src/app/shared/components/daas/daas-validator.component.ts

Changing the order of getting diagnosers first before checking for DAAS webjob as checking for diagnosers will warmup DAAS and will ensure that the webjob gets copied to the right folders which will then ensure that the webjob is started by the time the call to get webjobstate is made...

Changing order of Retrieving Diagnosers and checking WebjobState

---

package.json
src/app/availability/availability.routeconfig.ts
src/app/betaSubscriptions.ts
src/app/shared/models/portal.ts
src/app/shared/models/problem-category.ts
src/app/shared/models/server-farm.ts
src/app/shared/models/site.ts
src/app/shared/services/categories.service.ts
src/app/shared/services/generic-api.service.ts
src/app/shared/services/server-farm-data.service.ts
src/app/shared/services/site.service.ts
src/app/supportbot/message-flow/main-menu/main-menu.component.html
src/app/supportbot/message-flow/main-menu/main-menu.component.ts
src/app/supportbot/supportbot.module.ts

Most of this is deployed already for Jen's demo

Adding changes to handle function apps and other filtering

---

package.json
src/app/availability/availability.module.ts
src/app/shared/services/categories.service.ts
src/app/shared/services/service-incident.service.ts

Updated applens-diagnostics package and made necessary change to remove the insights problem. 
Enable for all subscriptions.

Update diagnostics library and remove sub filter

---

.angular-cli.json
package.json
src/app/availability/generic-detector/generic-detector.component.ts
src/index.html
src/styles/global.css

1. Push common columns with telemetry service from applens-diagnostic module
2. Css style change to enable star rating modal pop up

Enable telemetry service from applens-diagnostic module

---

src/app/shared/components/daas-sessions/daas-sessions.component.html
src/app/shared/components/daas-sessions/daas-sessions.component.ts
src/app/shared/models/daas.ts
src/app/shared/services/arm.service.ts
src/app/shared/services/daas.service.ts
src/app/shared/services/urielements.service.ts

This will allow users to delete Daas Session and reclaim disk space.

Implementing Delete session in DaaS UI

---

src/app/liveChatSettings.ts

Also reduce the inactivity time for more engagement

Enable chat for deployment slots

---

src/app/shared/models/tools-constants.ts
src/app/shared/services/categories.service.ts

Adding Autohealing as a tile under Diagnostic Tools

---

src/app/auto-healing/autohealing.component.css
src/app/auto-healing/autohealing.component.html
src/app/shared/components/support-tools/support-tools.component.html
src/app/shared/components/support-tools/support-tools.component.ts

Right now everything is looking a bit over-sized. Resized it so it fits nicely in Azure portal

Resizing AutoHealing UI slightly so it fits better in IBIZA 

---

src/app/liveChatSettings.ts
src/app/shared/services/livechat.service.ts

I am looking to move this config out of code so that it can be updated. Few things needs to be ironed out here.

Add Public Holidays logic

---

src/app/liveChatSettings.ts
src/app/shared/services/livechat.service.ts
src/app/supportbot/message-flow/talk-to-agent/talktoagentmessageflow.ts

Until the location issue is sorted out, we have decided to put the chat program on hold for this week. Meanwhile agents will resume training in other problem areas.

Disable Live Chat for this week

---

src/app/auto-healing/auto-healing.module.ts
src/app/auto-healing/autohealing.component.html
src/app/auto-healing/autohealing.component.ts
src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.css
src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.html
src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.spec.ts
src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.ts
src/app/shared/components/toggle-button/toggle-button.component.css
src/app/shared/services/autohealing.service.ts
src/app/shared/services/site.service.ts

Adding checks for proactive autohealing in AutoHealing section

Adding logic for Proactive autohealing

---

src/app/liveChatSettings.ts

Only for Case Submission right now from 9AM to 6PM

Enable Live chat from 9-6

---

src/app/home/components/home/home.component.css
src/app/home/components/home/home.component.html
src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts
src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.html
src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts
src/app/resources/web-sites/services/site-feature.service.ts
src/app/shared-v2/services/notification.service.ts
src/app/shared/components/notification/notification.component.css
src/app/shared/components/notification/notification.component.html

Context: The team building the ticket opening flow wants to add a banner on our blade when they open it so that the customer knows that they will want to close our blade to continue along the case submission process:
Also adding Zray and Tinfoil to Diagnostic tools per request from Nitasha:

Adding Notification for Ticket opening flow and premium tools

---

AngularApp/src/app/availability/availability.routeconfig.ts

Already had to deploy this because case submission was broken.

FIx CPU in case submission

---

AngularApp/src/app/availability/detector-view/detector-loader/detector-loader.component.html
AngularApp/src/app/availability/detector-view/detector-loader/detector-loader.component.ts
AngularApp/src/app/availability/detector-view/detector-view-base/detector-view-base.component.ts
AngularApp/src/app/availability/detector-view/detector-view-instance-detail/detector-view-instance-detail.component.ts
AngularApp/src/app/availability/detector-view/detector-view-problem/detector-view-problem.component.ts
AngularApp/src/app/shared/components/instance-view-graph/instance-view-graph.component.ts
AngularApp/src/app/shared/components/metric-graph/metric-graph.component.ts

@puneetg1983 brought attention to this issue that happens when you change time range.
Before:
After:

Fix loading

---

AngularApp/src/app/availability/tools-menu/tools-menu.component.ts
AngularApp/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/src/app/shared/components/support-tools/support-tools.component.ts
AngularApp/src/app/shared/services/portal-action.service.ts

On clicking 'metrics per instance' in tools, Open Azure Monitor new Metrics blade which has instances split

Move metrics to Azure monitor blade

---

AngularApp/src/app/resources/web-sites/services/site-support-topic.service.ts
AngularApp/src/app/resources/web-sites/services/web-sites.service.ts
AngularApp/src/app/shared-v2/services/support-topic.service.ts
AngularApp/src/app/shared/components/generic-detector/generic-detector.component.css
AngularApp/src/app/shared/components/generic-detector/generic-detector.component.html
AngularApp/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.ts
AngularApp/src/app/shared/services/appanalysis.service.ts

Fixing Network Trace issue where it said it was not authenticating when accessing through search.
In case submission, remove large padding for detectors and for Linux, point to the new detector instead of old.

Remove warm up calls and other fixes

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html

This is a PR for the work item 1393: Better error messaging for incorrect time range input.
This is only for AppLens, not for App Service Diagnostics.

Better error messaging for incorrect time range input at AppLens

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts

This was causing an issue because of changes made on the portal blade side (which will be deployed this week)

Fix misroute issue

---

AngularApp/projects/applens/src/app/modules/casecleansing/casecleansing.module.ts
AngularApp/projects/applens/src/app/modules/casecleansing/casecleansing/casecleansing.component.html
AngularApp/projects/applens/src/app/modules/casecleansing/casecleansing/casecleansing.component.ts
AngularApp/projects/applens/src/app/modules/casecleansing/casecleansingmodal/casecleansingmodal.component.html
AngularApp/projects/applens/src/app/modules/casecleansing/casecleansingmodal/casecleansingmodal.component.spec.ts
AngularApp/projects/applens/src/app/modules/casecleansing/casecleansingmodal/casecleansingmodal.component.ts
AngularApp/projects/applens/src/app/shared/services/casecleansing-api.service.ts
AngularApp/projects/applens/src/styles.scss

Updates to the case Cleansing tool:
* Full width table
* Filtering options
* Improoved UI
* Bug Fixes

Case Cleansing Improvements

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/logging/logging.service.ts

Differentiate between case submission (v1, v2) and Diagnose and Solve

Add source to default logging parameters

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts

Getting rid of applensv2 TCP Connections

Removing TCP Connections v2 and pointing to v3 TCP Connections

---

ApplensBackend/Services/DiagnosticRoleClientService/DiagnosticRoleClient.cs
ApplensBackend/appsettings.json

- Added Nazeef's code for the `isLocalDevelopment` setting to DiagnosticRoleClient to enable running the project on local machine
- Added `isLocalDevelopment` setting to `DiagnosticRole` section of appsettings.json

Add LocalDevelopment Setting to run DiagnosticRoleClient Locally

---

AngularApp/projects/diagnostic-data/src/lib/components/card-selection/card-selection.component.html
AngularApp/projects/diagnostic-data/src/lib/components/card-selection/card-selection.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/card-selection/card-selection.component.ts

minor changes to card rendering based on feedback...

Removing Icon and Adding color to Card Tiles

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html

Adding target="_blank" wherever I found it was missing

fixing anchor tags

---

ApplensBackend/Controllers/DiagnosticController.cs

Disable email alert for development environment

Disable email alert for development environment

---

ApplensBackend/Services/EmailNotificationService/EmailNotificationService.cs

Change the address alias of email alert

Change the address alias of email alert

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.scss

- Issue #217 
- Remove top margin which offset line numbers in detector editor
- Ran style tool on scss
Screenshot:

Fix Editor Line Number Offset

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-detector-changelist/tab-detector-changelist.component.scss

- The same component is used in the detector diff editor, applied alignment change to that component

Apply Line Number Alignment To Diff Editor

---

AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
ApplensBackend/Helpers/Constants.cs
Backend/Helpers/KustoConstants.cs

- Fixed style issues I noticed from reviewing a different PR
- Found global variables in C# constants file, set them to `readonly`

Style Fixes

---

AngularApp/projects/app-service-diagnostics/src/app/liveChatSettings.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-hosting-environments/services/web-hosting-environments.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-detector/generic-detector.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/logging/logging.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/utilities/versioningHelper.ts

When we decide to turn this ON, we will have to set enableV2  to true...

AB Testing - Toggling Availability and Performance view for Case Submission after checking subscriptionId

---

AngularApp/projects/app-service-diagnostics/src/app/liveChatSettings.ts
Backend/appsettings.json

Reverts Azure/Azure-AppServices-Diagnostics-Portal#264

Revert " Temporary Change : Enable Chat for Today Demo"

---

AngularApp/projects/app-service-diagnostics/src/app/app.module.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-kusto-telemetry.service.ts
AngularApp/projects/applens/src/app/app.module.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts
AngularApp/projects/diagnostic-data/src/lib/services/unhandled-exception-handler.service.spec.ts
AngularApp/projects/diagnostic-data/src/lib/services/unhandled-exception-handler.service.ts
AngularApp/projects/diagnostic-data/src/public_api.ts

- Implement unhandled exception handler which logs fatal exceptions to Kusto for monitoring and alerting
- Fully implement kusto logging to match ITelemetryProvider interface

Log Unhandled Exceptions to Kusto

---

ApplensBackend/LocalDevelopmentTemplate/Framework/Tools/LocalDevelopingHelper.psm1

Fixed the compilation output to show in VS code in Local development mode.

Fixed compilation output to show in local development

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts

- Deep linking enabled in forms only in Applens. Does not change browser URL in Portal 
- Log telemetry event for form button click
- Changed loading message
- Removed commented code
Screenshot of data logged:

Form Updates - deeplink enabled, log telemetry, change loading msg

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html

Remove rate and copy markdown buttons inside child detector view

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html

And fixing a broken link in network trace tool...

Enabling proactive tools on Dedicated Function Apps

---

AngularApp/package-lock.json
AngularApp/projects/app-service-diagnostics/src/app/app.module.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/document-search/document-search.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts

- Renamed `Form` component selector to "custom-form" to avoid collision with html `<form>` tag
- Documentation search component now shows the original html form

Renamed form component selector

---

AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-changelist/tab-changelist.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-changelist/tab-changelist.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-changelist/tab-changelist.component.ts
AngularApp/projects/applens/src/app/shared/models/commit.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
AngularApp/projects/applens/src/app/shared/services/github-api.service.ts
ApplensBackend/Controllers/GithubController.cs
ApplensBackend/Controllers/LocalDevelopmentController.cs
ApplensBackend/LocalDevelopmentTemplate/Framework/Tools/LocalDevelopingHelper.psm1
ApplensBackend/Models/Commit.cs
ApplensBackend/Services/GithubClientService/GithubClientService.cs
ApplensBackend/Services/GithubClientService/IGithubClientService.cs

Commit history for package.json

---

AngularApp/projects/applens/src/app/modules/dashboard/gist-changelist/gist-changelist.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/styles.scss

Reduce the height of gist management

---

ApplensBackend/LocalDevelopmentTemplate/Framework/Tools/StartUp.ps1
ApplensBackend/LocalDevelopmentTemplate/StartUp.cmd

Change to new share path with the production backend dlls

Change to new share path with the production backend dlls 

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/styles.scss

Style fix in modal

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-diagnostic.service.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts

- Fixed local dev package download disabled button when no code changes were detected 
- Fixed compilation output to show up in monitoring/edit and analytics/edit
- Fixed form output error message (Wanted to change this as the prev loading message was not user friendly)

Fixing UI issues

---

AngularApp/package.json
AngularApp/projects/diagnostic-data/ng-package.json
AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/services/diagnostic.service.ts

- Fixed build errors in diagnostic-data
- Require diagnostic-data to build to pass CI

Fix Build Errors

---

AngularApp/projects/app-service-diagnostics/src/app/shared/utilities/versioningHelper.ts

After this the new CPU view will show for 30% subs in case submission....

Enabling AB testing for CPU detector

---

AngularApp/projects/diagnostic-data/src/lib/components/markdown/markdown.component.html
AngularApp/projects/diagnostic-data/src/lib/components/markdown/markdown.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/detector.ts

Remove markdown border if no title is given to markdown view

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Enabling OpenShift on Azure as a resource on AppLens

Enable Open Shift on Azure as a resource on AppLens

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tabs/tabs.component.scss

- Fix lost styling for nav bar border

Fix Border on App Service Diagnostic Nav Bar

---

AngularApp/projects/app-service-diagnostics/src/app/app.module.ts
AngularApp/projects/diagnostic-data/src/lib/services/unhandled-exception-handler.service.ts
ApplensBackend/Startup.cs

- Add stack trace to unhandled exception logs
- Add site's current route to unhandled exception logs

More Unhandled Exception Information

---

ApplensBackend/Services/DiagnosticRoleClientService/DiagnosticRoleClient.cs

- trim version string from beginning of route if present

Trim version string from beginning of route on local development

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/dynamic-component/dynamic.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts

- Calling .unsubscribe on a Subject causes ObjectUnsubscribed error but does not unsubscribe the subscription
- Refactor subscriptions to automatically unsubscribe using takeWhile and takeUntil

Fix ObjectUnsubscribed Error

---

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.html
AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts

Changed confirmation messages on blade and tab opening solutions

---

AngularApp/projects/applens/src/app/modules/ase/ase-finder/ase-finder.component.ts
AngularApp/projects/applens/src/app/shared/services/ase.service.ts
AngularApp/projects/applens/src/app/shared/services/observer.service.ts
AngularApp/projects/applens/src/app/shared/services/site.service.ts
ApplensBackend/Controllers/ResourceController.cs

This reverts commit e3237304bc3bf69407317d28877095782a591fd2.
Reverting last commit to unblock people from testing their changes locally. Will revisit this change in the next few hours.

Revert "Use diagnostic role for basic site stamp information (#322)"

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-solution.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

- Validation was allowing null values through

Extended validation of ARM API inputs

---

AngularApp/package-lock.json
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-tile/category-tile.component.html

* BUG: All tiles like 'Availability and performance and configuration and management' are not accessible through keyboard under Diagnose and solve problems blade.
* BUG: 'Role and state' is not defined for all tiles under Diagnose and solve problems blade.

A few accessibility bug fixes.

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts

- When registering resource provider if 404 is received, retry 3 times.
- Added more logging if error occurs

Retry 3 times register Change Analysis

---

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts

- Change copy text to just say "Copy"

Fix Solution Copy Button Text

---

AngularApp/package-lock.json
ApplensBackend/package-lock.json

- Please commit package lock when installing or upgrading packages

Update Package Lock

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.html
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/default-solutions/default-solutions.component.html

With this PR:-
1. Enabling Web App Down on 30% subs
2. Enabling Web App Slow on 100% subs
3. Fixing a few broken links that were pointing to blogs.msdn.microsoft.com (which is retired)

Enabling web app down for 30% in case submission

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts

Wrap the resource name and limit the max width, to make sure it doesn't overlap with the informational icon.

Wrap word formatting for resource name

---

AngularApp/projects/app-service-diagnostics/src/app/supportbot/common/button-message/button-message.component.html
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check/health-check.component.html

This fixes the focus order bug in https://msazure.visualstudio.com/Antares/_workitems/edit/3723691

Accessibility Fixes

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/dynamic-component/dynamic.component.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check-v3/health-check-v3.component.html
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check-v3/health-check-v3.component.scss
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check-v3/health-check-v3.component.spec.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check-v3/health-check-v3.component.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/health-check/healthcheckmessageflow.ts
AngularApp/projects/app-service-diagnostics/src/app/supportbot/supportbot.module.ts
AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.html
AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.scss

With this PR, adding a new component HealthCheckV3Component which we can enable whenever we want to point to the AppLens v3 detectors. 
I am not currently enabling it, just getting the code reviewed and merged.
This is how it will look with v3

Change the home page health check component to point to AppLens v3

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html

With this change, any resource type can choose the order of the tiles for various categories by modifying _featureDisplayOrder array inside FeatureService

Allowing to order tiles for categories and accessibility fixes for Analysis

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts

- Removed injecting Websites service in feature service.
- Moved display order logic to just site-feature service.

Fix Diag & Solve loading for ASE

---

ApplensBackend/Services/FreshChatClientService/FreshChatClientService.cs

Updating the regex for password anonymizer.

Improving the anonymizer for masking password.

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-solution.service.ts

Add always on solution by whitelist patch arm api call

Add always on solution

---

AngularApp/projects/app-service-diagnostics/src/app/liveChatSettings.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/livechat.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-action.service.ts
AngularApp/projects/applens/src/styles.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
Backend/Controllers/ChatController.cs
Backend/Models/ChatConfiguration.cs
Backend/Services/ChatService/ChatService.cs
Backend/Services/ChatService/IChatService.cs
Backend/appsettings.json

Hi @ShekharGupta1988 , filing this PR to get a quick sense on whether I am on the right track or not. Can you please review and let me know if this direction makes sense? Also, I wasn't able to figure out if chat is enabled currently in Diagnose and Solve or not and if any of these changes will make a difference to that flow. Based on your feedback, will test it fully on Monday and update the PR accordingly

Adding SupportTopic information in Chat Backend

---

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.html
AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.ts

- Change rendering of solution to remove action button when the ActionType is Markdown
External View of Markdown Solution:
Internal View of Markdown Solution (Description and Internal Instructions are still independent although they are set to the same string in this example):

Add Markdown Solution

---

AngularApp/projects/applens/src/app/shared/models/observer.ts
AngularApp/projects/applens/src/app/shared/services/observer.service.ts
AngularApp/projects/applens/src/app/shared/services/site.service.ts
ApplensBackend/Controllers/ResourceController.cs
ApplensBackend/Services/ObserverClientService/IObserverClientService.cs
ApplensBackend/Services/ObserverClientService/SupportObserverClientService.cs

Reverts Azure/Azure-AppServices-Diagnostics-Portal#421

Revert "Support regional geomaster changes in applens"

---

Backend/appsettings.json

Edited the chat hours for US to be from 8-5 and enabled India from 7-8

Enabling chat for India team

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data-sources/tab-data-sources.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data-sources/tab-data-sources.component.scss

1. Fixing AutoHealing Blank rule issue
2. Adding OperationName to Data Sources Tab in AppLens whenever we find the operationName in response.

Auto heal UI fix to avoid adding blank rule

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts

Reverting the recent autoheal UI update from Puneet to fix a UI bug.
Discussed with Puneet.

Reverting the recent autoheal UI update from Puneet to fix a UI bug.

---

AngularApp/projects/app-service-diagnostics/src/styles/global.scss

Bug link - https://msazure.visualstudio.com/Antares/_workitems/edit/3716845
Normal Mode
High contrast mode - white on black
High contrast mode - black on white

Accessibility - Media query to fix issues for high contrast in graphs

---

AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.html
AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/change-analysis.service.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/changeanalysis-utilities.ts

- Getting changes for dependent resources by passing form query string parameters to the detector.
- Disabling zoom and drag in the graph 
- allow scan for dependent resources

Navigator fixes

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.ts

Separate tile in homepage for navigator

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

1. Will ask a specific icon from spring cloud service team.
2. Need to add a template in backend for this resource type.

Onboard spring cloud service to Applens

---

ApplensBackend/Configuration/StartupNationalCloud.cs
ApplensBackend/Program.cs

Enable AAD auth and WS-Federation for National Cloud environments.

Enabling dynamic auth

---

AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts

- Color changes to nodes and edges 
- Highlight the resource selected in the default view.  
Current view: 
With PR changes:

Navigator UI changes for understandability

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/override.json

adding APIM config

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/resource.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/arm/armResourceConfig.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-arm-config.service.ts

Switching from named regex groups to indexes for Edge/IE support.

Fix for Edge / IE support for partner diagnose and solve

---

AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts

Another bug fix for the changes view intialization

Fix the default rendering type

---

ApplensBackend/Configuration/LocalFilterProvider.cs
ApplensBackend/Configuration/Startup.cs
ApplensBackend/Configuration/StartupNationalCloud.cs
ApplensBackend/Controllers/DiagnosticController.cs
ApplensBackend/Controllers/LocalDevelopmentController.cs
ApplensBackend/Helpers/Constants.cs
ApplensBackend/Services/DiagnosticClientService/DiagnosticClient.cs
ApplensBackend/Services/EmailNotificationService/EmailNotificationService.cs
ApplensBackend/Services/EmailNotificationService/IEmailNotificationService.cs
ApplensBackend/Services/EmailNotificationService/NullableEmailNotificationService.cs

- Shortened Invoke method by ~60 lines using Linq and ternary operators for readability
- Use IEnumerable in email interface so that it does not depend on the List implementation

Refactor Invoke Method

---

AngularApp/projects/app-service-diagnostics/src/app/availability/availability.module.ts
AngularApp/projects/app-service-diagnostics/src/app/availability/availability.routeconfig.ts
AngularApp/projects/app-service-diagnostics/src/app/availability/reroute/reroute.resolver.ts

I create a resolver for rerouting to the V3 detectors and modified route config file to inject the resolver ,also hard code the analysis id for generating the full rerouting url.

Add resolver for rerouting to detectors V3

---

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts

- Internal text was not rendered when OverrideOptions was null

Fix Markdown Solution Internal Text

---

AngularApp/projects/diagnostic-data/src/lib/services/link-interceptor.service.ts

Always open links in a new tab

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/config.json

Updated the config file to show Cluster Management as its own category in AKS Diagnostics and to change the placeholder text for the search bar.

Updating config

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Improve DaaS error handling

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Update the resource type for Microsoft.ContainerRegistry

Fix the enabled resources

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/cpu-monitoring-tool/cpu-monitoring-tool.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/cpu-monitoring-tool/cpu-monitoring-tool.component.scss

1. Removing Preview Tag
2. Increasing Max duration from 7 to 30

CpuMonitoring Changes

---

AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts

1. Now timeseries support kusto query bin by any timegrain
2. Fix the issue that sometimes timeseries data won't be rendered properly

Fix the timeseries rendering issue

---

AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts

- Display last scan timestamp in UTC
- Removed .length to prevent null reference

Fixed few bugs in batch api

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts

Fixed the following bug reported:

Fixed bugs reported 

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/home.module.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

This is a temporary solution for AKS in Diagnose and Solve for China Cloud.

Stop gap aks mooncake

---

AngularApp/projects/applens/src/app/modules/dashboard/services/applens-support-topic.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/generic-support-topic.service.ts

Enable support document in detector view in Case Submission Flow

---

AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.ts
AngularApp/projects/applens/src/app/collapsible-menu/pipes/search.pipe.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts

Filter left nav by item id and name both

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/config.json

There is an extra 's' at the end of Azure Kubernetes Service. 
Change Azure Kubernetes Services -> Azure Kubernetes Service

fixing typo

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts

Stop gap aks mooncake2

---

AngularApp/projects/app-service-diagnostics/src/styles.scss
AngularApp/projects/applens/src/styles.scss
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

Chartheight

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-solution.service.ts

- Add route for a new solution for @michimune 
- Making a task to refactor whitelist out to appsettings

Add PUT config/logs to ARM API Solution Whitelist

---

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/form.ts

The UI change related to https://github.com/Azure/Azure-AppServices-Diagnostics/pull/365

Adding a RadioButtonList as an input type

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Fix the JSON

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts

Case where issue is detected - the successful checks section is collapsed
Case where no issues detected - the successful checks section is open by default

Include analysis results and show successful checks when no issue detected

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json

Adding a new category in Logic Apps Diagnostics to expose new public-facing detectors.

Updating config.json for Logic Apps to add a new category

---

AngularApp/package-lock.json
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
ApplensBackend/Controllers/DiagnosticController.cs
ApplensBackend/Helpers/Constants.cs

Changes:
- Fix in the Detector Publishing Email to include the correct alias of the person who modified the detector
- Small code refactoring to make headers code more generic and scalable.

Fix Publishing Email and Small Code Improvements

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Enable Diagnose And Solve for Fairfax. The UI will appear as follows.

Diagnose And Solve for fairfax

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Point requests from National cloud to liberation and bypass the diag role.

Point National Cloud requests to liberation

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/styles.scss

Make info box visible on scrolling down applens

---

AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.html
AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.spec.ts
AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-diagnostic.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
AngularApp/projects/applens/src/app/shared/services/github-api.service.ts
ApplensBackend/Controllers/DiagnosticController.cs
ApplensBackend/Controllers/GithubController.cs

- Add UI for Kusto Mapping Configuration
- Wire up backend to the kusto mappings configuration API

Configure kusto mapping

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-content.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/search.ts
AngularApp/projects/diagnostic-data/src/lib/services/generic-content.service.ts

Implement search component parameters like:
1. Detector Search
- Is enabled
- Max results
- Min score threshold
2. Web search
- Is Enabled
- Max Results
- Use stack ?
- Preferred sites for searching?

Implementing Parameters of Search component

---

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.ts
Backend/Services/AppInsightsService/AppInsightsService.cs

Found a NRE in our telmetry and this looks like the culprit.

Fixing null reference exception in app insights enablement

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/livechat.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/logging/bot.logging.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/logging/events.enumerations.ts

Disable fresh chat for non public subs

Nmallick1/Disable fresh chat for non Public subs

---

AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.ts

Load the default kusto mappings template. Feature got regressed after the codeLoaded addition in commit a82305bd44bd6a0fa276580fe010e5c41498a86d

Fix kusto mappings default template

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

temporarily force send diagversion header. this will break fairfax but this is a temporary mitigation.

Temporarily force send diagversion header.

---

AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.ts

Enable CXP Chat component in UI.

Enable CXP Chat component in UI.

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Point requests to liberation runtimehost for fairfax

Point requests to liberation runtimehost for fairfax

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

This will enable liberation for subs listed in current master branch. Cindy's PR has more subs listed and those will also get enabled when the PR is merged.

Enable liberation for internal subs

---

AngularApp/projects/diagnostic-data/src/lib/components/dropdown/dropdown.component.html
AngularApp/projects/diagnostic-data/src/lib/components/dropdown/dropdown.component.ts

To fix the drop-down menu can't accessible issue.
[WorkItem](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1031)

fix drop-down menu can't accessible issue

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-diagnostic.service.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
ApplensBackend/LocalDevelopmentTemplate/Framework/Tools/LocalDevelopingHelper.psm1

UI PR for https://github.com/Azure/Azure-AppServices-Diagnostics/pull/442

UX - Avoid detector authors to publish detector with same Id

---

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-markdown/app-insights-markdown.component.html
AngularApp/projects/diagnostic-data/src/lib/components/app-insights-markdown/app-insights-markdown.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/app-insights.ts

This is the frontend code change request w.r.t https://github.com/Azure/Azure-AppServices-Diagnostics/pull/439

Changing to AppInsights Rendering based on DataTable

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/config.json

Adding a preview tag to AKS Diagnostics in our blade

Adding a preview tag to AKS Diagnostics

---

AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.html
AngularApp/projects/diagnostic-data/src/lib/models/communication.ts
ApplensBackend/Models/Communication.cs
ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs
Backend/Models/Communication.cs
Backend/Services/OutageCommunicationService/OutageCommunicationService.cs

Fixes:
- Simply Comms Logic
- Add ICM number as per request from CSS

Simplify Comms logic and Add ICM number to Comms

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/compiler-response.ts

This PR enables runtime logs in the Develop mode.

View runtime logs in develop tab

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/shared/models/observer.ts

Add geomaster service address in observer response body for ASE and surface this through the request headers to the diagnostic backend

Request header addition for ASE

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/home.module.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/settings.service.ts

Open app settings page with category side nav:

Fix change app settings page for application changes detector

---

ApplensBackend/Controllers/DiagnosticController.cs

Currently, Invoke API is HTTP POST so it requires it either be called with some tool like postman or fiddler or from Applens UI. 
This PR adds HTTP GET for the Invoke API so the API can be directly called from the browser
This is just a scenario for when you only need a JSON response from the backend and its unnecessary to add UI elements to the Applens UI.
Can quickly be called from the browser with https://applens.azurewebsites.net?path={some_diagnostic_backend_path}&method={http_verb}

Added HTTP GET to Invoke API

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-time-picker/detector-time-picker.component.ts

fix bug when typing invalid value for hour(> 24) and minute(>60) input in time-picker

fix bugs when type in invaild value for in input

---

AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.html
AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.ts

Updated the UI to show a message once the case is created and added a close button.
The first time chat bubble shows following
Once the customer clicks on "Confirm & Start!", the display changes to following

CXP chat engaged message edit

---

AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data-sources/tab-data-sources.component.ts

Currently DataSources are not coming when you try to develop a detector, fixing that.

Fixing DataSources for onboarding experience

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-memory-rule/autohealing-memory-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-requests-rule/autohealing-requests-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/collapsible-list/collapsible-list.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-activity/cpu-monitoring-activity.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-sessions/cpu-monitoring-sessions.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared/components/toggle-button/toggle-button.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/cpu-monitoring-tool/cpu-monitoring-tool.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/memorydump-tool/memorydump-tool.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/profiler-tool/profiler-tool.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts

Fixing Insight in Analysis to get the right status insight and fixing a bunch of accessibility bugs in Diagnostic Tools

Tools accessibility bugs and correct insight status for Analysis View

---

AngularApp/projects/diagnostic-data/src/lib/components/changeanalysis-onboarding/changeanalysis-onboarding.component.html

Fixing accessibility bugs assigned

Accessibility bugs

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.html

Changes to automatically announce results or errors after customer hits enter in search bar.
https://msazure.visualstudio.com/Antares/_workitems/edit/7095484
https://msazure.visualstudio.com/Antares/_workitems/edit/7095494

Accessibility for search component results and announcement

---

AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/insight.ts

Fix failed [Bug 1319](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1319) due to failure when trying to pass null into  **str.trim()** in getMarkdown method
A live repo in [Applens](https://applens.azurewebsites.net/subscriptions/14548673-81fd-4315-a7eb-7eff739c6a75/resourceGroups/MyAmLINKPOC/providers/Microsoft.Web/sites/Amlink-Outlook-Addin-API/detectors/LinuxBasicWebAppInfo?startTime=2020-05-28T18:04&endTime=2020-05-29T17:49)

Fix bug in Insight Component

---

AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

This PR fixes the following three bugs:
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1315
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1316
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1318

Fix null ref exceptions

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html

- Fixing the AutoHeal issue for Status Codes Rule
- Fixing https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1317

AutoHeal UI Fix for Status Codes Rule

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts

This is just to test the DAAS Site Extension fix for National Fix before we roll out the extension update

Temp PR to check DAAS backend fix - Will revert

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/diagnostic-data/src/lib/components/data-container/data-container.component.html

Accessibility bug 7095579, 7094435, 7094435

---

AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts

Assign a request id for outgoing requests. Make it easier to for UI and user experience analysis.

Request id assignment for outgoing requests from UI in AppLens

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts

Also add checking for empty premium tools  array.

Fixing side nav not highlighted after routing change

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.html

- [7094449](https://msazure.visualstudio.com/Antares/_workitems/edit/7094449)
- [7094785](https://msazure.visualstudio.com/Antares/_workitems/edit/7094785)
- [7095100](https://msazure.visualstudio.com/Antares/_workitems/edit/7095100)
- [7095120](https://msazure.visualstudio.com/Antares/_workitems/edit/7095120)
- [7095142](https://msazure.visualstudio.com/Antares/_workitems/edit/7095142)

Fix for Diagnostic Tools accessibility bugs

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Null check for downtimes to fix UI NRE.

Null check for downtimes to fix UI NRE.

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/category.service.ts

Avoid adding duplicate categories.

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/cxp-chat-caller.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/notification.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/notification/notification.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/utilities/guid.ts
AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/cxp-chat.service.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/guid.ts

Three changes in the PR
1. Allow for SCIFrame blade to return KeyValuePair to the parent blade
2. Auto refresh the chat URL after 30 minutes of customer not engaging with chat
3. Remove the X icon from notification in case submission.

Allow for SCIFrame blade to return KeyValuePair to the parent blade

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerinstance/containergroups/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerinstance/containergroups/override.json

Adding a config file for ACI

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.scss
AngularApp/projects/app-service-diagnostics/src/app/home/components/section-divider/section-divider.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Fix 3 accessibility bugs:
|||
-- | --
| [7084192](https://msazure.visualstudio.com/Antares/_workitems/edit/7084192) | [Keyboard Navigation - App Service Diagnostics - High CPU Analysis] After selection of "High CPU Analysis" focus indicator does not land on "High CPU Analysis" Pane. |
| [7614078](https://msazure.visualstudio.com/Antares/_workitems/edit/7614078) | [Supporting the platform - App Service Diagnostics - None] At zoom 400%,Controls and keyboard focus indicator are not appearing properly on the screen. |
| | Items in Side Nav not read |
For **7614078**, I change the width and height to be percentage instead of fixed,  so when zoom in, the side-nav will not take too much space. 
And also change some styles for tooltip in side-nav, so tooltip won't take extra place within …

Fix accessibility bugs

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Fix for this service health WI: https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/edit/1337/?triage=true

Generate new request id for each arm request retry

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

**Before change, current view**
**After change**

Remove detector header in case submission view.

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-time-picker/detector-time-picker.component.ts

Fix bug : [Cannot read property 'contains' of null at <no_method>](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1364/)

Fix contains null exception

---

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

@XiaoxuHU @ShekharGupta1988 Could you help review again? This is the same with the previous PR but with another commit to fix build error

Add customized accessibility components "All" and "None" in chart module

---

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

1. Button initialized with "Select None":
2. After clicking on the button, button text becomes "Select All":
3. After clicking "Select All", button text becomes "Select None":

Make highchart button responsive to browser window size

---

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

1. Move the legends to the bottom
2. Remove border of the buttons
3. Alignment of "All/None" button and "Zoom" button:

Move legends to the bottom and remove selection button to align with zoom button

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.ts

Found a better tooltip from fabric component for our side nav:

Change tooltip to fabric tooltip

---

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts

- Change table header be bold
- Change column mode, width for each column evenly

change table header style

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Add capability to check for USSEC and identify as national cloud.

Add capability to check for USSEC and identify as national cloud.

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts

- Dynamic setting table height and add text when there is table is empty
- Enable pre-populated search results when click search bar

Add text for empty table, enable pre-populated search result

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/summary-cards/summary-cards.component.ts

- TypeError: Cannot read property 'find' of undefined in Summary Card component 
[1405](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1405/)
- Cannot read property 'getSubscriptionProperties' of undefined  at getSubscriptionProperties
[1468](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1468/)

Fix UI Exceptions

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/create-storage-account-panel/create-storage-account-panel.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/create-storage-account-panel/create-storage-account-panel.component.ts

Hoping this fixes the below UI bug
1473 | [Diagnose and Solve Portal] Cannot read property 'value' of undefined in create-storage-account-panel | app-service-diagnostics-portal\2001-2 | Active | Service Health | 0 | 8/14/2020, 5:19:06 PM

Fix value undefined in create-storage-account-panel

---

AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts

Add a event type attribute for all the logging event json object to ibiza

Add a event type attribute for all the logging event json string

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts

Fix **Cannot read property 'id' of undefined  in feature service**
[USER STORY 1474](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1474/)
I only modified code in **getCategoryIdByCategoryName** method in feature service, other places are just format issue.
For now, if can't match categoryId in category-summary component, it will hide side-nav bar.

Fix Cannot read property 'id' of undefined in feature service

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts

- Render customized search-result-list for landing page in IE
- Render old ngx-table in IE

Fix IE for search bar and data-table

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts

Fix the refresh button functionality for diagnostic tools page:
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/edit/1486/?triage=true
User Story 1486: Enable refreshing for diagnostic tools category

Fix the refresh button functionality for diagnostic tools page

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/config.json

Updating the keywords to better reflect the content of Cluster Insights

Updating the keywords for Cluster Insights

---

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/models/form.ts

Adding tooltip for form inputs:
Allow icon as input:

Add tooltip for form input

---

AngularApp/npm-shrinkwrap.json
AngularApp/package.json
AngularApp/projects/app-service-diagnostics/src/polyfills.ts
AngularApp/projects/applens/src/polyfills.ts

Fix exception [[IE 11 Compatiality]Object doesn't support this action ](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1495/)

Fix IE exception when creating Url

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-detector/generic-detector.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts
AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts

This logic is integrated behind a feature flag, will not have any production impact.

IFrame integration hackathon for case submission flow

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-comms.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-comms.service.ts
AngularApp/projects/applens/src/app/shared/models/resources.ts
AngularApp/projects/applens/src/app/shared/services/resource.service.ts
AngularApp/projects/applens/src/assets/enabledResourceTypes.json
AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.html
AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/communication.ts
ApplensBackend/Controllers/CommsController.cs
ApplensBackend/Helpers/Extensions.cs
ApplensBackend/Models/Communication.cs
ApplensBackend/Services/OutageCommunicationService/IOutageCommunicationService.cs
ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs

Changes:
- [CSS Ask] : Display Emerging Issues for few selected Products in Applens 
- [09/30 ARM Deadline] : For External flow, Move away from passing token to our controller. Instead, now calling Azure service health API.

Show Emerging Issues in Applens + Service Health Item Fix (1348)

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json

Update title and add one more category for user to have a quick check.

Modify config file to better describe our cases

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Disable downtimes from case submission

Disable downtimes from case submission

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.ts
AngularApp/projects/app-service-diagnostics/src/polyfills.ts
AngularApp/projects/applens/src/polyfills.ts

This PR fix for exceptions : 
- [1511](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1511/) [Diagnose and Solve Portal] 'IntersectionObserver' is undefined on IE11.0
- [1514](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1514/) [Diagnose and Solve Portal] Cannot read property 'name' of undefined at e._next

Fix exceptions 'IntersectionObserver' is undefined and Cannot read property 'name'

---

AngularApp/projects/app-service-diagnostics/src/app/availability/tools-menu/tools-menu.component.html
AngularApp/projects/app-service-diagnostics/src/app/availability/tools-menu/tools-menu.component.ts
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/icons-constants.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/support-tools/support-tools.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/support-tools/support-tools.component.ts

This is the change for this work item: 
https://msazure.visualstudio.com/Antares/_workitems/edit/6618144
Task 6618144: [Tinfoil] - Disable entry point

Disable premium tools section and TinFoil for all the users

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/feedback/feedback.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/pii-utilities.ts
AngularApp/projects/diagnostic-data/src/public_api.ts

I change the logic so that if estimated table height is less than threshold(50% of window height)and height is not passed from detector code, it will be set by Fabric UI. Otherwise we will override table height as before.
I also added PII replacement for feedback input

Dynamic adjust table height and check PII info 

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html

ms-vscode.csharp is now ms-dotnettools.csharp

Update C# extension name

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/insights-v4/insights-v4.component.html

Fix three accessibility bugs,
1. 7095150 - [[Screen reader - App Service Diagnostics - Search] Screen reader does not announce the position of search dropdown options.](https://msazure.visualstudio.com/Antares/_workitems/edit/7095150)
2. 7084245 - [[Screen reader - App Service Diagnostics - Diagnostic tools] Label is not associated with “Language” combo box present on “Diagnostic tools” page.](https://msazure.visualstudio.com/Antares/_workitems/edit/7095100)

Fix accessibility bugs(7095150,7095100)

---

AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts

Origins for other clouds will fetch from App Settings

Remove Sovereign Clouds

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.html

Increase the height to show the loading messages:

Fix loading formatting for Applens

---

AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts

Try to fix [1512](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1512) ‘Uncaught (in promise): Code:MissingSubscription The request did not have a subscription or a valid tenant level resource provider. at M’
All Exceptions are from **registerResource** in resource.resolver
If not able to get resourceUri from activatedRouteSnapshot, then try to get from RouterStateSnapshot. 
If both are not working then throw exception message for next step debug

Fix exception for ‘Uncaught (in promise): Code:MissingSubscription

---

AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts

While testing the staging environment I observed **an intermittent issue** when there are a lot of detectors running, sometimes the web-search component gets stuck on "Fetching web search results..." message.
This was happening because the Applens .NET Core app takes a long time to satisfy the "API key" request and the observable never emits an event to forkJoin (Still trying to figure the root cause behind this on forkJoin issues).
However taking forkJoin out of the equation and running the web search requests individually solves the problem.

Solve intermittent issue with web search

---

AngularApp/projects/diagnostic-data/src/lib/models/search.ts

Added preferred sites public documentation and integration blog for logic apps

Preferred sites addition for Logic Apps

---

AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.html

Fix for WI [1572](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1572/).
This exception is a little bit wired, exceptions are from fabric dropdown code when it was loading **LinuxAppDown Analysis**, it is supposed to not render fabric dropdown. 
I checked the code and guess it might has some issue with two ngIf for two dropdowns. And fix by using ngIf-else instead

Cannot read property 'focus' of null  from dropdown component

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-panel/risk-alerts-panel.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-panel/risk-alerts-panel.component.ts

Fix the order and add the link for overall best practice link:

Fix the order and link of best practice check panel

---

AngularApp/projects/app-service-diagnostics/src/app/genie/genie.module.ts

Provide resource service to dynamic analysis in genie

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-config-summary/autohealing-config-summary.component.ts
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/site.service.ts

- Handling exit code 0x800703e9 in crash monitoring
- Increasing default Crash Monitoring duration to 15 days
- Improving the messaging in AutoHealing when Substatus and win32 status is 0

Handling exit code 0x800703e9 in crash monitoring

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.scss
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/models/risk.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/resource.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts
AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts

- Get rid of using sessionStorage since it will need to change browser config to make sessionStorage working in incognito window
- Fix order issue for side-nav in category page after click homepage quick link

Fix to not using sessionStorage and order issue in side-nav

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.scss
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html

- Fix focus and remove unnecessary '-' in detector title
- Update feedback panel with enabling two-way communication

Enable two-way feedback and fix for detector title

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.scss
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.ts

This PR is for 
1) Add Id for each feedback for tracking
2) Fix style issue when hover over cross button in feedback panel

Change feedback style and add feedback Id

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/icons-constants.ts
AngularApp/projects/diagnostic-data/src/public_api.ts

Update tool category overview to make tool-tile style aligned with category-tile component

Update tools overview page

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/server-farm-data.service.ts

Trying to fix exceptions below,
- Cannot read property 'toString' of undefined at e.handleError
- Cannot read property 'name' of undefined at e.addAdditionalProperties
- Cannot read property 'find' of undefined at t._next

Fix exceptions

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Moved it from Microsoft.ContainerService to Microsoft.RedHatOpenShift

openShiftManagedClusters was incorrectly mapped

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts

Add portal session Id information for diagnostics tools page logging

Add portal session Id for diagnostic tools page

---

AngularApp/projects/applens/src/app/modules/main/main/main.component.html
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
AngularApp/projects/applens/src/app/shared/models/resources.ts

Add Support for Portal Session Id and VM Machine Id

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts

Updating category descriptions to fit the work count requirement

Updating category descriptions

---

AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts

This PR is for fixing regression that cause case submission not able to load

Fix for loading blad in case submission

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.ts

Fixing
- https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1637
- https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1625/
- https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1638/
and preselecting Collect Thread Stacks option in DaaS' Profiler component

Fixes for 1625 and 1637

---

AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.html
AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.ts

Fix Comm Alert background color when its mitigated

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts

Set detectorListAnalysis ViewChild reference to static.

NRE fix to downtime in Diagnose And Solve blade

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-arm-config.service.ts
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.servicefabric/clusters/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.servicefabric/clusters/override.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts

Fix config for Service Fabric and SignalR. Also, add logging in case of merging of config fails.

Diagnose And Solve portal fix for Service Fabric

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-arm-config.service.ts

Remove App Insights logging to break circular dependency

Remove App Insights logging to break circular dependency

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Log detector view loading error so we can set up alert from the client side based on this event.

Log detector view loading error

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.scss
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts

In this PR,
1) Update style for category tile so that if category tile text are not same length, each tile style will still be almost  align(tile height, tile title and tile link will be align. But tile description and keywords may not)
2) Add keywords for windows web app and diag tool

Update category tile style

---

AngularApp/projects/app-service-diagnostics/src/app/home/home.module.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-hosting-environments/services/ase-category.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-hosting-environments/services/web-hosting-environments.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/asev3-custom-view/asev3-custom-view.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/asev3-custom-view/asev3-custom-view.component.spec.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/asev3-custom-view/asev3-custom-view.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/shared.module.ts

Show a custom view with documentation to ASE V3 users. The below view will be presented after clicking any category from homepage:

Add custom view for ase v3 users

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.ts
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/diagostic-sessions-panel/diagostic-sessions-panel.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-action.service.ts

This PR is to fix some bugs that can cause ARM resource unable to open blade or rendering the category page when opening new blade.
I tested in APIM that it can open new blade for detector or category overview

fix opening blade for arm resource

---

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.html
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/models/detector.ts

This PR is for extending data-table to add filters and customize column width and visibility.
Along with backend PR, [Add Table Filters #1055](https://github.com/Azure/Azure-AppServices-Diagnostics/pull/649)

Add Table Filters

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/risk-tile/risk-tile.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-notification/risk-alerts-notification.component.ts

Majority of exceptions came from function app and linux app. One function in Risk alert service is returning null  for function/linux app while we were subscribing the response.

Fix client side exceptions

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/risk-alert.service.ts

Looks like we can not compare an observable variable by doing if( some observable variable), I notice the observable will never be subscribed..
The right fix should be returning a null observable in the function getRiskAlertNotificationResponse()

Fix risk alert loading issue

---

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.html
AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.spec.ts
AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/models/detector.ts

This PR adds a functionality to show Tabs on AppLens and D&S. The "red dot" to request attention isn't implemented yet.

Support Tab UI

---

AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Another fix for APIMissingSubscription exception,
Try to validate resource uri in resource.resolver to block problematic resource registering call

Validate resource uri before registering

---

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.ts

Added code in genie to log events related to internet search and customer interaction with results.

Log web search clicks and events in genie

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.ts

- Using Tooltip component from Fabric for better alignment in UI
- Passing empty blobSasUri from UI so the SASURI from Environment variable gets picked up by DaaS backend

Using Tooltip component from Fabric

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/genie-panel/genie-panel.component.ts
AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts

Fix the bug that genie chat text box is disabled when shield is not enable and no cognitive doc results are found

Enable genie chat text box when no document results and shield is not enabled

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts

Fix for issue 233254320 and 233291364

checking if the sessions object is really an array

---

ApplensBackend/Services/SupportTopicService/SupportTopicService.cs

Cluster for AzureSupportability changed.

Fix supportability kusto cluster

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts

This is to make Logic App use new UI

Add logic app for use new UI

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.html

Follow up fix for [BUG 9593070](https://msazure.visualstudio.com/Antares/_workitems/edit/9593070) to add alt attribute into image

Accessibility fix for BUG 9593070

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts

This PR is to fix duplicate tiles in Spring Cloud category page 
[ICM 233468650 - Diagnose and Solve Problems duplicate options for networking](https://portal.microsofticm.com/imp/v3/incidents/details/233468650/home)

Fix duplicate tiles in spring cloud

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/configFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.scss

apply defensive null checks and other minor changes in flow implementations
minor change to `.step-container` in network-checks.component.scss

Network Checking Tool bugfix

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check-step.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/info-step-view/info-step.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/input-step-view/input-step.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/configFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.scss

Fixed 2 null reference exception and other minor fixes

Fixing bugs filed in bug bash

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-quick-link.service.ts

Yun Jung and Yao will be working on the design for new features tag on homepage.
For now we will promote this to homepage as quick links for Windows Web Apps and dedicated Function Apps:

Add network checker to quick links for web app and dedicated function app

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts

This PR is for fixing name of undefined for [WI 1781](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1781/)

FIx for name undefined

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.html
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts

The feature will be enabled everywhere next week but wanted to get this PR out in the mean time
**Please do not merge this yet.**

AutoHealing UI for Linux

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/create-storage-account-panel/create-storage-account-panel.component.ts

Reverts Azure/Azure-AppServices-Diagnostics-Portal#1074 as the real issue was that this component was being called on non microsoft.web resources

Revert "removing currentSiteStatic and using currentSite"

---

AngularApp/projects/app-service-diagnostics/src/app/globals.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts

Improve DNS check and other minor fixes

Network Troubleshooter dns check improve

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/step-view-lib.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js

log ConnectivityTestTriggered telemetry for Network Troubleshooter connectivity check
minor 2 lines of changes

log ConnectivityTestTriggered event for Network Troubleshooter connectivity check

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/step-view-lib.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js

1. add 10 seconds timeout to tcpping
2. minor wording changes
3. other minor fixes

network check minor bug fixes

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/diagostic-sessions-panel/diagostic-sessions-panel.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/genie-panel/genie-panel.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/genie-panel/genie-panel.component.scss
AngularApp/projects/app-service-diagnostics/src/app/genie/common/feedback-button-message/feedback-button-message.component.html
AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/documents-search/documents-search.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.scss

This PR is to fix the below accessibility bugs:
[Bug 9586329: [Programmatic Access - App Services - Diagnose and solve problems - Genie]: Role is not define for "Send" control.](https://msazure.visualstudio.com/Antares/_workitems/edit/9586329)
[Bug 9593014: [Visual Requirement - App Services - Genie]: Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds (.article-link[_ngcontent-app-id-c28=""])](https://msazure.visualstudio.com/Antares/_workitems/edit/9593014))
[Bug 9586258: [Visual Requirement - App Services - Diagnose and solve problems - Genie]: Luminosity ratio is less than as required (4.5:1) for "type your question" edit field placeholder text.](https://msazure.visualstudio.com/Antares/_workitems/edit/9586258)
[Bug 9586283: …

Fix genie related accessibility bugs

---

AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts

Fixing bug that logs all results from Deep Search as surfaced by Bing

Fixing bug that logs all results from Deep Search as surfaced by Bing

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/site.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/storage.service.ts

- Hiding Diagnostic Tools for Xenon sites
- Change the recycle process to Recycle Container for Linux Apps in AutoHealing
- Change the permissions of SAS URI to give permissions on blobs, tables, queues

Hiding DiagnosticTools for Xenon and other small fixes

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts

PR is for migrating ISE to new D&S UI

Enable ISE for new UI

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/dropdown-step-view/dropdown-step.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/step-view-lib.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts

a simple experiment to see if this can increase the user engagement
add `NetworkCheck.DropdownExpanded` telemetry event as well

Network Troubleshooter dropdown expand by default 

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.scss
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.ts

This is to fix Japanese side nav overflow issue:

Fix localization side nav width

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check-step.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check-step.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check-step.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/check-step-view/check.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/step-view-lib.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/shared.module.ts

Implement multi-level subchecks and details side panel for `CheckStepView` per Sid's request
Only the check without subcheck can show the `detailsMarkdown` in side panel

Network Troubleshooter multi level subchecks and details markdown

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

This is being used to display app type in new applens ui

Adjusting capitalization for search suffix

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

For an easier review, toggle the whitespace check in PR settings ;-)

Fixing error handling slightly for DaaS API calls

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-risk-alert.service.ts

Function app Diagnose and Solve homepage:
This risk alert is specific for dedicated Function Apps for now. For dynamic plan, we will onboard a different set of risk alert checks.

Onboard risk alert for Function Apps

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-risk-alert.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-notification/risk-alerts-notification.component.ts

Onboard this notification detector and show it as a notification bar to deliver emerging issues:
This panel content is powered by [Function App Notification Detector](https://applens.azurewebsites.net/subscriptions/c1972e9d-b3c7-4de4-acb3-681773b28ced/resourceGroups/cindyfn/providers/Microsoft.Web/sites/cindyfntest/detectors/functionAppNotification?startTime=2021-06-09T16:40&endTime=2021-06-10T16:24) which we can update dynamically:

Onboard notification feature for Function Apps

---

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.html
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.ts

This PR is to update some styles for table filter to align with Figma design for Linux Log Viewer

update table and table filter styles

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts

Onboard keystone solution for Logic App with this [keystone detector](https://applens.azurewebsites.net/subscriptions/c258f9c0-3d64-4761-8697-cab631f28422/resourceGroups/applensdiagnostics/providers/Microsoft.Web/sites/kzlogictest2/detectors/la_standard_keystone/edit?startTime=2021-06-16T18:27&endTime=2021-06-17T18:11
)

Onboard keystone solution for Logic App and Function App

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/configFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/learnMoreFlow.js

Change Nework Troubleshooter flow wording

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.batch/batchaccounts/config.json

Match Category id to read the same as the category that is assigned to the detector.

Fix the categoryId in config for AzureBatch

---

AngularApp/projects/applens/src/app/app.module.ts
AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.html
AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.scss
AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.spec.ts
AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.ts
AngularApp/projects/applens/src/app/modules/surveys/services/surveys.service.ts
AngularApp/projects/applens/src/app/modules/surveys/surveys.module.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
ApplensBackend/Configuration/Startup.cs
ApplensBackend/Configuration/StartupNationalCloud.cs
ApplensBackend/Controllers/SurveysController.cs
ApplensBackend/Services/SurveysService/NationalCloudSurveysService.cs
ApplensBackend/Services/SurveysService/SurveysService.cs
ApplensBackend/appsettings.json

AppLens case surveys is the part of Solution Orchestrator where we take feedback from customer engineers for betterment of AppLens detectors and diagnostics.
Screenshots:
We show the detectors that were recently used for the support ticket resource and ask if any resolved the problem.
Select detectors that solved the problem
Submit
If something else helped find the solution, we ask them to tell us specific links/wikis from which we can incorporate things into our detectors.
Engineers can see the case details like description, cause, resolution text to freshen up their solution of the ticket.

AppLens Case Surveys

---

AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.html
AngularApp/projects/applens/src/app/modules/surveys/components/takesurvey/takesurvey.component.ts
ApplensBackend/Services/SurveysService/SurveysService.cs

1. Shorten the detector list.
2. Role combobox for the dropdown to display list below placeholder.
3. Message for survey already submitted.
4. Error message enhancement.

Some edits to feedback survey

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js

fixing [Fix bug 1922: commonRec is not defined/Cannot read property 'length' of undefined](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1922)

Fix bug 1922: commonRec is not defined/Cannot read property 'length' of undefined

---

AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts

Showing 5 results as default for both internal and external users

Showing 5 results from DeepSearch for external users by default

---

AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.html
AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.scss
AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.ts
AngularApp/projects/applens/src/app/modules/incidentassist/incidentassist.module.ts

When customer lands on AppLens to provide correct info
After customer enters info and clicks "Check Validation and Run Diagnostics" button - Running diagnostics with validation
After diagnostics are run
If user closes the panel

Showing AppLens insights in panel

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-hosting-environments/services/ase-category.service.ts
AngularApp/projects/app-service-diagnostics/src/assets/img/landing-home/networkingase.svg
AngularApp/projects/app-service-diagnostics/src/assets/img/landing-home/scalingase.svg

Migrating ASE to Genie V3
- Updated the categories with new icons
- Mapped each category to overview detectors
- Updated the description to fit the UI guidelines

Ase genie v3 migration

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts

Enable ASE for V3

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-action.service.ts

This PR covers the ask from Change Analysis team to switch to their new blade.

Link to new Change Analysis blade

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

noticed by coincidence that it's ASE's pesId

Update pesId for ACR

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts
AngularApp/projects/diagnostic-data/src/lib/models/documents-search-config.ts

Enabling DeepSearch for all support topics in windows and linux app service

Enabling DeepSearch for all support topics in windows and linux app service

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/commonWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetIntegrationConfigChecker.js
AngularApp/projects/diagnostic-data/src/lib/components/step-views/dropdown-step-view/dropdown-step.component.html
AngularApp/projects/diagnostic-data/src/lib/components/step-views/dropdown-step-view/dropdown-step.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/step-views/step-view-lib.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts

https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1984/
For bug 1. TypeError: Cannot read property 'replace' of null  at vnetIntegrationConfigChecker.js:65:38, add a couple condition checks before calling to this function to make sure when the function is called, the value is not null. If null, an exception is expected.
For bug 2 Cannot read property 'length' of undefined: dropdown-step.component.html:5:127, updated the component implementation and html
For bug 3 Error: getEnvironmentVariablesAsync failed:postKuduApiAsync timeout after 15s: diag-provider.ts:168:20, it was from the deprecated code. Now the deprecated code is removed and callsites were updated to refactored version

Fix bug item 1984

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/nameResolvingAndIpWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetAppSettingChecker.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetAppSettingWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetInegrationWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetIntegrationConfigChecker.js
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

1. fix minor problems in `diag-provider.ts`
2. update connection failure flow with new and refactored checks

Network Troubleshooter Improvement

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetInegrationWordings.js

Fix bug https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/query/a1fb713f-81e9-44e2-93a7-be6daf7c7ed5/ and another minor bug

fix bug 1997 and another minor bug

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

* Added Arc Appliance service to resource list
Note: There is no defined logo for Arc Appliance yet, so I used Arc K8s Logo

Adding support for Arc Appliance

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
AngularApp/projects/applens/src/assets/img/Azure-Network-Function-Manager-Device-Logo.svg

Onboarding Microsoft.HybridNetwork/devices to AppLens

Device Onboarding to AppLens

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-quick-link.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-risk-alert.service.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts

This PR is to:
1. Enable new D&S for Linux Function App
2.  Add popular quick links for Linux web app:
3. onboard Risk Alert for Linux web app.

Enable new D&S for linux function app and add quick links for linux web app

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.documentdb/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.documentdb/override.json

Add initial config.json and override.json with one category.

Add initial configs for Microsoft.DocumentDB (aka, Cosmos DB)

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
ApplensBackend/Services/GithubClientService/GithubClientService.cs

fixed not loading code from devops on edit detector page

Darreldonald load code on init

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

As per Ajay's request, I reverted the changes to searchSuffix. I also added a displayName parameter for our 'Service Type' list in AppLens VNext.

Reverted changes to searchSuffix and added displayName

---

AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/json-utilities.ts

To fix "Unexpected end of JSON input" exception

Add try parse in dropdown and fab-tab

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.scss
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/resource-home/resource-home.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.html
AngularApp/projects/applens/src/app/modules/main/main.module.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.html
AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.html
AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.scss
AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.ts
AngularApp/projects/applens/src/app/shared/shared.module.ts

Applens Banner
Feedback Notification

Create banner to switch between prod and preview slot and  Update feedback notification style

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts

Add a mapping for the new TLS/SSL settings (Preview) SSL Blade for integrated diagnostics.

Configure Integrated diagnostics for new TLS SSL blade

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts

enable network troubleshooter for VNet Outbound Connectivity support topic

---

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.html

<html>
<body>
ID | Title | State | Area Path | Tags | Comments | Changed Date
12480660 | [Usable - App Service - Availability and Performance]: Link Should not define under the info icon in performance and availability window. | New | Antares\ANTUX | A11ySev4; A11YUSABLE; Accessibility; Benchamark; Benchmark-HCL-AppServiceWebApp-OCT2021; Diagnose and Solve Problems; HCL; Win10-Firefox | 0 | 11/16/2021, 11:18:32 PM
12472116 | [Screen reader - App Service - Availability and Performance]: Name should be defined for the link present under the performance and availability window. | New | Antares\ANTUX | A11YMAS; A11ySev2; Accessibility; Benchmark; Benchmark-HCL-AppServiceWebApp-OCT2021; Diagnose and Solve Problems; HCL; MAS4.1.2; Win10-Firefox | 0 | 11/16/2021, …

More accessibility fix

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/auto-healing.module.ts
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-config-summary/autohealing-config-summary.component.ts
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action-linux/autohealing-custom-action-linux.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action-linux/autohealing-custom-action-linux.component.spec.ts
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action-linux/autohealing-custom-action-linux.component.ts
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-v2/daas-v2.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/site.ts

_This PR will be merged once ANT96 is deployed everywhere_

Adding AutoHeal for .NET core linux apps

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/nameResolvingAndIpWordings.js
AngularApp/projects/diagnostic-data/src/lib/components/step-views/dropdown-step-view/dropdown-step.component.scss

In some cases, namresolver/nslookup CLI provides wrong results, use DaaS nameresolver api to get a more accurate result.

Network troubleshooter uses DaaS nameresolver api to resolve hostname

---

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/v2-flows/genie-chat.flow.ts

Update genie welcome text

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html
AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.scss
AngularApp/projects/app-service-diagnostics/src/app/shared/components/timespan/timespan.component.scss

Change input background color with theming:

Fix theming for autoheal

---

AngularApp/package.json

Fix for static files 404 issue

Revert build applens command back

---

AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts

Get product name from searchSuffix in enableResourceTypes.json. So not break any charts/table for logging

Update product name in telemetry.service

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts

For [WI 2147](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2147)
Change logic in checking start time, so it not older than past 30 days

Update checking start time less than 30 days

---

AngularApp/angular.json
AngularApp/extra-webpack.config.js
AngularApp/package.json
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/tsconfig.app.json
ApplensBackend/appsettings.json

Quick demo
https://user-images.githubusercontent.com/8492235/146622177-aadac35b-797a-425f-9f48-5019be22c674.mp4

Code autocomplete in AppLens

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

This change ensures that the load commands are always on the top i.e. before imports added by autocomplete. Otherwise detector compilation would fail.

Autocomplete: Keep gist load def above autocomplete imports

---

AngularApp/Dockerfile
AngularApp/buildimage.bat
AngularApp/buildimage.sh
AngularApp/installNode14Repo.sh
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/step-views/dropdown-step-view/dropdown-step.component.scss
AngularApp/startcontainer.bat
AngularApp/startcontainer.sh

Calls checkSubnetIntegrationUsage detector to get result from Observer

NetworkTroubleshooter VNet deletion flow can check if a subnet is integrated with any app

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionFlow.js

fix a bug that vnet deletion flow cannot recognize the SAL is already marked with allowDeletion:true

bug fix for vnet deletion flow of Network Troubleshooter

---

AngularApp/Dockerfile
AngularApp/buildimage.bat
AngularApp/buildimage.sh
AngularApp/installNode14Repo.sh
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/step-views/dropdown-step-view/dropdown-step.component.scss
AngularApp/startcontainer.bat
AngularApp/startcontainer.sh

Cherry pick PR #1375 and #1386

ApplensRevamp Cherry pick PR #1375 and #1386 NetworkTroubleshooter VNet deletion flow can check if a subnet is integrated with any app 

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/commonWordings.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js

cherry pick PR #1388 turn on Network Troubleshooter for Linux and Container based App

cherry pick PR #1388 turn on Network Troubleshooter for Linux and Container based App

---

ApplensBackend/Configuration/StartupNationalCloud.cs
ApplensBackend/Services/ResourceConfigService/NullableResourceConfigService.cs

Forgot to add this to the last PR https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1395

Add nullable class to support ncloud

---

AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table/fab-data-table.component.ts

[App Insights Session](https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22eb1f22c0-7581-11ec-a2ee-8d0f37588799%22,%22timestamp%22:%222022-01-14T21:35:39.666Z%22%7D/ComponentId/%7B%22Name%22:%22DiagnoseAndSolvePortal%22,%22ResourceGroup%22:%22DiagnoseAndSolve%22,%22SubscriptionId%22:%22c1972e9d-b3c7-4de4-acb3-681773b28ced%22%7D)

Fix table client side exceptions

---

AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts

Introduce fields for sapProductId and sapSupportTopicId. Once we start receiving these values, we will need to work on introducing them in ArmConfig for partners, supplying the value to chat api's etc.

Introduce sapProductId and sapSupportTopicId parameters.

---

AngularApp/projects/diagnostic-data/src/lib/components/step-views/step-view-lib.ts

Same PR as https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1407
This is the same fix to main branch

Fix loading issue on safari

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/subnetDeletionFlow.js
AngularApp/projects/diagnostic-data/src/lib/components/step-views/check-step-view/check.component.html
AngularApp/projects/diagnostic-data/src/lib/components/step-views/check-step-view/check.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/step-views/step-view-lib.ts

cherry pick #1412 to ApplensRevamp, also fixing an icon alignment issue in Network Troubleshooter exists in ApplensRevamp only

cherry pick #1412 to ApplensRevamp

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Fixed resource type for redis cache

Fixed resource type for redis cache

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts

Fixed by using absolute path for routing in Applens

Fix child detector routing issue

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.app/containerapps/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.app/containerapps/override.json
AngularApp/projects/applens/src/app/modules/containerapp/containerapp-finder/containerapp-finder.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/shared/models/observer.ts
AngularApp/projects/applens/src/app/shared/providers/resource.service.provider.ts
AngularApp/projects/applens/src/assets/enabledResourceTypes.json

This PR adds the new resource provider name (Microsoft.App) for container apps to the diag portal experiences.

Add new resource provider name for container apps

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.app/containerapps/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.app/containerapps/override.json
AngularApp/projects/applens/src/app/modules/containerapp/containerapp-finder/containerapp-finder.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/shared/models/observer.ts
AngularApp/projects/applens/src/app/shared/providers/resource.service.provider.ts
AngularApp/projects/applens/src/assets/enabledResourceTypes.json

This PR is cherry-picking commit c6cd0ff7b from the main branch.

Containerapp newrp on applensrevamp

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/breadcrumb.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-common/tab-common.component.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/generic-breadcrumb.service.ts
AngularApp/projects/diagnostic-data/src/public_api.ts

1. Adding breadcrumb for navigation from parent detector to child
2. Adding failed loading section for child detectors loading not successful
3. Bug Fixing
3.1 Read startTime and endTime from url
3.2 Focus will reset to time-picker when detector loading is finished
3.3 Three loading dots in parent-child detector will disappeared after loading is done
3.4 Metric below highchart will only show data without prefix points
3.5 Revert to use stack chart as default

Add breadcrumb and fixing bugs

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/genie-panel/genie-panel.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/genie-panel/genie-panel.component.ts

This PR is to fix the two long running bugs related to genie:
https://msazure.visualstudio.com/Antares/_workitems/edit/7094812
https://msazure.visualstudio.com/Antares/_workitems/edit/9586371

Fix genie narrator accessibility bugs

---

AngularApp/projects/applens/src/app/applens-global.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/search-results/search-results.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-docs/applens-docs.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts
AngularApp/projects/applens/src/app/shared/shared.module.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts

- Enable Project Shield searching experience
- Add few colors into high-chart graph
- Update logic for showing title
- Change style for breadcrumb

Enable project shield in Applens VNext

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts

Trying PR now to ApplensRevamp instead of main

Allowlisting beta subscriptions

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-common/tab-common.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-common/tab-common.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-key.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-monitoring/tab-monitoring.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Darreldonald analytics tab

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts

Add resource info icon and panel

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts

Add CXP chat bubble to network troubleshooter tool and supply necessary sap id's

Enable CXP chat in network troubleshooter

---

AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.html
AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.scss

This reverts commit 194845bccdc53b7aa8406803b97454f842d2eec0.

Revert "Update text for Applens banner (#1466)"

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts

Reverts Azure/Azure-AppServices-Diagnostics-Portal#1480

Revert "Add resource info icon and panel"

---

AngularApp/.npmrc
AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.scss
AngularApp/projects/applens/src/app/collapsible-menu/components/search-box/search-box.component.html
AngularApp/projects/applens/src/app/collapsible-menu/components/section-divider/section-divider.component.html
AngularApp/projects/applens/src/app/collapsible-menu/components/section-divider/section-divider.component.scss
AngularApp/projects/applens/src/app/collapsible-menu/components/section-divider/section-divider.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/user-detectors/user-detectors.component.ts

Change new side nav to the original side nav with a few changes:
1. Added "overview" menu and "full detector list" menu:
2. Put "analysis" under "detectors" with other categories:

Bring back single level side nav

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

gist code can be previewed in the version selector
gist code window enlarged

added the code window for gist version selector

---

AngularApp/projects/applens/src/app/app.module.ts
AngularApp/projects/applens/src/app/applens-global.ts
AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts
AngularApp/projects/applens/src/app/shared/shared.module.ts

New PR to add resource info panel:

Fix resource info panel

---

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/time-series-instance-graph/time-series-instance-graph.component.html
AngularApp/projects/diagnostic-data/src/lib/components/time-series-instance-graph/time-series-instance-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts

Add "All/None" button, and make graph legends selectable:

Change graph to the original view

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/shared/models/devopsConfig.ts

added a save button to edit detectors page in graduation flow
saves code in the users working branch
link opens code in devops  in a new tab

Darreldonald savebutton

---

AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Fix hovering misalignment on graph

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html

i commented out the download button in the html
the command bar seems to stop working when there are more than six \<items> in it
currently there are seven so i just removed one to get it working again

removed download button

---

ApplensBackend/nuget.config

Update nuget feed to a different single feed

Update the nuget feed to point to different single feed

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/cxp-chat-caller.service.ts

Assume CXP chat is enabled for all ST's. Chat can be enabled/disabled within the CXP system.

Assume CXP chat is enabled for all ST's.

---

AngularApp/projects/applens/src/styles.scss

Changing text color for operator and punctuation

Update markdown style

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts

Caused a CRI and high site impact count.
Commit : https://github.com/Azure/DaaS/commit/a7d7a19f3c5cdd81464d6ff454a80950b4d24f56

AutoHealFix:  custom option for CLR Profiler With Thread Stack

---

AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts

Fix chart styles for dark theming

---

AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/string-utilities.ts

This PR is for improving experience for using search box in Applens side nav
- Move filtering from each menu item to side-nav.component during searching
- Add a faster string comparison algorithm([KMP Algorithm](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm)), to help improving search speed

improve search speed in side nav

---

AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.html

Update banner text for applens-old

---

AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.ts

Remove banner for preview environment

---

AngularApp/projects/applens/src/styles.scss

Fix modal again

---

AngularApp/projects/app-service-diagnostics/src/styles.scss
AngularApp/projects/applens/src/styles.scss

Fix chart tooltip font for dark mode

---

AngularApp/projects/applens/src/app/modules/dashboard/services/user-setting.service.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.html
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
AngularApp/projects/applens/src/app/shared/models/resources.ts
AngularApp/projects/applens/src/app/shared/models/user-setting.ts
ApplensBackend/Models/RecentResource.cs

Enable service type default selection as user last time selection

Enabling default Service Type in landing page

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

Adding the author alias for tracking purposes. Eg:

Appending user alias

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts

This reverts commit 8d1a4555518164efae5c6e179138334bd433c62d.

Revert "save on create (#1553)"

---

AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts

Bringing back Active PRs tab for og side nav.

add PRs tab

---

AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts

Showing inital when no profile image

---

AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts

- Fix query params when calling detector from analysis view and navigating from analysis view to detector
- Fix some style issue for Applens header

Update header style and fix query params issue

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts

- Fix a race condition when rending the recent resources(fecthing user settings against fetching enableResourceType.json)
- Fix null exception for ".includes()" in dashboard and dashboard-container
- Fix for showing analysis section when there is no analysis for that resource 
[Applens](https://applens.trafficmanager.net/subscriptions/6955155b-d8c3-4569-88c9-d26b8c7da3d5/resourceGroups/az-rg-test-extcustomer-imageinformatics/providers/Microsoft.MachineLearningServices/workspaces/mimansatestml/detectors/ml_cluster_issues?clusterName=testnopipgpu&batchAccountName=bai24234205166152017247p&batchPoolName=testnopipgpu_f372288a-7220-48e2-8fbc-494f3cbdad0b&accountVersion=22f0d13eb72e5744&region=centralindia&startTime=2022-05-10T07:02&endTime=2022-05-10T18:46)

Fixing bugs in Applens

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

Got feedback from Partners that it's not obvious which branch is selected for development. Adding a notification bar at top to show branch selection.

Branchmessage

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/favoite-detectors/favorite-detectors.component.html
AngularApp/projects/applens/src/app/modules/dashboard/favoite-detectors/favorite-detectors.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/favoite-detectors/favorite-detectors.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/applens-command-bar.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/user-setting.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.html
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts
AngularApp/projects/applens/src/app/shared/models/user-setting.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
AngularApp/projects/applens/src/styles.scss
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
ApplensBackend/AppLensV3.csproj
ApplensBackend/Controllers/UserSettingsController.cs
ApplensBackend/Models/RecentResource.cs
ApplensBackend/Services/CosmosDBHandler/CosmosDBHandlerBase.cs
ApplensBackend/Services/CosmosDBHandler/CosmosDBUserSettingHandler.cs
ApplensBackend/Services/CosmosDBHandler/ICosmosDBHandlerBase.cs
ApplensBackend/Services/CosmosDBHandler/ICosmosDBUserSettingHandler.cs

- Migrate from DocumentDB API to CosmosDB API for fully leverage CosmoDB features. Like [Partial Document Update](https://docs.microsoft.com/en-us/azure/cosmos-db/partial-document-update)
- Enable pinned detector feature in Applens. User can pin their favorite detectors in homepage and analysis/detector page

Enable Favorite Detectors in Applens

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts

Change downtime display to 24 hours

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts

Added a justification box to provide reason for accessing cross case subscription resource:
And some validation message improvements.

Durian Cosmetic changes

---

AngularApp/projects/applens/src/app/shared/applens-banner/applens-preview-banner.component.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts

Preview banner on main page for durian

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html

Auto expand observation insights for external view

---

AngularApp/projects/applens/src/app/modules/dashboard/favoite-detectors/favorite-detectors.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/services/user-setting.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts

- Add favorite detectors into side-nav
- Increase maximum pinned favorite detectors to 10
- Add logging and remove unused code

Add favorite detectors section into side-nav

---

ApplensBackend/Templates/Detector_CommunicationServices.csx
ApplensBackend/Templates/Gist_CommunicationServices.csx

Add templates for CommunicationServices

Add templates for CommunicationServices

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts

Fix for showing notification in case submission for ARM resource

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json

Our product has a new name now🎉

Azure Spring Cloud product rename

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Adding pesID for services that were missing that field

Update enabledResourceTypes.json to include PESIDs

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/shared/utilities/applens-cloud-region-utility.ts

Add ASC resource explorer link to overview page if case number is specified

Add ASC resource explorer link to overview page if case number is specified

---

Backend/Controllers/AppInsightsController.cs
Backend/Services/AppInsightsService/AppInsightsService.cs
Backend/Services/AppInsightsService/IAppInsightsService.cs

Correct AppInsights endpoint for National clouds

Fix app insights integration national clouds

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts

In overview page
In resource info blade

Add link to open stamp in AppLens

---

AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html

remove text

---

ApplensBackend/Controllers/DiagnosticController.cs

I basically searched our UI codebase to find these names:

AppLens appsettings restrictions

---

ApplensBackend/Models/RecentResource.cs
ApplensBackend/Services/CosmosDBHandler/CosmosDBUserSettingHandler.cs
ApplensBackend/Services/CosmosDBHandler/ICosmosDBUserSettingHandler.cs
ApplensBackend/appsettings.json

By adding a userId "__default", with default user settings. Every time when create a new usersetting, getting config from "__default" first

Get default user setting when creating usersetting

---

AngularApp/projects/app-service-diagnostics/src/app/globals.ts

[End to End transaction](https://ms.portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22caae90fd-95a3-4641-a523-b66894f4654c%22%2C%22ResourceGroup%22%3A%22DiagnoseAndSolve%22%2C%22Name%22%3A%22DiagnoseAndSolvePortal%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fcaae90fd-95a3-4641-a523-b66894f4654c%252FresourceGroups%252FDiagnoseAndSolve%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252FDiagnoseAndSolvePortal%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2260492b70-28d0-11ed-82db-890c9409f558%22%2C%22timestamp%22%3A%222022-08-31T01%3A58%3A14.932Z%22%2C%22cacheId%22%3A%22d72f4864-22a9-4e20-a912-dbf048376494%22%2C%22eve …

Fix for cannot read properties of undefined

---

ApplensBackend/AppLensV3.csproj
Backend/Backend.csproj
azure-pipelines.yml

- Upgrade Diag backend to 6.0
- Upgrade Applens backend to 6.0
- Update Angular build pipeline for using latest Ubuntu

Upgrade Diag backend and Applens backend to 6.0

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/shared/models/package.ts

Added Search Box popup for Detector Graduation flow

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

This reverts commit 33b59bd4e6a4e04d7cec247e2cf858a2785c744d.

Revert "Added Search Box popup for Detector Graduation flow (#1716)"

---

AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.scss

Change text color for dark mode

---

Backend/Services/EncryptionService/EncryptionService.cs

Throwing UnauthorizedAccessException when failing to decrypt using legacy method

AppInsightsEncryption - Improving logic slightly for throwing access exception

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-api.service.ts

Sku value added to request header from Azure Portal

Added sku value to header

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Fixing for [ICM 332915527](https://portal.microsofticm.com/imp/v3/incidents/details/332915527/home)

Add slash check for resource uri

---

AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.html
AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.ts
AngularApp/projects/applens/src/app/modules/incidentassist/incidentassist.module.ts
AngularApp/projects/applens/src/app/modules/incidentassist/services/incident-assistance.service.ts
AngularApp/projects/applens/src/styles.scss
ApplensBackend/Controllers/IncidentAssistanceController.cs
ApplensBackend/Services/IncidentAssistanceService/IncidentAssistanceService.cs
ApplensBackend/Services/IncidentAssistanceService/NationalCloudIncidentAssistanceService.cs

Added a command bar to access various actions for template management
Command bar options
Test the changes to the template
Manage who can author/update the template
See the list of available validations to use in the template

ICM Automation self serve feature

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
ApplensBackend/Templates/Detector_VirtualNetworkGateways.csx
ApplensBackend/Templates/Gist_VirtualNetworkGateways.csx

Adding in Microsoft.Network/virtualNetworkGateways so we can start building detectors for this specific resource.

Add Microsoft.Network/virtualNetworkGateways

---

AngularApp/projects/applens/src/app/collapsible-menu/components/search-box/search-box.component.ts

Fix for expanding side-nav item by default

Default to collapse side-nav

---

ApplensBackend/Templates/Detector_VirtualNetworkGateways.csx
ApplensBackend/Templates/Gist_VirtualNetworkGateways.csx

Corrected the Provider name for both detector and gist templates. Modified the detector layout slightly to align with the preferred detector creation layout.

Updates to virtualNetworkGateway Tempaltes

---

AngularApp/package.json

Revert change for https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1797 in ssl-local command

Revert change for ssl-local

---

AngularApp/projects/applens/src/app/modules/dashboard/user-detectors/user-detectors.component.ts
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table/fab-data-table.component.html

- Fix for input in Applens where cannot delete last character 
- Update logic for showing L2 and L3 support topic in all detector list

Fix input and add L3 support topic for all detector list

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-overview/category-overview.component.ts
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.ts
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/section-divider/section-divider.component.ts
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-risk-alert.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/risk-alert.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/integrated-solutions-view/integrated-solutions-view.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/portal-referrer-resolver/portal-referrer-resolver.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/resource-redirect/resource-redirect.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-notification/risk-alerts-notification.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/fabric-feedback/fabric-feedback.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts

As discussed with Dalibor, I changed some logging properties and add "Location" for indicating where logging is coming from

Improve logging experience

---

Backend/Services/CertificateService/CertificateService.cs

KeyVault may contain multiple certificates which are **not expired** and this can cause our logic to pick multiple certificates which is incorrect. (Found this by looking at the logs of the Staging endpoint)
Making a change to pick the latest certificate and add all the rest to the expired certificate list.

Update AppInsights Encryption Cert's latest cert determination logic

---

AngularApp/projects/diagnostic-data/src/lib/utilities/resiliencyScoreReportHelper.ts

Updating SKU density table to show updated SKU table:

Updating SKU density table

---

Backend/appsettings.json

Tested in Staging endpoint by deploying this branch to Staging and validated that the correct app setting is getting created.

Enable AppInsights Certificate Encryption

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts

When copying and pasting AppLens links especially into most applications, the URL shows up as [Applens (trafficmanager.net)](https://applens.trafficmanager.net/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/detector-development/providers/Microsoft.Security/aip/aip/detectors/CorrelationId?startTime=2022-12-06T15:03&endTime=2022-12-07T14:47).
Applications take the title of the page to convert the URL into a handy name. If we updated the title of the page to include the detector and resource name when in the context of a detector, these links would be more useful as now the resource and detector name of the detector is in the URL and it will help engineers quickly identify which page they need to go to when they have multiple AppLens tabs open …

Update Applens Page Title

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

i made the queryresponse undefined on each runcompilation call so it would re render the data sources tab
resolves an issue partners had with viewing the changes made to queries while developing detectors
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2534
- [ x] Bug fix (non-breaking change which fixes an issue)
the queryresponse is assigned undefined at the start of each runcompilation call
run a detector that executes a query in applens edit mode or create mode
view data sources
modify query and run detector again
view data sources again
- [x ] I have looked over the diffs.
- [x ] I have run the linter to catch any errors.
- [ x] There are no errors from my changes on this branch.
- [x ] I have ensured that my changes support …

refresh data sources

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

removes the whitespace in branch names for graduation
remove whitespace characters from detector id before branch string is created

remove spaces on branch names

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json

Disable keystone for logic App
As requested disabled keystone for logic app as a temporary solution as this detector is having issue

Disable Keystone for logic App

---

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts

[Bug Fix] Fix for renderingProperties undefined

Fix for renderingProperties undefined

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

This PR fixes the template name registered for Container App Environment resource type.

Fix template name for Container App Environment

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/markdown-query-dialog/markdown-query-dialog.component.ts

The markdown configuration in workflow is currently broken. This PR fixes that.

Fix the Worflow Markdown configuration

---

AngularApp/projects/applens/src/app/modules/dashboard/user-detectors/user-detectors.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/detector.ts

- This change adds the git commit sha & deployed date of detectors to all detectors view
- Ref WI https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/edit/2711/?triage=true
(https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/edit/2711/?triage=true)
Parses the commit Sha and Deployed date sent from Runtimehost backend and displays it as column 
It can be tested by going /alldetectors or Your Detectors from left side menu

Add Git version and date

---

AngularApp/projects/applens/src/app/app.module.ts

Fix for directing "Microsoft.Change/Analysis" resource to the main page
Removing ambiguous route after routing for ARM resource, so for ARM resource, it will match for route "subscriptions/:subscriptionId/resourceGroups/:resourceGroup/providers/:provider/:resourceTypeName/:resourceName" first. 
Otherwise for change analysis resource(/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/detector-development/providers/microsoft.change/analysis/aip).  
It will insert "/providers/Microsoft.Web" and redirect url will be "(/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/detector-development **/providers/Microsoft.Web/providers/microsoft.change** /analysis/aip". Hence will break routing and staying in the landing page
In the landing page, select Service Type as …

Remove ambiguous route

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

Enabling publish button for Workflows

Enabling publish button for Workflows

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html

Fix for reading metadata properties of null

Fix cannot read properties of null(reading 'metadata')

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json

This change is to enable keystone detector for Logic Apps Consumption. It was previously reverted due to a detector outage which seems to be now fixed.

Enabling keystone detector for Logic App consumption

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/commonWordings.js

Added manual troubleshooting instructions to the "not supported" message we show for linux function apps. 
Tested in local dev environment
N/A

Updated Network Troubleshooter Linux not supported text with help text

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

save/publish in create mode was failing due to branch being empty
changed the condition for selecting the method for updating the branch
go to create mode and save/publish the detector code

update branchupdate logic

---

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts

When rendering large amount of data on the Gantt Chart, Highcharts is not showing all the labels for all the data on the y-axis. To resolve this issue, we will use the length of the data in the series to calculate the chart’s height. By setting the data as a variable, the total height of the chart will change based on the length of the series data.
- calculates the chart's height by using the length of the series data
- adds a new attribute `dataLength` to represent the length of the series data
- ensures that large series data are rendered properly
- In your terminal, run the following commands
- `cd AngularApp` 
- `npm run applens` 
- Go to localhost:4200 and provide an app name e.g. `buggybakery` or `rekha-autoheal-test`
- Create a new detector and add the following code
``` …
```

Fix - Dynamically Change Gantt Chart’s Height Based on Length of Series Data

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts

Keep Successful checks list always collapsed by default in case submission.
Navigate to Azure Portal, try creating a support ticket for an AKS resource with following support topic
Create, Upgrade, Scale and Delete operations (cluster or nodepool) --> Upgrading the cluster or nodepool
Dynamic analysis is executed once all the detectors are done, they will expand the successful checks and static self help goes out of view.
With this change, the successful checks remain collapsed and a customer is able to view static self-help.

Keep Successful checks list always collapsed by default in case submission

---

AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts

line that added documents to a static list of documents got removed, caused example tab to stop working
add documents to a static list to be read from other components
go to create detector and click example tab

add back line that adds documents to the static list of documents

---

Backend/Backend.csproj
Backend/Startup.cs

Add Newtonsoft package for proper response on Bing Search API
- Tested the other two controllers AppInsights and Healthcheck, they are returning the same response as before so nothing should break.

Add Newtonsoft package for proper response on Bing Search API

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/detector-node/detector-node.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/detector-node/detector-node.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/services/workflow.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-root-node/workflow-root-node.component.ts

Fixes a bug which was causing incorrect detectorId to show up on Detector Nodes

Fix for DetectorNode to pick right detectorId

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/openai.service.ts
AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.html
AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/applens/src/app/shared/services/applens-openai.service.ts
AngularApp/projects/diagnostic-data/src/lib/services/generic-openai.service.ts

Some UX improvements to chatbot for laptop screens

Some UX improvements to chatbot for laptop screens

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/markdown-query-dialog/markdown-query-dialog.component.ts

Fix the UI for Status and Markdown as backend model changed

Fix the UI for Status and Markdown as backend model changed

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
AngularApp/projects/applens/src/app/modules/main/main/main.component.html

This is for WI 2972 to remove attribute in <app-root> component as requested
[BUG 2972 -- [Keyboard Navigation - AppLens- Welcome] Ensures aria-hidden elements do not contain focusable elements.](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2972)
Found when enable "isHiddenOnDismiss" as true for <fab-panel> on top layer component, browser will add aria-hidden to true into <app-root> in the first place
Inspect attribute in <app-root> HTML tag

Fix for aria-hidden is true in 

---

AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.html
AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.ts

Update the disclaimer message in ChatGPT

---

AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.spec.ts
AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts

Change appearance of If and Switch condition nodes

Workflow - Change appearance for Condition nodes

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/common-node-properties/common-node-properties.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/common-node-properties/common-node-properties.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/ifelse-condition-step/ifelse-condition-step.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-node/kusto-node.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-query-dialog/kusto-query-dialog.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/markdown-node/markdown-node.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/markdown-query-dialog/markdown-query-dialog.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/node-styles.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-step/switch-step.component.html
AngularApp/projects/applens/src/styles.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.scss

Ensure Workflow authoring and runtime view works with dark theme

Support dark theme for Workflow view and Authoring

---

AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.ts

This fixes a regression where the workflow Run is broken for any condition nodes.

Fix Workflow Run for If condition nodes

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/foreach-node/foreach-node.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/foreach-node/foreach-node.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/foreach-node/foreach-node.component.spec.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/foreach-node/foreach-node.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/node-actions/node-actions.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/node-base-class.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/node-title/node-title.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/services/workflow.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts

Just adding the UI stuff needed for ForEach for now but disabling that as the backend needs more work to be done.
https://dev.azure.com/msazure/One/_git/AAPT-Antares-AppServiceDiagnostics/pullrequest/7709680

Handles the UI part for the Foreach and small text updated for Arrays

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.ts

detector tooltips didnt show what the detector does. now will show the detector description
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2862
add tooltip field to the catagory nav component
take tooltip input
find detector description when menuitem is created
pass description as tooltip parameter
hover over detector name in D&S blade

description now shows as tooltip

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts

Move the Bing API call to behind ARM via detector id.
Security fix

Make call to Bing ARM detector instead of Bing API

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring-analysis/crash-monitoring-analysis.component.ts

<html>
<body>
3032 | Cannot read properties of undefined (reading 'host') | app-service-diagnostics-portal\Backlog | New | Service Health | 0 | 3/8/2023, 11:17:40 PM
</body>
</html>

CrashMonitoring bug - Fix for undefined (reading 'host')

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts

Refer to the original PR: https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1937

Adding APIM as well for Bing API migration

---

AngularApp/projects/applens/src/app/modules/dashboard/devops-deployments/devops-deployments.component.ts

removed user filter

---

AngularApp/projects/applens/src/app/modules/dashboard/devops-deployments/devops-deployments.component.ts
AngularApp/projects/applens/src/app/shared/components/devops-notification/devops-notification.component.ts

filter branches created by AppLens

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.scss

Just making the controls a bit smaller.

Reduce some control sizes for workflows

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-overview/category-overview.component.ts
AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts

This PR is for fixing emerging exceptions
- TypeError: TypeError: Cannot read properties of undefined (reading 'description')
[End to End Transaction](https://ms.portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22caae90fd-95a3-4641-a523-b66894f4654c%22%2C%22ResourceGroup%22%3A%22DiagnoseAndSolve%22%2C%22Name%22%3A%22DiagnoseAndSolvePortal%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fcaae90fd-95a3-4641-a523-b66894f4654c%252FresourceGroups%252FDiagnoseAndSolve%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252FDiagnoseAndSolvePortal%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%229bac5880-c340-11ed-a084-39c9bdb17a79%2 …

Fix for find and description undefined

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-common/tab-common.component.ts

changing url to go to edit in prod will also open ppe in new tab original tab always goes back to data
fixed tab highlights
accesibility bug with the warning message for trying to edit detectors in prod
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3037
tab highlight change triggered by childactivationend
if in prod when develop tab is clicked open edit page in ppe in new tab, original tab goes to data tab
if linked to develop tab in prod, redirect to data tab and open edit page in ppe
in ppe, change to develop tab and then to another tab (for tab highlight)
in prod, click develop tab
paste a link to the prod develop tab in the browser

ppe opens in new tab when develop is clicked in prod

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/openai-arm.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.html
AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.ts

- Fixes Loader Icon issue
- Expands the observation and issues section as soon as even 1 critical/warning insight is found.
- Character limits for when to trigger the special search.

Bug fixes for SolOrchV2

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring-analysis/crash-monitoring-analysis.component.ts

Fixes an exception in Crash Monitoring Analysis component

Fix URL exception in Crash Monitoring Analysis component

---

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/network-trace-analysis/network-trace-analysis.component.html
AngularApp/projects/applens/src/app/modules/dashboard/network-trace-analysis/network-trace-analysis.component.spec.ts
AngularApp/projects/applens/src/app/modules/dashboard/network-trace-analysis/network-trace-analysis.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
ApplensBackend/Controllers/DiagnosticController.cs
ApplensBackend/appsettings.json

The Network Trace Analysis Tool is a tool for analyzing network traces and provides possible causes of and solutions to issues on a network. 
- adds a new section `Tools` to the side nav
- adds a new tool for analyzing network traces.
- Go to http://localhost:4200/
- In the side nav, click the `Tools` section and click `Network Trace Analysis`
- When the iframe is rendered, drag and drop a trace file or choose a file using the upload button
- Click `Submit` and follow the instructions that's displayed on the screen
- Kindly use any of the trace files in this zipped file to test this tool
[test trace files.zip](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/files/11067526/test.trace.files.zip)
- The main repo for this tool can be found …

Feat - Network Trace Analysis Tool

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

This is for improve logging for ARM call failed

Improve logging in ARM Service

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

This PR is for 
- Fix for race condition when retrieving location with subscription id
- Improving logging in arm.service for error handling
Go to portal -> Select "High CPU Analysis" -> Check if still having "https://management.azure.com/subscriptions/undefined" call

Fix for undefined subscription id when calling ARM 

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts

fix network troubleshooter arm url for sovereign cloud
[3033](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3033/)
use armService.armUrl instead of hard coded hostname
tested locally

fix network troubleshooter arm url for sovereign cloud

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-case-step/switch-case-step.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-case-step/switch-case-step.component.scss
AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-case-step/switch-case-step.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-run-dialog/workflow-run-dialog.component.html
AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-run-dialog/workflow-run-dialog.component.ts
AngularApp/projects/applens/src/app/shared/models/package.ts
AngularApp/projects/applens/src/assets/enabledResourceTypes.json
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts

Post this PR, publishing of workflows will follow Detector Graduation project and we will have to redeploy all existing workflows using Graduation.
@rekhaswaminathan - I will sync up with you before I merge this as I want to understand how to get this smoothly to PROD so don't worry I will not be merging the PR even if everyone has approved :-)

Enable grad publish workflows

---

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.html

Remove 150 max length for form input

Remove 150 max length for form input

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/fleets/config.json

Minor update to fleet connectivity category text.

Fleet diagnose & solve blade category text update

---

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts

**Caught by [Automation Test](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_releaseProgress?_a=release-environment-extension&releaseId=10085&environmentId=61168&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab)**, where missing directing for Overview detectors hence it will showing as blank page
Go to AKS [Case Submission](https://ms.portal.azure.com/?websitesextension_ext=asd.env%3Dstaging#view/WebsitesExtension/SCIFrameBlade/id/%2Fsubscriptions%2F931906d8-00b9-481b-aba2-f227b237cada%2FresourceGroups%2FCanaryResources%2Fproviders%2FMicrosoft.ContainerService%2FmanagedClusters%2Fapplensdiagnoticscanaryaks/source/CaseSubmissionV2-NonContext/supportTopicId/32844699/sapSupportTopicId/d142eb20-fdf9-707d-63e8-d50cd5203c75/sapProduc …

Fix for redirecting for overview detector

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts

accessibility
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3203
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3072
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3075

accessibility bug fixes

---

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.html
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts

This is the revert change for [PR 1993](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1993) to add back maxLength up to 150. Besides adding error message to prompt if length > 150 characters

Revert change for max input length limitation

---

ApplensBackend/Services/OutageCommunicationService/IOutageCommunicationService.cs
ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs

fix comms query and remove emerging issue dead code

---

ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs

Fix Applens backend build error

Fix Applens backend build error

---

AngularApp/projects/diagnostic-data/src/lib/components/date-time-picker/date-time-picker.component.html
AngularApp/projects/diagnostic-data/src/lib/components/date-time-picker/date-time-picker.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/date-time-picker/date-time-picker.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.ts
AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/time-utilities.ts

This PR is for adding a new date time combo picker component to simplify detector-control code, as well as allow to use in cpu-monitoring component and form component
To add this component, as simple as add below in html, also you can configure for min/max date time, label, only show date picker(showDatePickerOnly), ect..
`<date-time-picker [(moment)]="moment"></date-time-picker>`
Once added this component, test if 
`<date-time-picker [(moment)]="moment" [label]="'Start'"></date-time-picker>`
`<date-time-picker [(moment)]="moment" [label]="'Start'" [disabled]="true" [required]="true"></date-time-picker>`
`<date-time-picker [(moment)]="moment" [label]="'End'" [showDatePickerOnly]="true"></date-time-picker>`

Add date-time-picker component

---

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.html
AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html
AngularApp/projects/applens/src/app/modules/main/main/main.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html

This PR is for fixing below accessibility bugs.
- [[Keyboard Navigation- App Services - High CPU Analysis] 'Go back to high CPU analysis' link is not keyboard accessible, while navigating through tab key.](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3040)
- [[Keyboard Navigation- App Lens - Welcome]: 'View all supported resource types' control is not keyboard accessible. It is not actionable with enter/ spacebar](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3147)
- [[Keyboard Navigation - App Lens - Overview]: The copy buttons available on 'Overview' blade are not keyboard accessible](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/ed …

Fixing accessibility bugs

---

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.html
AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/openai-chat/openai-chat.component.html
AngularApp/projects/diagnostic-data/src/lib/components/openai-chat/openai-chat.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/chatbot-models.ts
AngularApp/projects/diagnostic-data/src/lib/services/chatui-context.service.ts

- Adding PreProcessingMessage and PostReceiveMessage callbacks to make the chat ui component more extensible
- Updating the Chat Context service to have per chat message store (instead of global message store)

Making Chat UI component more extensible

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
ApplensBackend/Templates/Detector_ADE.csx
ApplensBackend/Templates/Detector_Devbox.csx
ApplensBackend/Templates/Gist_ADE.csx
ApplensBackend/Templates/Gist_Devbox.csx

Making changes to Devbox and ADE

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json

For APIM Diagnose and Solve, Diagnostic Tools category, Overview blade was always spinning for about a minute and then would eventually show an error message. This fix configures what detector to call for Diagnostic Tools category.
Modified config.json to add a category detector that needs to be invoked
Open Diagnose and Solve for APIM and navigate to Diagnostic Tools category
https://ms.portal.azure.com/#view/WebsitesExtension/SCIFrameBlade/id/%2Fsubscriptions%2Fef90e930-9d7f-4a60-8a99-748e0eea69de%2FresourceGroups%2Fapim-demo%2Fproviders%2FMicrosoft.ApiManagement%2Fservice%2FBrokenAPITest/categoryId/diagnostictoolsapim/optionalParameters~/%5B%7B%22key%22%3A%22categoryId%22%2C%22value%22%3A%22diagnostictoolsapim%22%7D%5D

Add an overview detector for Diagnostic Tools category for APIM

---

UITest/DiagPortalTest/DiagPortalTest.cs
UITest/DiagPortalTest/DiagPortalTest.csproj
UITest/DiagPortalTest/DiagPortalTestBase.cs
UITest/UITest.sln
UITest/UITestUtilities/BroswerUtilities.cs
UITest/UITestUtilities/JsonFileTestDataAttribute.cs
UITest/UITestUtilities/UITestBase.cs
UITest/UITestUtilities/UITestUtilities.csproj
UITest/UITestUtilities/WebDriverExtension.cs

This is for refactoring UI test code so it can be use in Applens testing as well

Update test logic

---

UITest/DiagPortalTest/CaseSubmissionTest.cs
UITest/DiagPortalTest/DiagAndSolveTest.cs
UITest/DiagPortalTest/DiagPortalTest.cs
UITest/UITestUtilities/UITestBase.cs

This PR is to update retry in UITestBase.cs

Update TestWithRetry for UITest

---

AngularApp/projects/diagnostic-data/src/lib/components/openai-chat/openai-chat.component.ts

Bug fix, support first message with session persistence too

Bug fix, support first message with session persistence too

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
AngularApp/projects/applens/src/assets/img/Azure-Chaos-Studio-Logo.svg
ApplensBackend/Templates/Detector_ChaosStudio.csx
ApplensBackend/Templates/Gist_ChaosStudio.csx

Onboarding Azure Chaos Studio

---

AngularApp/projects/applens/src/app/app.module.ts
AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
AngularApp/projects/applens/src/app/shared/components/resource-error-page/resource-error-page.component.html
AngularApp/projects/applens/src/app/shared/components/resource-error-page/resource-error-page.component.scss
AngularApp/projects/applens/src/app/shared/components/resource-error-page/resource-error-page.component.ts
AngularApp/projects/applens/src/app/shared/models/resources.ts
AngularApp/projects/applens/src/app/shared/services/site.service.ts

This PR is for adding error page if deeplink resource does not exist or Observer is returning 5xx
With any not existed resource, take `appdoesntexist` as an example, 
Go to https://applens.trafficmanager.net/subscriptions/8ee49137-b1a2-4c6f-9e7f-6fe62eaa238a/resourceGroups/JMVG/providers/Microsoft.Web/sites/appdoesntexist and check if it redirect to `/resourceError` page
Before fix it will show as blank page
Add error page for resource not exist

Update error page for resource not exist

---

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/openai-genie/openai-genie.component.ts

Use only critical insights in deep search unless there are no critical insights

Deep Search Improvements

---

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/openai-genie/openai-genie.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/openai-arm.service.ts

Insights cleaning and better formatting

GenieDeepSearch: Insights cleaning and better formatting

---

UITest/DiagPortalTest/DiagPortalTest.cs

This PR is for updating logic for logging in

Update Portal logging in for UI test

---

UITest/UITestUtilities/UITestUtilities.csproj

Update package version, fix build error

Update package version

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json

This PR is to update Arm Api Version

Update ARM API version

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/update-detector-references/update-detector-references.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts

Added telemetry logging for usage statistics for SuperGist to track number of times API is loaded, Update Detector References button is clicked, and button for bulk updating detector references and creating PR link is clicked. This allows us to monitor and track usage statistics for SuperGist feature and detector references bulk update. 
N/A
Added telemetry service to update detector references component
Added telemetry logging in update detector references component and onboarding flow component 
Adds telemetry logging to different functions within the update detector references component and onboarding flow component
Test that the telemetry is being logged by putting a debugger point in telemetry logging or checking console output

Added SuperGist Telemetry Logging Events

---

AngularApp/Dockerfile
AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsConfigChecker.js
AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsWordings.js

Updates linux to support the connectivity check api in VnetProxy
Change is required to support Network Checker work ongoing to enable Network Diagnostics from the Portal for Customers with common networking configuration
https://msazure.visualstudio.com/Antares/_workitems/edit/13004963/
Enables the Connectivity Check for Azure Functions Linux to allow customers to Diagnose and Solve typical network configuration issues. 
This has been tested locally using Portal with Local Host 
TODO ...

Add Linux Network Checking to Diagnose and Solve -> Connectivity Check

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts

This is for updating detector id under category tile

Update detector id in category tile

---

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.scss

ChatUI Component tiles alignment bug fix

---

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts

This is to update blade mapping for certificate blade
1. In the portal, go to any Windows app resource
2. Go to "certificates" in the left nav bar and click "Troubleshoot" to open D&S panel
3. Check panel is opening "Run All Certificates & Domains checks" detector or not

Update config for portal referral blade

---

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

fix bug 3433 https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3433/
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3433/

fix bug 3433

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js

enable tcpping for linux webapp
na

enable tcpping for linux webapp

---

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/dynamic-analysis/dynamic-analysis.component.ts

This PR aims to add a sorting logic to the diagnostic insights, so that consistency and cache usage is maintained for subsequent requests

Sorting genie insights alphabetically to maintain consistency

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/string-utilities.ts

- Based on meeting feedback, updated the wording to sound more like attestation than consent.
- Before parsing for Status, check if valid json

update in wording based on feedback

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts

1. Adding logs for analysis and parent-child detector
2. Fix a gramma issue for time picker message
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2650
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3475

Adding log for analysis/parent-child detector

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Enabling workflows feature for AKS

Enable Workflows for AKS

---

AngularApp/projects/applens/src/app/shared/services/applens-http-interceptor.service.ts

Removed breaking change

---

AngularApp/projects/applens/src/app/modules/dashboard/kustogpt/kustogpt.component.html

Kusto copilot UI not loading
Fix a typo by removing ';'

Fix a typo in HTML

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.html
AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts
AngularApp/projects/diagnostic-data/src/lib/components/workflow-accept-userinput/workflow-accept-userinput.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-condition-node/workflow-condition-node.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.scss
AngularApp/projects/diagnostic-data/src/lib/components/workflow-view/workflow-view.component.ts

- Adding time picker for workflow run experience
- Enabling keyboard and screen reader accessibility for workflow run experience
- Showing errors for the diagnostic sessions table for Linux Web Apps

Workflows accessibility changes and adding time picker control

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts

Fix a broken Network Troubleshooter subscription selection experience because of armservice changes made recently

add modifyUrl to createUrl function

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js

fix a small network troubleshooter bug

fix a small network troubleshooter bug

---

ApplensBackend/Configuration/StartupPublicAzure.cs

Handling for when OpenAI is disabled.

OpenAI setting handling

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

- Enable deleting of workflows from AppLens UI.
- Also handle scenario properly where a detector is marked InternalOnly=true from InternalOnly=false
- Disable Copilot button for workflows

Enable Workflow delete functionality from AppLens

---

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts

Time series graph supports plotting multiple time bands based on `timeBands` option
This feature is needed by `Correlation Analyzer detector` I am working on

dynamic-data supports time bands

---

AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts

gist categories were not sorted
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2958
sort the gist categories

sort gist categories

---

AngularApp/projects/applens/src/app/modules/dashboard/network-trace-analysis/network-trace-analysis.component.ts

This PR uses the applensglobal updateheader method to display "Network trace analysis" as the header when the tool is opened

Update Applens Header for Network Trace Analysis Tool

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
ApplensBackend/Templates/Detector_CloudService.csx
ApplensBackend/Templates/Gist_CloudService.csx

Azure cloud service product onboard on AppLens platform, more detectors will be added later.
It will help engineers to troubleshoot specific issues of cloud service efficiently.
- New configuration section on AngularApp\projects\applens\src\assets\enabledResourceTypes.json
- New add ApplensBackend\Templates\Detector_CloudService.csx
- New add ApplensBackend\Templates\Gist_CloudService.csx
- creates a new rendering type 
Microsoft.ClassicCompute/domainNames
Testing it via local environment 
I checked the other product and follow the same way to add an example for azure cloud service.

Onboard azure cloud service in applens

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json

Enable workflows for billing and remove Storage as a supported resource.

Enable workflows for billing and remove Storage as a supported resource

---

AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-node/kusto-node.component.ts
ApplensBackend/Templates/WorkflowKustoNode_LinuxApp.txt

- Handling a NRE in create-workflow-component
- Generalizing Kusto Query format for partners Workflow nodes
- Adding default query template for Linux WebApps

Generalizing Kusto query in Workflows for partners and minor fixes

---

AngularApp/projects/diagnostic-data/src/lib/services/parse-resource.service.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts

This PR is for updating product name for telemetry
type is "microsoft.logic/workflows" - Azure Logic App
kind contains "workflowapp" - Azure Logic App Standard

Update product name

---

AngularApp/projects/applens/src/app/modules/main/main/main.component.ts

When users provide an invalid resource id with the ARM Resource ID service type selected, they see an error message informing them that the resource ID is invalid. When they try to correct this by selecting a different service type (e.g. App Service) and provide a valid app name, the UI does nothing when they click the Continue button
- resets the error message when a new service type is selected, or the resource type is updated.
- On Applens main page, select ARM resource ID as service type
- Provide wrong resource id
- Click Continue and error is displayed
- Change service type to App Service
- Click Continue and nothing happens
- On Applens main page, select ARM resource ID as service type
- Provide wrong resource id
- Click Continue and error is displayed
- Change service type to App …

Fix bug on Applens UI

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

bug fix
checks the id for the saved detector and gives user an error if the id is changed

added detection and new error message

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts

add submitOnSelection option to dropdown component and childDetector=true parameter to detector-list component

add submitOnSelection option to dropdown component and childDetector=true parameter to detector-list component

---

AngularApp/projects/applens/src/app/modules/main/main/main.component.html
AngularApp/projects/applens/src/app/modules/main/main/main.component.ts

Since it could be quite difficult for a user to remember the exact time a resource was deleted or failed creation, we decided to improve the user experience by excluding the time field when the user is selecting a date when the resource was deleted or failed creation and also, show a loading spinner with a message.
- updates the UI to only include date picker and show loading spinner w/ message when we're trying to validate the resource in the ARM cluster
Due to permission restrictions when accessing the ARM cluster locally, this feature can only be tested in the staging/production environment.
To test
- Go to Applens homepage
- Select ARM Resource ID in the Service type dropdown
- Provide a deleted resource ID
- Click Continue
- Because the resource wasn't found, the homepage is …

Update the UI to Only Include Date Picker and Show Loading Spinner w/ Message

---

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/form.ts

fix the issue of dropdown submitOnSelection feature doesn't completely work

fix form dropdown submitOnSelection feature

---

AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.html
AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.scss

Change icon and text for CXP chat bubble

Change CXP Chat icon

---

AngularApp/projects/app-service-diagnostics/src/styles.scss

Add a top border for panel in D&S to differentiate between panel and Ibiza

Update with top border

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts

Fix json parse error

---

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
AngularApp/projects/applens/src/assets/img/Azure DevOps-Logo.svg
ApplensBackend/Templates/Detector_DevOps.csx
ApplensBackend/Templates/Gist_DevOps.csx

Onboarding DevOps

---

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.html
AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.scss

Chat styling changes

---

ApplensBackend/Controllers/IncidentAssistanceController.cs

Return Unauthorized Response for Calls to Incident Related Endpoints

---

ApplensBackend/Extensions/AuthServiceCollectionExtensions.cs
ApplensBackend/appsettings.PublicAzure.json

fix forged aad token issue

---

ApplensBackend/Controllers/DetectorGistTemplateController.cs
ApplensBackend/Extensions/AuthServiceCollectionExtensions.cs
ApplensBackend/appsettings.PublicAzure.json
ApplensBackend/appsettings.json

Add validation logic for only allowed AppId otherwise request will be failed

Add validating for appId

---

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.scss

This is to update document section styling
[WI 3571: Apollo Articles experience is not consistent](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3571)
Choose an App Service Windows resource in case submission, select Availability and Performance > Web App Down or Reporting Errors, check if "Additional troubleshooting resources" section is showing as card style or not

update document section styling

---

ApplensBackend/Controllers/CommsController.cs
ApplensBackend/Controllers/InsightsController.cs
ApplensBackend/Controllers/LocalDevelopmentController.cs
ApplensBackend/Controllers/SurveysController.cs
ApplensBackend/Controllers/WorkflowUsersController.cs
ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs

fixing controllers

---

AngularApp/projects/diagnostic-data/src/lib/components/fab-tab/fab-tab.component.html

There is an issue where a Form inside a Tab doesn't work correctly. Pressing a submit button has no effect. This PR fixes this problem.
This PR updates the fab-tab.component.html. The issue occurs because the fab-tab component uses a dynamic-data internally, and some necessary properties are missing.
Create a new detector with the following detector code, run, and press the button:
[AppFilter(AppType = AppType.WebApp, PlatformType = PlatformType.Windows, StackType = StackType.All)]
[Definition(Id = "aaa", Name = "aaa", Author = "mikono", Description = "")]
public async static Task<Response> Run(DataProviders dp, OperationContext<App> cxt, Response res)
{
if (cxt.Form == null)
{
var r1 = new Response();
Form f = new Form(1);
Textbox t = new Textbox(1, "Label for input", true);
Button b = …

Fix: Form in Tab doesn't work

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler/profiler.component.html

Fixing profiler buttons. The highlighting broke in PROD

Fix profiler buttons

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/resource-redirect/resource-redirect.component.ts
AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts

This PR is for 
1. Adding logging for PesId for all events(Better approach might be getting pesId from Ibiza)
2. Fix null reference for include in solution.component

Add loggging for pesId

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

preserve shield in metadata

---

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js

App Service VNet integration now supports DNS settings more than 2, thus update the corresponding logic in Network Troubleshooter

network troubleshooter vnet dns fix

---

AngularApp/projects/diagnostic-data/src/lib/components/workflow-accept-userinput/workflow-accept-userinput.component.html
AngularApp/projects/diagnostic-data/src/lib/components/workflow-accept-userinput/workflow-accept-userinput.component.ts
AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts

The UX changes required to support the backend functionality for the PR -

Changes required to support worflow input options for select

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts

- Add logging for feature path routing
- Fix APIs for getting app settings

Add logging for feature path routing

---

AngularApp/Dockerfile

- The image used is not supported anymore and our repo is flagged by  scanners

Delete DockerFile - its not maintained

---

Backend/Backend.csproj

Update vulnerability package

---

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html

Fix cannot read property of null (reading "Description")
[End to End Transaction](https://ms.portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22caae90fd-95a3-4641-a523-b66894f4654c%22%2C%22ResourceGroup%22%3A%22DiagnoseAndSolve%22%2C%22Name%22%3A%22DiagnoseAndSolvePortal%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fcaae90fd-95a3-4641-a523-b66894f4654c%252FresourceGroups%252FDiagnoseAndSolve%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252FDiagnoseAndSolvePortal%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22dd134b4d-3915-11ee-8472-0022487866b3%22%2C%22timestamp%22%3A%222023-08-12T13%3A40%3A27.110Z%22%2C%22cacheId …

Fix cannot read property of null 

---

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.cache/redis/config.json
AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.cache/redis/override.json

Add redis cache arm resource config
Enable app lens for redis cache in diagnose and solve
Partner onboarding
Partner onboarding
https://applensdiagnostics.azurewebsites.net/?p=79

Add redis cache arm resource config

---

AngularApp/projects/applens/src/app/modules/dashboard/communication-toolkit/communication-toolkit.component.ts

This PR adds telemetry logging for when a message is copied from RCA Toolkit through the keyboard : control c OR command C. 
Related to RCA Toolkit
Added changes to code in communication-toolkit.component.ts 
This code utilizes Angular's "HostListener" decorator which can be used to listen for DOM events in order to detect control c or command c operations. https://angular.io/api/core/HostListener
In order to test, one can try to copy a message/RCA from the RCA toolkit by using control/command c and see if an event is outputted

added logging for control c or command c message copied for rca

---

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.html
AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.scss

Cherry pick from https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/commit/798a822cf876139432a9f74c7184e81ffb312f58 to update chat-box style

Update chat-ui styles

---

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
UITest/DiagPortalTest/testConfig.json

- Fix product name showing as "Azure Web App" instead of "microsoft.web/sites"
- Add validating featurePath from deeplink. Only routing when detector id exist
- Updating UI test detector name for AKS

Fix logging product name, add validating feature path, update detector name for UI testing

---

AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.html
AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.ts
AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
AngularApp/projects/diagnostic-data/src/lib/utilities/string-search-utilities.ts
AngularApp/projects/diagnostic-data/src/public_api.ts

This is to use another search algorithm see if it can reduce searching time
[Performance - Filtering the side nav on AppLens](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3181/)

Update search algorithm for Applens side-nav

---

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.scss

Fix for Chat UI CSS

---

AngularApp/projects/applens/src/app/modules/dashboard/kustogpt/kustogpt.component.ts

Exclude Analytics table from requiring EventPrimaryStampName filter in query

Adjust query best practice check

---

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.ts

Fix for https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3679

Fixing Null resourceId in AppInsights enable component

---

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html
AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts

This is to update logic for fixing button issue in command bar in editing experience
For <fab-command-bar-item> need to use `display:none` to control display/hide, `*ngIf` will break button functionality

Update logic for show/hide copilot button

---

UITest/DiagPortalTest/DiagPortalTest.csproj
UITest/DiagPortalTest/testConfig.json
UITest/UITestUtilities/BroswerUtilities.cs
UITest/UITestUtilities/UITestUtilities.csproj

This PR is for fixing UI testing failure in pipeline

Fix UI test issue

---

.github/workflows/lockdown.yml
README.md

Disabling create PR and update ReadMe

Update readme and add github action
