Azure/Azure-AppServices-Diagnostics-Portal

app/availability/analysis/memory-analysis/memory-analysis.component.ts
Sometimes the memory analysis does not return one of the detectors that it should, this should be handled and not stop the other detectors from showing the results
=> Fix issue when memory does not return one of the detectors

app/availability/analysis/tcpconnectionsanalysis/tcp-connections-analysis.component.ts
Our code for handling the detector name change had a small bug where in I forgot to change \ check for graphMetaData and this currently broke the "Connection Rejections" in support center. Making a fix for the same.
=> Removing the whole portexhaustion stuff

app/availability/availability.routeconfig.ts, app/shared/components/daas-sessions/daas-sessions.component.html, app/shared/components/daas-sessions/daas-sessions.component.ts, app/shared/components/daas/daas.component.html, app/shared/components/daas/daas.component.ts, app/shared/components/daas/profiler.component.html, app/shared/components/daas/profiler.component.ts, app/shared/components/tools/http-loganalysis-tool/http-loganalysis-tool.component.html, app/shared/components/tools/http-loganalysis-tool/http-loganalysis-tool.component.ts, app/shared/components/tools/java-memorydump-tool/java-memorydump-tool.component.ts, app/shared/components/tools/java-threaddump-tool/java-threaddump-tool.component.ts, app/shared/components/tools/memorydump-tool/memorydump-tool.component.ts, app/shared/components/tools/php-logsanalyzer-tool/php-logsanalyzer-tool.component.html, app/shared/components/tools/php-logsanalyzer-tool/php-logsanalyzer-tool.component.ts, app/shared/components/tools/php-processanalyzer-tool/php-processanalyzer-tool.component.html, app/shared/components/tools/php-processanalyzer-tool/php-processanalyzer-tool.component.ts, app/shared/components/tools/profiler-tool/profiler-tool.component.ts, app/shared/components/tools/styles/daasstyles.css, app/shared/models/daas.ts, app/shared/services/daas.service.ts, app/shared/services/urielements.service.ts, app/shared/shared.module.ts, app/solutions/components/specific-solutions/java-threaddump-solution/java-threaddump-solution.component.ts, app/solutions/components/specific-solutions/memorydump-solution/memorydump-solution.component.ts, app/solutions/components/specific-solutions/profiling-solution/profiling-solution.component.ts
1. Adding PHP Logs, PHP Report tools from DAAS 
2. Leveraging DAAS's feature to validate whether HTTP logs and PHP logs have been enabled or not
3.  Adding support for generating raw thread report in profiler
4. Removing caching for all DAAS components as they are reflecting incorrect data due to cache
5. Ensuring that all the DAAS tools show a warning if they site is not running in Dedicated Tiers
=> Adding More DAAS Tools and Improving UI for Profiler to enable collecting raw stack traces

src/app/shared/services/categories.service.ts
Web App Down and Web App Restarted now point to linux specific generic detectors.
They do not show up under Management and Config anymore
=> Add Web App Down and Restart for Linux

src/app/shared/services/livechat.service.ts
Had a <= instead of < in the comparison which was resulting in 1 extra hour of business for live chat
=> Fix Business Hour logic

src/app/shared/services/livechat.service.ts
We noticed in case submission that our blade opens in full screen, so customers have to scroll left to type in customer verbatim. Due to that, chat widget (which is right now on the right hand side of our blade) and the popup is not visible on smaller screen sizes.
Hence for case submission, moving the chat icon to left
=> Moving chat to left for case submission flow

src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html, src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts, src/app/auto-healing/autohealing.component.ts, src/app/shared/components/daas-main/daas-main.component.html, src/app/shared/components/daas-main/daas-main.component.ts, src/app/shared/components/daas-sessions/daas-sessions.component.html, src/app/shared/components/daas/daas-scaleup/daas-scaleup.component.css, src/app/shared/components/daas/daas-scaleup/daas-scaleup.component.html, src/app/shared/components/daas/daas-scaleup/daas-scaleup.component.spec.ts, src/app/shared/components/daas/daas-scaleup/daas-scaleup.component.ts, src/app/shared/components/daas/daas-validator.component.html, src/app/shared/components/daas/daas-validator.component.ts, src/app/shared/components/daas/daas.component.html, src/app/shared/components/daas/daas.component.ts, src/app/shared/components/daas/profiler.component.html, src/app/shared/components/daas/profiler.component.ts, src/app/shared/shared.module.ts
1. Allowing DAAS to work only on Standard Tier and removing the Basic Tier
2. Brought back the analyzerStatus messages that got lot over a period of time
3. Adding a DAAS Scale up Component
4. Parallelizing a few calls in DAAS Validator component
5. Added Retry on check for Daas Webjob state as that can take some time to load
6. Fixing some null checks.
Quick Preview when non paid tier used...
=> Allowing DAAS to work only on Standard SKU and giving an option to Scale Up

AngularApp/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.css, AngularApp/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html, AngularApp/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts, AngularApp/src/app/auto-healing/autohealing.component.css, AngularApp/src/app/shared/components/daas/daas-validator.component.html, AngularApp/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/src/app/shared/components/daas/daas.component.html, AngularApp/src/app/shared/components/daas/daas.component.ts, AngularApp/src/app/shared/components/daas/profiler.component.html, AngularApp/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html, AngularApp/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.ts, AngularApp/src/app/shared/components/tools/styles/daasstyles.css, AngularApp/src/app/shared/services/daas.service.ts, AngularApp/src/app/shared/services/urielements.service.ts
In this PR
- Ensuring user can run diagnostic tools if he is part of Website Contributor
- Improving error handling message for Network Trace component if user does not have app service plan permissions
- correcting message in AutoHealing component to call out that custom action can execute multiple times and suggesting user to choose CollectKillAnalyze option
- Autohealing component -> DAAS Tools will show properly even for Website contributor
- Added logic to implement a Cancel Session button in DAAS UI but I found that the DAAS Cancellation logic from backend needs some improvement **so leaving the Cancel button in commented mode** but adding the required code logic so this can be flipped easily when required.
=> Changes to diagnostic tools so website contributors can collect data

AngularApp/src/app/shared/components/instance-view-graph/instance-view-graph.component.html, AngularApp/src/app/shared/components/instance-view-graph/instance-view-graph.component.ts
This is what the customers were seeing:
I increased the height but also hid the legend when there are too many sites so that this doesn't happen.
=> Hide Legend when there are numerous sites in one server farm

ApplensBackend/AppLensV3.csproj
Solving these two errors:
```
warning NU1608: Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.DependencyCollector 2.4.1 requires Microsoft.ApplicationInsights (= 2.4.0) but version Microsoft.ApplicationInsights 2.6.4 was resolved.
warning NU1701: Package 'Microsoft.ApplicationInsights.Web 2.6.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project
```
=> Updating Nuget Packages

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.ts
@stevenernst131 - would appreciate if you validate the english of this sentence too :) 
_CAUTION: You are choosing to run diagnostics on more than 50% of the instances serving your app. If you already know a particular instance is misbehaving, you can choose to run Diagnostic only on that instance. Running diagnostic tools on all instances simultaneously can cause significant downtime for your web app. Are you sure you want to continue ?_
=> Adding a warning for diagnostics when customers select all instances

AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/models/resources.ts
Allow only enabled resource types in AppLens and make those routes case insensitive. If some random resource is entered, the following error message will show up.
=> Allow only enabled resource types in AppLens and make those routes case insensitive 

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/cpu-monitoring-tool/cpu-monitoring-tool.component.html
Without this margin there is a wobbling scrollbar that is coming in Edge which is really annoying. In most of the components we have some text below the animation so this effect is not visible.
=> Fix scrollbars coming in Edge while the component is loading

AngularApp/projects/app-service-diagnostics/src/app/availability/tools-menu/tools-menu.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/support-tools/support-tools.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-action.service.ts
Azure app services is decommissioning Z-Ray for web apps. Starting Monday (3/11), no new web apps will be able to install this add-on. The existing sites which has this add-on will continue to use it till some time. These sites have been proactively notified.
- For sites which doesn't use Zray, the option to enable it (shown as `PHP Debugging` in `Diagnostic Tools`) will not show up
- If the site has Zray premier add-on enabled, the option will show up and instead of opening Ibiza blade(which is also getting removed), customers will be redirected to ZRay Site Extension in Kudu.
=> Decommission ZRay feature

ApplensBackend/Services/DiagnosticRoleClientService/DiagnosticRoleClient.cs
Passing the x-ms-internal-view header now for ARM resource types in DiagnosticRoleClient Execute method. AddAscInsight was not working due to this missing header for Logic Apps and AKS.
=> Passing the x-ms-internal-view header now for ARM resource types

AngularApp/projects/app-service-diagnostics/src/app/liveChatSettings.ts
| Support Topics |
|---------------------|
| Web App Restarted |
| Configuring SSL     |
| Configuring Domains |
| Backup and Restore  |
Will wait for `IP Configuration` support topic as the detector needs to be enabled/modified for Linux Web App
=> Enable Chat for More Support Topics in Linux

AngularApp/projects/diagnostic-data/src/lib/models/detector.ts
I had merge conflicts when merging forms-ui branch to master, while resolving it the enums got out of order causing solution to render instead of form.
=> Incorrect order of enum in server side vs client side caused UI error

AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
Added a check in the date range selection control to check for invalid dates. Also defaulting to past 24 hours in case someone bypasses the UX and hits the applens URL directly. Error messages are displayed as follows.
I am aesthetically challenged, please suggest a better highlighting color for the error message :)
=> Time range check on detectors

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/utilities/versioningHelper.ts
Enabling CPU detector instead of web app down in case submission
And enabling this for beta subscriptions so we can test it before we start A/B testing.
=> Enabling CPU detector in case submission

AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts
I think this part was removed by accident while we migrate our projects...
That's why we don't get any child detector summary data anymore
=> Add back child detector event logging data

ApplensBackend/appsettings.json
To run the project locally, we need this value to bypass the authentication part of the backend. This configuration value was missing from appsettings.
=> Add missing config value to appsettings

ApplensBackend/Services/DiagnosticRoleClientService/DiagnosticRoleClient.cs
If the resource name has "v2" or "v4" in it then it will be replaced with string.empty thus sending wrong resource name to backend during local development.
=> Fix x-ms-path editing

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.html, AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts, AngularApp/projects/diagnostic-data/src/lib/utilities/string-utilities.ts, AngularApp/projects/diagnostic-data/src/lib/utilities/uri-utilities.ts
- Detector link can be placed anywhere in internal solution text
- If the format string {detectorlink} is not present, end the internal text with the default detector link markdown;
- Fixed detector link builder
=> Configure Detector Link in Internal Solution Text

AngularApp/projects/applens/src/app/modules/ase/ase-finder/ase-finder.component.ts, AngularApp/projects/applens/src/app/shared/services/ase.service.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/site.service.ts, ApplensBackend/Controllers/ResourceController.cs
Today, when the end user requests for a site in applens, the backend makes a call to SupportBayApi to get basic site information. Instead of making that call to SupportBayApi we will make the call to diagnostic backend instead to get this site info. The same will go as for stamp/ase.
=> Use diagnostic role for basic site stamp information

AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
Fixing the time selector for Edge. momentJS was falling back on creating date via js Date which wasn't working on Edge and hence was creating an invalid moment object causing the issue. Replaced .toString() with .format() which converts the date to one of the ISO date formats and conversion back from string to moment object always works in all browsers. Tested with Edge, Chrome and IE 11. Assuming it works with the rest of the browsers :-)
=> Fixing the time selector error for Edge

AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/utilities/changeanalysis-utilities.ts
This PR fixes the following issues:
- When Change Analysis api returns null for old value/new value, the monaco editor throws js error and does not show diff view. So adding null check to set empty string in those cases.
- Clicking anywhere on timeline (not a data point) triggers select event, and causes change set id set to be undefined. Adding check here to avoid setting change set id in those cases.
=> Adding null check

AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-detector/generic-detector.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tabs/tabs.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.html, AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
In this pull request, the following fixes have been done
1. Added successful detectors to the bottom of the analysis as successful checks
2. Highlighted the selected Analysis detector in AppLens
3. Fixed the Analysis tab to open a new detector for legacy analysis detectors
4. Added an Expand View when the detector is loaded under analysis (This is done in case someone needs to get the DataSources and KUSTO queries etc.)
5. Changed error handling in Analysis layer so that if a child detector fails, rest of the detectors still load
6. Scrolling to the top when a child detector is clicked under the Analysis list
7. Improved the card navigation to route to analysis route if the card added is of type DetectorType.Analysis
8. Fixed a bug in loading of Solutions when multiple detectors added …
=> Fixes to Analysis Layer after testing a few end to end scenarios

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tile-list/tile-list.component.html, AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/detector-summary/detector-summary.component.html, AngularApp/projects/app-service-diagnostics/src/styles/controls/_tiles.scss
Tiles appearing under Diagnostics tools and Category chat window are not accessible through keyboard navigation.
- Made the tile navigation possible through Tab and Shift+Tab
- Pressing enter key on detector summary list takes to detector in genie chat window
- Pressing enter key on Diagnostic tool tile opens the tool window
- Tested in Chrome and Edge.
Screenshots from Keros showing tab stops
=> Fix keyboard navigation on tiles

AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.html
Bug 3729814: [Screen reader - Azure Web phase3 - Best Practices] Name and role is not defined for 'Always on disabled' control under 'Always on check' list item.
Bug 3730151: [Screen reader - Azure Web phase3 - Best Practices] Name, role and state is not defined for 'ARR affinity is enabled' control under 'ARR affinity check' list item.
Bug 3729955: [Keyboard navigation - Azure Web phase3 - Best Practices] 'Always on disabled' control is not accessible through keyboard under 'Always on check' list item.
Bug 3730083: [Screen reader - Azure Web phase3 - Best Practices] Name and role is not defined for 'App service plan host less than 15 active site' control under 'App service plan density check' list item.
Bug 3730136: [Keyboard navigation - Azure Web phase3 - Best Practices] 'ARR affinity …
=> Insight accessibility fix for name, role, state and keyboard access

AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.ts
This was a known issue in Angular material table expand row not working with `display: none `https://github.com/angular/components/issues/15596
- Tested Applens Edge & Chrome
- Tested App Service Diagnostics Edge & Chrome
Edge:
Chrome:
=> Fix row expansion not working in edge

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/utilities/versioningHelper.ts
With this PR, we are
1. Enabling v3 **High Memory Usage** detector in Case Submission for all subs
2. Enabling v3 **Web App Slow** Analysis for beta subscriptions to check if Analysis View loads properly in case submission. After testing this out fully, will send another PR to set `enableV2 =true`
=> Enable v3 Memory Detector for case submission and Slow response Analysis for beta subs

AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
1. Hide gists section if empty
2. Collapase left hand detector list by default, and expand automatically if search happens
=> Hide gists section if empty and collapase left hand detector list by default

AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
The caching issue was happening because the startTime was getting rounded to 5 minutes. This was happening only if a detector had a Chart and the Chart was actually rounding the startTime to 5 minute interval.
The fix is to return a clone of StartTime object so that the original startTime doesnt get changed when chart is rendered.
Thanks to @stevenernst131  for his quick guidance :-)
=> Fixing the Caching issue of detectors

AngularApp/projects/diagnostic-data/src/lib/utilities/changeanalysis-utilities.ts
The value type of number is not handled, and monaco is complaining saying no original or modified model for all following changes.
=> Fix the minor bug that the changes view shows nothing

AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts
1. Tweak the enablement button group so it works better on narrow sized screen
2. Update the last scan message so we don't confuse user with the concept of code scan
3. Update the last scan message so if code scan is enabled and there is no last scan yet, we don't ask user to enable Change Analysis
=> Change Analysis onboarding UI tweaks

ApplensBackend/LocalDevelopmentTemplate/Detector/Diag.ps1
the .\Diag.ps -run cmd replies with an invalid redirect to location: //.  previously. Use the same url for http-server.
=> Fix local development detector view in browser

AngularApp/projects/app-service-diagnostics/src/app/home/components/diagnostics-settings/diagnostics-settings.component.ts
The original call using patchResource() will not return full response of the error, which makes the error message always "Try again later" even if it's something like unauthorized.
=> A minor fix of error handling when add hidden tag to web app

AngularApp/projects/applens/src/styles.scss
Currently, when there are many versions of gist, the confirm button goes all the way to the bottom and its not seen. Made Gist modal scrollable if the content is overflowing.
=> Make gist modal scrollable

AngularApp/projects/applens/src/app/shared/models/observer.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/site.service.ts, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/ObserverClientService/IObserverClientService.cs, ApplensBackend/Services/ObserverClientService/SupportObserverClientService.cs
--Point applens backend from support bay api to wawsobserver
--Deprecate /hostnames api in applens backend as wawsobserver does not support it and the data does not seem to be being used anywhere in frontend.
=> Support regional geomaster changes in applens

Backend/appsettings.json
Chat Controller calls are failing because the code is looking for PublicHolidayRegions where as configuration has PublicHoliday. Fixing the typo
=> Fixing Chat typo that is prevent chat to come up

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-main/daas-main.component.ts, AngularApp/projects/app-service-diagnostics/src/app/supportbot/message-flow/main-menu/main-menu.component.ts
Even though I am sending this PR, this is basically **dead code.**None of the below components are currently used. They were used at some point but not any more. 
So we should be totally ok with making the backend change for properties call.
=> Rely only on stack from diagnosticProperties call

ApplensBackend/Services/DiagnosticRoleClientService/DiagnosticRoleClient.cs
While running applens locally, x-ms-internal-client header values gets received as "true, True" in Runtime host side because of the order in which headers were added. Fixing that in this PR
=> Fix issue in local dev where header value gets passed twice

AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
Kusto has a lag of 15 minutes so defaulting the end time to now - 15 minutes. This should hopefully reduce the Kusto load and avoid it from forcefully reading from disk.
=> Set default end time to now - 15 minutes

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.html, AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/markdown-view/markdown-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/markdown-view/markdown-view.component.spec.ts, AngularApp/projects/diagnostic-data/src/lib/components/markdown-view/markdown-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts, AngularApp/projects/diagnostic-data/src/lib/services/link-interceptor.service.spec.ts, AngularApp/projects/diagnostic-data/src/lib/services/link-interceptor.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
With this PR, a detector can now have a hyperlink to another Detector, tool or analysis.
On the detector side, you have to do something like this
```
res.AddMarkdownView($@"Open <a href='{GetLinkToDetector(cxt, "detectors/http4xx")}'>HTTP 4XX Detector</a>","Markdown Title");
static string GetLinkToDetector(OperationContext<App> cxt, string routePath)
{
if (cxt.IsInternalCall)
return $"{cxt.Resource.ResourceUri}/{routePath}";
else
return $"./resource{cxt.Resource.ResourceUri}/{routePath}".ToLower();
}
```
The `GetLinkToDetector `method can be worded more appropriately and put in a Gist so all detector authors can leverage this.
=> Allow markdown to have links to Detectors, Analysis and Tools

ApplensBackend/Services/DiagnosticClientService/DiagnosticClient.cs
- If both IsLocalDevelopment and RuntimehostEnabled is false, requests will go the DiagRole. This is the current set up in Applens-prod and applens-staging.
- In Applens-dev slot, RuntimehostEnabled is true and LocalDevelopment is false, so requests will directly go to Runtimehost App Service.
- While running the project locally, RuntimehostEnabled can be set to false and LocalDevelopment is true, so requests will go to runtime host running locally.
- Once we have migrated applens to runtimehost completely, we can get rid of the flags and there will be only one flow.
=> Changed DiagnosticClient request flow logic

AngularApp/projects/app-service-diagnostics/src/assets/custom-timeline.css, AngularApp/projects/applens/src/assets/custom-timeline.css, AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts
- Highlight the most recent change group in the default view to indicate that it’s been selected. 
- Change groups should be monotone in color unless selected. 
- Change the cursor to a pointer style when a user hovers over a change group. 
- Make the top row from the change chart expanded by default
=> Addressed Change Analysis UI feedback

AngularApp/projects/diagnostic-data/src/lib/utilities/changeanalysis-utilities.ts
The 'content' field can be a plaintext string or a json object. Need to handle it differently, otherwise the monaco editor will show nothing
=> Fix the app change view where the content is a json object

AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.html
The existing implementation will blindly load the monaco editors for all changes, which will make the UI unresponsive when there is a huge list of changes (100 changes for example).
The fix is to load the editor only when it's expanded.
=> Performance improvement of the change list view

AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/time-series-instance-graph/time-series-instance-graph.component.ts
I was getting a NaN for 0, discovered it is any integer. 
parseFloat returns 'NaN' for an integer, Number() constructor handles either float or int.
=> Fix graph when number is int

AngularApp/projects/diagnostic-data/src/lib/components/app-dependencies/app-dependencies.component.ts
- This bug was caused in case of web app having various storage services under same storage account as dependencies. Since the network node was using resource uri as the id, it was throwing error when there are multiple nodes with same id. So changed it to use host name instead.
=> Fixed bug where no dependencies were showing up in Navigator

AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.ts
To able to wrap text in a DataTable, we have to set RowHeight to Auto but with the scrollbarV is breaking. The quick way to fix this is by setting a scrollbar on the component itself and set rowHeight to Auto in detector code.
=> Fix Wrap Text issue in Ngx-DataTable for FrebViewer tool

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-tile/category-tile.component.ts
Added a check to see if the detector is analysis or a detector and route accordingly.
=> Fix the routing to analysis in case there is a single public detector in a category

AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts
- Display last 24h changes by default
- Noisy changes filtered out by default
- Last Scan timestamp, timestamp on each change, timeline displayed in UTC
- Removed noise icon from table legend
=> UI improvements for Change Analysis batch API

AngularApp/projects/diagnostic-data/src/lib/components/changes-view/changes-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/changesets-view/changesets-view.component.ts
- Updated Change Analysis insight title to reflect number of changes instead of change groups.
Current UI:
New UI:
- Removed caching call for getDetector API call by passing `shouldRefresh` parameter as `true`
=> Updated Change Analysis insight title, removed caching for getDetector API call

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
1. In highcharts, texts and labels are given in HTML but rendered as SVG. When useHTML both set to be true, tooltip will be laid below XAxis labels. Remove Xaxis "useHTML=true" and set "tooltip.outside" to prevent this behavior in Highcharts 6.1.1. 
2. Change select "All" and "None" behavior.
series.hide() and series.show() will try to reflow the chart. If there are too many series, UI will freeze.
However setVisible is only set the visible status, which works instantaneously.
3. Change the default height of linechart from "200px" to "300px".
=> Change tooltip opacity and reflow behavior

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Detector Id gets override for monitoring developing page after we run monitoring dashboard code for the first time, which incorrectly set the detector id gets monitored to be the current system invoker id ("__monitoring" or "__analytics").
This was causing the second run of monitoring code failed previously.
=> Fix monitoring developing page

AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts
When there is only one data point, we should not determine the timegrain only based on the starttime and endtime. Otherwise the data point won't show up in the bar chart.
The initial value should be 60 mins if the time difference between start time and end time is less than 7 days. 
For instance this example:
https://applens.azurewebsites.net/subscriptions/878ee15c-1efd-43de-b6ad-3f7e15338b1d/resourceGroups/rg-big-paceaissima-qa/providers/Microsoft.Web/sites/asfa-big-bib-qa-mapping/detectors/FunctionAppDeployed?startTime=2019-12-03T21:21&endTime=2019-12-05T21:05
This is after fix:
This kind of bug is not my favorite lol
=> Render chart properly when there is only one data point

AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts
In the timeseries logic, first we determine which column of the input table we want to render as y axis values. (This is determined by iterating all the columns and return the column index which has datatype of double or int.) Once we get the counter column index, we push the datapoint and reformat it as “TablePoint” format for timeseries rendering.
data.table.rows.forEach(row => {
numberValueColumns.forEach(column => {
const columnIndex: number = data.table.columns.indexOf(column);
const timestamp = moment.utc(row[timestampColumn]);
lastTimeStamp = timestamp;
if (row[columnIndex]) {
const point: TablePoint = <TablePoint>{
timestamp: timestamp,
value: parseFloat(row[columnIndex]),
column: column.columnName,
counterName: counterNameColumnIndex >= 0 ? row[counterNameColumnIndex] : null
}; …
=> Fix the 0 values not rendered properly in timeseries

AngularApp/projects/applens/src/app/modules/dashboard/gist-changelist/gist-changelist.component.scss
Old experience in applens gist version history:
New experience:
=> Making gist version history scrollable

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts
Adding this header to ARM calls which GeoMaster will consume for the following APIs:
- ListDetectors
- GetDetector
- GetDiagnosticsProperties
=> Adding header x-ms-diagversion for calls to ARM

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts
- Adding support to monitor Scm processes and
- increasing the default time to 2 weeks instead of one.
=> Monitor SCM process in proactive cpu monitoring

AngularApp/projects/applens/src/app/shared/components/unauthorized/unauthorized.component.html, AngularApp/projects/applens/src/app/shared/components/unauthorized/unauthorized.component.scss, AngularApp/projects/applens/src/app/shared/components/unauthorized/unauthorized.component.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, ApplensBackend/.gitignore, ApplensBackend/AppLensV3.csproj, ApplensBackend/Configuration/Startup.cs, ApplensBackend/Configuration/StartupNationalCloud.cs, ApplensBackend/Controllers/TemporaryAccessController.cs, ApplensBackend/Models/TemporaryAccessUser.cs, ApplensBackend/Services/Authorization/AuthorizationHandler.cs, ApplensBackend/Services/CosmosDBHandler/CosmosDBHandler.cs, ApplensBackend/Services/CosmosDBHandler/ICosmosDBHandler.cs, ApplensBackend/appsettings.json
Temporary Access Provision for AppLens. It defaults to 7 days and can be availed one time only.
Screenshots:
When user does not have access to applens
When temporary access is approved
And user is redirected to home page
When user has already used one-time temporary access
=> Temporary access provision for AppLens

AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts
The actual issue why it was failing was this exception
`Error while sending request: Failed to execute setRequestHeader on XMLHttpRequest: Value is not a valid ByteString.`
=> Fix AppLens to load for sites with non-ascii chars

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts
Changes in cognitive search:
1. Use only particular types of stacks.
2. Show cognitive search at most 10 seconds into the rendering of the search component - and not wait for all detectors to execute.
Changes in detector search:
1. Do not run detectors that are already rendered in parent analysis.
No changes in the UI so no screenshots.
=> SearchComponent: Cognitive search optimization and Detector search updates

AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.html, AngularApp/projects/applens/src/app/modules/dashboard/configuration/configuration.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html, AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Applens editor hangs when the code is emptied. This happens for detectors/gists/configuration files.
Repro steps:
Open applens and open any detector for editing or go to create new detector
Then empty the editor, the editor screen hangs indefinitely
The fix:
We use a boolean for rendering the monaco code editor instead of binding it directly to "code" variable. We set the boolean once the pre-development requests are complete.
After the fix, upon emptying the editor one can have the view
=> Fix issue: Applens editor hangs on empty code

ApplensBackend/Services/GithubClientService/GithubClientService.cs
When I click on Manage Package for WebAppDownWindows gist, the list is just not loading because there are more than 150 commits to this file. 
After this change, we will restrict the UI to show last 60 commits only thereby allowing the call to succeed.
This is a temporary fix and the long time fix is to allow pagination in the gist version list. I am submitting this PR to unblock myself so I can easily use the latest version of the Gist in few detectors.
=> Restrict only last 60 commits to be shown in Gist Version Management

AngularApp/projects/app-service-diagnostics/src/app/shared/models/appinsights.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/appinsights/appinsights.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.ts
When this portal service fails to find the tag for App Insights resource, we can get appsettings for the app and reverse lookup all the AI resources in the subscription to find out the AI resource linked for the app.
=> Improve AI detection logic when Portal RPC service returns nothing

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
We observed a bug in search component rendering where search component would show up only the first time an analysis is opened in a session. This was happening because we are filtering out search component from detector result dataset to skip it from rendering in the "detector part" of analysis view and show it at the very end. As it seems the detector response is cached and is copied by reference, so when we filter out search component we actually modify the cached detector response which results in search component not being there when the cached response is referenced the second time.
To overcome this, we **added a pipe filter while rendering dynamic components and avoid the search component** only in analysis view.
=> Render search component in detector/analysis view of analysis type detector

AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts
Check 1: If the search result is either the parent or any child of the parent - skip
Check 2: If the search result is a detector - show it
Check 3: If the search result is an analysis -> get it's children -> show only those who fail the check 1.
=> Fix bug in parent rendering in search results

AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.html, AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.ts
- Row limit was previously worked around with `TableOptions = new { scrollbarV = true}` in detector rendering properties
- Setting a height limit on the table and removing row limit automatically adds the vertical scroll bar, achieving the same effect
=> Remove Row Limit For DataTable

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.scss, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts, AngularApp/projects/app-service-diagnostics/src/app/betaSubscriptions.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts
Auto-healing server side code is encountering a buffer overrun if the storage account number is longer than 18 characters. The server side fix is applied but will go with ANT 88 which might take more than a month. Adding a check in UI code for Storage name length so that customers dont end up configuring a storage account which may then cause Autohealing to fail silently.
For pre-configured Storage accounts that are already exceeding in length, Auto-Heal UI will show this warning.
=> Add a check for storage length till ANT88

AngularApp/projects/diagnostic-data/src/lib/components/insights-v4/insights-v4.component.html, AngularApp/projects/diagnostic-data/src/lib/components/insights-v4/insights-v4.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.html, AngularApp/projects/diagnostic-data/src/lib/components/insights/insights.component.ts
There is currently an issue in which if an Insight has more than one item in the collection, then the hyperlinks only work in the first item of the insight and not the other one.
To explain more, for an insight like the below one, hyperlinks are opening in a new tab only for **Description** but not for **Learn More**.
This PR fixes that issues and ensure that links are opened in a new tab for all insight list items.
The change from ngIf to hidden is required because otherwise the ngAfterViewInit is not having the reference to all the markdown components just because they are not even loaded in DOM.
=> Fixing bug when links not opened in new tab

AngularApp/projects/app-service-diagnostics/src/app/app.module.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/web-sites.module.ts
Websites service is already defined as an injectable to be provided in "Root". To make sure the service is a singleton, it should not be provide in a lazy loaded module in websitesmodule again.
=> Fix search suffix for windows web app

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
This seems like the only solution I can find so far to make this refreshing completely working. 
https://ms.portal.azure.com/?websitesextension_ext=asd.env%3Dstaging#home
In this solution, I only unsubscribe the observer in ngDestroy function. Meaning as long as the component instance is still in the routing cache and getting reused, it will be still listening to the refresh signal from detector control service. I am thinking if this is the right way to do, but since we are already maintain those cached component instances, then maybe we should also maintain their subscribing states to make it a complete story.
The side effect is that it's making all the get detector response calls for the cached components whenever we refresh a detector. Need to find a way to minimize the calls.
=> Hard refresh for refreshing request

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-time-picker/detector-time-picker.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-control/detector-control.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
For the refresh command from the old detector control (Either click on refresh icon or set the time duration), we bypass the instanceId comparison logic.
=> Fix timer picker in Applens and D&S

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-requests-rule/autohealing-requests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
1. Changing wording for some of the questions that we present in AutoHeal
2. Showing a warning if timeInterval is less than request interval
3. Removing the resource specific text from Analysis List page
=> AutoHeal Text Changes and removing resource specific text

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-sessions/cpu-monitoring-sessions.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-sessions/cpu-monitoring-sessions.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts
With this change, we will now force customers to configure a Storage Account even when they try to use memory dump collection for Proactive CPU Monitoring.
=> Forcing Storage Account selection on Proactive CPU Monitoring

AngularApp/projects/diagnostic-data/src/lib/components/data-table/data-table.component.ts
The Column Search functionality in Event Viewer got regressed I believe once we upgraded to Angular8. Bringing that back.
=> Bringing back the column search in datatable

ApplensBackend/LocalDevelopmentTemplate/Detector/Diag.ps1, ApplensBackend/Services/EmailNotificationService/EmailNotificationService.cs
Add fix a small bug in local dev tool:
-o [path] Open browser window after starting the server. Optionally provide a URL path to open. e.g.: -o /other/dir/
https://www.npmjs.com/package/http-server 
http-server "$PSScriptRoot\..\Framework\UI\Detector-UI-Rendering\dist" -o /index.html -a localhost -p 8000 -c-1
=> Change sender address to avoid publish email go to spam

AngularApp/projects/app-service-diagnostics/src/app/availability/problem-solution/problem-solution.component.ts, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.ts, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.ts, AngularApp/projects/app-service-diagnostics/src/app/home/components/category-tile/category-tile.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts
Hey @ShekharGupta1988  I realized we have control over for the whole string here:
The reason I didn't change this to **Diagnose and solve problems | Availability and Performance**  is that before we send the whole string from our Iframe to ibiza, ibiza will show the resource name by default first, and then change it to our string. So it will be changed from "BuggyBakery" to "Diagnose and solve problems | Availability and Performance", which is a bit jarring. So I keep the string to be as it is to make the switch look more smooth.
=> Breadcrumb fix and few logging fix

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.scss
Fixing accessibility bugs for luminosity ratio
1. Overriding the healthy-icon-color class for this component only (because the icon is used in different places and the background colors there are different). Updated luminosity ratio is 3.88 : 1 (required is minimum 3 : 1)
2. Updating the panel heading color from gray to black (since the background is light gray too). Updated luminosity ratio is 19.26 : 1 (required is minimum 4.5 : 1)
https://msazure.visualstudio.com/Antares/_workitems/edit/7096293
https://msazure.visualstudio.com/Antares/_workitems/edit/7096303
Before look:
After look:
=> Luminosity ratio bugs

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/version-test.service.ts, AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.scss, AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/portal-appinsights-telemetry.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/version.service.ts
1. Add logic to pass percentage of external traffic for new experience
2. Enable page view time for application insights
3. Bug fix for old experience when there is no "healthcheck"  element to focus
4. Small UI change:
=> Add logic to enable external users with new expericence

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.html, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/diagostic-sessions-panel/diagostic-sessions-panel.component.html, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/diagostic-sessions-panel/diagostic-sessions-panel.component.spec.ts, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/diagostic-sessions-panel/diagostic-sessions-panel.component.ts, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/fabric.module.ts, AngularApp/projects/app-service-diagnostics/src/app/globals.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.service.ts
In new Diagnose & Solve portal, whenever customer clicks “view all sessions” link from “Collect Memory Dump” page or “Collect Profiler Trace” page, a context menu with the sessions table will show up in a context menu:
=> Create diagnostic sessions panel in new D&S

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
By checking the logs, I found out this resource name is logged as undefined because this variable is initialized in NgOnInit() however logging was added in constructor.
=> fix resource name logging undefined

ApplensBackend/Helpers/Constants.cs, ApplensBackend/Services/SelfHelpContentService/SelfHelpContentService.cs
Github API authentication from query parameters will be deprecated soon, fix the existing API call by changing it to header authorization:
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
=> Remove token query parameter for Github API call

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts
With this PR:-
1. Temporarily disabling the forcing of storage account for Memory dumps for National Clouds
2. Adding the relevant information to pass while setting the BlobSasUri when DAAS update is everywhere.
=> Fixing DAAS Storage Account selection for National Clouds

AngularApp/package.json, AngularApp/projects/app-service-diagnostics/src/app/startup/services/auth.service.ts, AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts
Service Health Issue [1333: [Portal] 401 (expired token) exceptions in Portal while talking to ARM](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1333)
We see a lot of 401 (expired token) issues in portal when talking to ARM. It's because of the ARM token being expired and not getting refreshed from ibiza.
This is hampering our customer experience by displaying them nothing when requests are made. ~1,667 distinct users have been impacted due to this issue in last 1 month.
[Failure count trend weekly](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fc1972e9d-b3c7-4de4-acb3-681773b28ced%2FresourceGroups%2FDiagnoseAndSolve%2Fproviders%2Fmicrosof …
=> Token refresh mechanism for portal blade

AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
Match the popout view with regular detectors view in AppLens. Show detector author and header info along with time picker.
=> Show timer picker in detector view after poping it out from downtime triggered analysis

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
- Fix for error message in time picker in external UI should indicate the input time format should be "MM/DD/YY hh:mm"
- Fix for logging StartTime and EndTime as ISO string so that Kusto query can use it directly.
=> Fix for format issue in error message and timestamp format for logging

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
Trigger downtime even when first or last point on the graph is selected. The UI behavior was breaking earlier, the dropdown value would change however the observations would not get triggered. This will fix it.
=> Trigger downtime when first or last point of the graph is selected

AngularApp/projects/diagnostic-data/src/lib/components/dropdown-v4/dropdown-v4.component.html
Had fixed this issue for the dropdown component in an earlier PR.
But seems we are using a new component in the new UI code. So here is the same fix for that component too.
=> Accessibility bug v4: Make aria-expanded to false by default

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/insights-v4/insights-v4.component.html
This PR is to fix these two accessibility bugs:
Bug 7094718: [Supporting Platform - App Service Diagnostics - High CPU Analysis] Tooltip does not define for Hamburger menu control.
Bug 7095620: [Keyboard navigation - App Service Diagnostics - Web job details] Focus moves on non-interactive element via tab key for web job texts.
=> Add highchart menu button tool and skip focus on insight without content

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/cxp-chat-caller.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts
Update DiagnoseAndSolve to take users language settings from Ibiza and pass it to the CXP chat API. Also pass the resourceId along with ticket creation params to auto inject HealthSupportPlan in case the resource is found unhealthy. This was discussed with Nitin over IM.
=> Pass user Ibiza language setting to CXP Chat API

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/connection-diagnoser-tool/connection-diagnoser-tool.component.html
A bug was reactivated. I had resolved it for the insight title but missed the internal text inside insight.
Old ratio: 4.17:1
Minimum Required: 4.5:1
New ratio: 5.08:1
[Bug 7096293](https://msazure.visualstudio.com/Antares/_workitems/edit/7096293): [Visual Requirements - App Service Diagnostics - Diagnostic Tools - Check connection strings] Luminosity ratio of the highlighted text is less than the minimum required value of 4.5:1.
=> Luminosity ratio for text inside insight

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-memory-rule/autohealing-memory-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-requests-rule/autohealing-requests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-trace-tool/network-trace-tool.component.html
Fix for the following accessiblity bugs as I noticed that one got reopened.
- [Bug 7095672](https://msazure.visualstudio.com/Antares/_workitems/edit/7095672): [Screen Reader - App Service Diagnostics - Collect .Net Profile Trace] Screen reader is reading some unnecessary table information when focus moves to controls under “Collect a Profiler Trace” heading on “Collect .Net Profile Trace” page.
- [Bug 7096151](https://msazure.visualstudio.com/Antares/_workitems/edit/7096151): [Screen readers - App Service Diagnostics - Diagnostic Tools - Custom Auto-Heal Rules] The data in the table cells are not associated with the column headers.
The only way I was able to get screen reader to associate table cell with header was by adding tabindex=0. This seems easiest approach vs. moving to any new …
=> Fix for bug 7095672 and 7096151

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.scss
[7095541 ](https://msazure.visualstudio.com/Antares/_workitems/edit/7095541)| [Visual Requirements - App   Service Diagnostics - Proactive CPU Monitoring] Luminosity ratio is less than   3:1 for slider control on “Proactive CPU Monitoring” page.
-- | --
This is how it looks now.
=> Fixing luminosity ratio for the Slider bar

AngularApp/projects/app-service-diagnostics/src/app/shared/components/collapsible-list/collapsible-list.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/collapsible-list/collapsible-list.component.scss, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
- Fixing the below bug
[7095516 ](https://msazure.visualstudio.com/Antares/_workitems/edit/7095516)| [Screen Reader - App Service   Diagnostics - Proactive CPU Monitoring] Name/Role property is not defined for   “Expand/Collapse” button present on “Proactive CPU Monitoring” page.
-- | --
- Also fixing the below error in Diagnostic Tools
`Cannot read property 'map' of undefined at t._next`
=> Screen Reader to announce Collapse \ Expand on collapsible list

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
With this PR:-
- Removing check for StorageAccount name length because the backend fix is in PROD
- Improving check for DAAS validator to check for LocalCache, WEBSITE_WEBJOBS_STOPPED, and WEBSITE_DAAS_DISABLED
- Fixing the Issue of Duplicate Insights in Analysis Component
The fix for duplicate insights is more of a workaround, the real issue is that the call to `this._activatedRoute.paramMap.subscribe` inside the `refresh()` method in `DetectorListAnalysisComponent` is getting called twice when navigating from one Analysis to other. Due to this every item in the array is getting added twice. I tried debugging for sometime but couldn't figure out what is causing. @nmallick1 - if you get check a chance, please debug this a bit.
=> Improve DAAS Validation Checks and fixing duplicate insights in Analysis

AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-analysis/tab-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
Make downtimes shareable when opened in drill down mode. 
Maintain the current drill down view even when downtime selection is changed. The detector view updates to reflect the latest downtime selection instead of switching to observation list.
=> Fix deeplinking from analysis to detector in drill down view

AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
Allow 5 min variance of start and end time in downtimes since backend normalizes cxt.StartTime and cxt.EndTime into 5 min timegrain.
=> Fix for default downtime trigger.

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
Looks like a new exception introduced recently:
User Story 1367: [Client side exceptions]: Cannot read property 'map' of undefined at e._next
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1367/
Application insights End to End transaction:
https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%22c1972e9d-b3c7-4de4-acb3-681773b28ced%22%2C%22ResourceGroup%22%3A%22DiagnoseAndSolve%22%2C%22Name%22%3A%22DiagnoseAndSolvePortal%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2Fc1972e9d-b3c7-4de4-acb3-681773b28ced%2FresourceGroups%2FDiagnoseAndSolve%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FDiagnoseAndSolvePortal%22%2C%22ResourceType%22%3A%22microsoft.insi …
=> Fix client side exception in daas session component

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
Behavior is in alignment with ibiza sidebar:
Zoom 80%:
Zoom 300%:
Window resize:
=> Fix side nav width to be adjusted with zoom and resize

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/cpu-monitoring/cpu-monitoring-configuration/cpu-monitoring-configuration.component.scss
[7095528 ](https://msazure.visualstudio.com/Antares/_workitems/edit/7095528)| [Supporting   the Platform - App Service Diagnostics - Proactive CPU Monitoring] Slider   control is not visible properly in high contrast mode black/white on   “Proactive CPU Monitoring” page.
-- | --
=> Fixing Slider to be visible in High Contrast Mode

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts
This is to fix  [Cannot read property 'snapshot' of null at e.navigateTo](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1398) exception
=> Remove check isHomePage with ActivatedRoute

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-solution.service.ts
This PR allows Solutions on D&S to perform the reboot worker API, which is a POST ARM call.
=> Add reboot to allowedRoutes for solution ARM API

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts
This is regarding to the client side exception fix for this service health item:
TypeError: Cannot read property 'params' of undefined 
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/edit/1399/?triage=true
=> Accessing route snapshot in routing events

AngularApp/package.json
To fix the heap limit allocation failure we see sometimes when we run "npm run applens" or "npm run ssl-local"
=> Fix local build heap limit allocation failure

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/dynamic-insight/dynamic-insight.component.html, AngularApp/projects/diagnostic-data/src/lib/diagnostic-data.module.ts
- Ues Fabric DetailList component to replace ngx-datatable. 
- Use Fabric TextField component for searching
For now new datatable supports almost all functionalities, like : searching(but not able to search across multiple columns) , sorting , resizing columns and showing the description below the table
=> Replace ngx-datatable with Fabric DetailList

AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts
Currently the new Frame control from case submission team won't be able to get the message if there is not message object payload. Adding the payload with event type so they can register listener on these events.
=> Adding event message body to integrate with case submission flow

AngularApp/projects/app-service-diagnostics/src/polyfills.ts, AngularApp/projects/applens/src/polyfills.ts
There is a known issue on IE to find object.entries:
https://stackoverflow.com/questions/42446062/object-doesnt-support-property-or-method-entries
Localhost IFrame doesn't work for IE, I have deployed the fix in staging:
https://ms.portal.azure.com/?websitesextension_ext=asd.env%3Dstaging#@microsoft.onmicrosoft.com/resource/subscriptions/c1972e9d-b3c7-4de4-acb3-681773b28ced/resourceGroups/cindybuggyapp/providers/Microsoft.Web/sites/cindybuggyapp20190611092617/troubleshoot
=> Fix Diagnose and Solve loading issue on IE

AngularApp/projects/app-service-diagnostics/src/app/shared/components/collapsible-list/collapsible-list.component.scss
Currently in IE 11, this is how the CPU monitoring page is rendered. 
Fixing it to look like Edge
=> Minor fix for collapsible for CPU Monitoring for IE11

AngularApp/package.json, AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
This is a potential fix for this service health item
User Story 1513: [Diagnose and Solve Portal] Cannot read property 'call' of undefined at SVGGElement.<anonymous>
The exceptions are from this customEvents javascript in highchart library:
customEvents.js: line 370
**events[event].call(elemObj, e);**
=> Fix highchart type error: Cannot read property 'call' of undefined at SVGGElement.

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/insights-v4/insights-v4.component.html
According to accessibility team, if the insight is not an interactive element, it should not be focused.
=> Accessibility bug fix for non-expandable insights

AngularApp/projects/app-service-diagnostics/src/app/shared/services/appinsights/appinsights.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.html, AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/appinsights.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
Currently we delete the existing APPSERVICEDIAGNOSTICS_READONLYKEY API key when someone tries to click Connect on our AI integration page. This causes problems when multiple apps are connected to same AI resource.
[1532 ](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1532/)| ASD Integration with AppInsights breaks if same AI resource used on multiple web apps | app-service-diagnostics-portal\Backlog | New | Service Health | 1 | 9/24/2020, 7:16:07 PM
With this PR
1. We will not delete the existing APPSERVICEDIAGNOSTICS_READONLYKEY API keys
2. We will create a key with name like this …
=> Allow users to 'Connect' when multiple apps connected to same AI resource

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/documents-search.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-documents-search.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/documents-search/documents-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/documents-search-config.ts, AngularApp/projects/diagnostic-data/src/lib/services/generic-documents-search.service.ts, AngularApp/projects/diagnostic-data/src/public_api.ts
- Added a new Config file which has a list of Products for which Deep Search is enabled
- Added methods in component to get PesId 
- Deep Search's IsEnabled method considers PesId and IsPublic
=> Updated Deep Search to be enabled only for specific Products

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
The View All Sessions link is not coming in the tools today for ILB ASE 
Earlier customers had a way to get to Diagnostic Sessions from other places so maybe that's why no one reported this issue earlier.
=> Enable DaaS sessions link on ILB ASE

ApplensBackend/AppLensV3.csproj
- Update AzureAd from 3.17 to 5.2 to factor for new clouds otherwise we will get WinHttpExceptions with server name not resolved errors.
=> Update AzureActiveDirectory to latest

AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts
This is regarding to the issue that we are seeing a blank space for AKS detector, because of no detector view was rendered within an analysis:
=> Fix the formatting of AKS detector view

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/pipes/site-filter.pipe.ts
Right now whenever there is a new sku onboarded, we need to add a new value to serverfarm.ts for the new sku, and change the values for "Paid", "NotDynamic", "All"
export enum Sku {
Free = 1 << 0,
Shared = 1 << 1,
Dynamic = 1 << 2,
Basic = 1 << 3,
Standard = 1 << 4,
Premium = 1 << 5,
PremiumV2 = 1 << 6,
Isolated = 1 << 7,
PremiumContainer = 1 << 8,
Paid = 504,         // 111111000
NotDynamic = 507,   // 111111011
All = 511           // 111111111
}
Adding the logic in filter to allow "Diagnostic Tools " showing up for all the non-dynamic sku without add new sku enum
=> Fix diagnostic tools not showing up for premium v3 and other new onboarded skus

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
This is for fixing duplicate tools in category-nav component. 
This is caused by not filtering stack for tools and I added **stackMatchedForTools()** method back to resolve issue.
Before fixing,
After fixing,
=> Remove duplicate tools in category-nav

AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts
It seems for logic apps and apim, the geomaster is not passing over the query term to Runtime host api due to which search is not fired.
Will disable the detector search for logic apps and apim for now and work on enabling the geomaster flow.
=> Disabling detector search for logic apps and apim

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
Enable all ST's for web app windows and linux for CXP chat. CXT team can independently enable/disable chats within their system.
=> Enable all ST's for web app windows and linux for CXP chat.

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/server-farm-data.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/site.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/comm-alert/comm-alert.component.ts
- Fix **Cannot read property 'map' of undefined at <no_method>**
- Fix **Cannot read property 'toLowerCase' of undefined at t._next** and **Cannot read property 'indexOf' of undefined**
Basically these two exceptions are caused by some resources(Like App Service Certificate) it doesn't have kind and serverFarmId in the site property, I modified code to add check and replace serverFarmId with siteResourceId when make ARM call
=> Fix emerging exceptions

AngularApp/projects/diagnostic-data/src/lib/models/search.ts
APIM is currently passing the text parameter in /detectors route in their RP, so the detector search works.
=> Enabled detector search for APIM in public portal

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts
Please refer [Bug_1593](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1593) about my investigation so far.
Basically, all exceptions are from dependency calls like this,
**"https://management.azure.com/?clientOptimizations=undefined&l=nl.nl-nl&trustedAuthority=https:%2F%2Fportal.azure.com&shellVersion=undefined#02261aef02bc430fae3e00b4d31b28f1&api-version=2015-08-01"** 
and I have no idea about where we call this endpoint, so I throw new error as long as there is an ARM call with similar format.
I checked all calls with this format will be failed so we should no need to worry about performance impact.
[Go to Log Analytics and run query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Lo …
=> Add new error for investigation "MissingApiVersionParameter" exception

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts
Enable CXP chat for function apps. CXP team will be able to manage which ST's to open up the chat for.
=> Enable CXP chat for function apps

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-search-results/fabric-search-results.component.ts, AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts
From stack trace issue is caused by **registerResource** passing wrong resourceUri, I added logic to extract resourceUri if in this scenario
I checked in last 14 days all dependency call were failing so I think we should either block this call or modify the resourceUri to get the right ARM call
dependencies
| where timestamp >= ago(14d)
| where name contains "management.azure.com/?clientOptimizations=undefined&l=en.en-us&trustedAuthority=https:%2F%2Fportal.azure.com&shellVersion=undefined#"
| summarize count() by resultCode
resultCode | count_
-- | --
400 | 243
0 | 19
Here is the stack trace,
Error: Uncaught (in promise): Error: ARM Call Cause MissingApiVersionParameter Exception
Error: ARM Call Cause MissingApiVersionParameter Exception
at e.createUrl …
=> Fix for MissingApiVersionParameter

AngularApp/projects/app-service-diagnostics/src/app/shared/models/arm/armResourceConfig.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-arm-config.service.ts, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.apimanagement/service/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.appplatform/spring/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.certificateregistration/certificateorders/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.certificateregistration/certificateorders/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerinstance/containergroups/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerinstance/containergroups/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerregistry/registries/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerregistry/registries/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.containerservice/managedclusters/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/integrationServiceEnvironments/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/integrationServiceEnvironments/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.logic/workflows/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.servicefabric/clusters/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.servicefabric/clusters/override.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/config.json, AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.signalrservice/signalr/override.json
Extend partner config to indicate whether the response returned by arm api is base64 encoded.
Also add support for keystoneDetectorId.
Update partner configs to reflect updated schema.
=> Extend partner config to indicate whether the response returned by arm api is base64 encoded.

AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts
In my last fix, I was trying to extract the right resource uri from Angular route and send ARM request to fix this exception. But that fix looks like not working as the exception still throwing by **createurl** method in arm service. 
In this PR, I am going to block these requests which will cause MissingApiParam exception since from my previous investigation, exceptions are caused by dependency calls make to "https://management.azure.com/?clientOptimizations..." return with 400.
[App Insight](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fc1972e9d-b3c7-4de4-acb3-681773b28ced%2FresourceGroups%2FDiagnoseAndSolve%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FDiagnoseAndSolvePortal/source/LogsBl …
=> Completely Block Calls that causing MissingApiParam exception

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-notification/risk-alerts-notification.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-panel/risk-alerts-panel.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/risk-alerts-panel/risk-alerts-panel.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
This PR is for changing action for risk tile in homepage,
When clicking availability tile in risk alert section, it will open risk alert panel in right side so user can get thorough insights about these 4 basic checks. When scroll to bottom, there is a "Run All Check" link, it will navigate to risk alert detector to get all checks.
=> Open panel for homepage risk tile

AngularApp/projects/app-service-diagnostics/src/app/home/resolvers/resource.resolver.ts
I checked Javirs dashboard and issue still happening after deployed last fix. Figure out the check logic for resource URI in resolver is not correct and cause error still throwing by arm service.
Update the logic to check only last part without arm endpoint, new logic should be able to block problematic ARM calls
=> Update check to block ARM call

AngularApp/projects/app-service-diagnostics/src/armResourceConfig/microsoft.servicefabric/clusters/config.json, ApplensBackend/nuget.config
Fix the category id for service fabric category so that the detector load as soon as a tile is clicked on.
=> Fix the category id for service fabric

AngularApp/projects/applens/src/app/shared/services/github-api.service.ts, ApplensBackend/nuget.config
When a new detector is created, it doesn't have an id, which causes the UI to hit a wrong route to the backend.
=> Prevent forming bad route for metadata file for new detector creation

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-chat/category-chat.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts
Bug 1654: [Diagnose and Solve Client] Cannot convert undefined or null to object in logging properties
Bug 1653: [Diagnose and Solve Client] TypeError: e.ToString is not a function in error logging
Bug 1654: [Diagnose and Solve Client] Cannot convert undefined or null to object in logging properties
=> Fixing top 3 service health items from Diagnose and Solve client

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-content.service.ts, AngularApp/projects/diagnostic-data/src/lib/models/search.ts, AngularApp/projects/diagnostic-data/src/public_api.ts
**Since genie does not use Project Shield for documentation search**, it is not using the functionality of excluded sites due to which AWS results pop up.
With this change we are making the list of excluded sites global for documentation search in the entire diagnostics project.
=> Fix:Genie is showing results from unintended sites

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/auto-healing.module.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-config-summary/autohealing-config-summary.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-rule/autohealing-rule.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.scss, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/timespan/timespan.component.scss, AngularApp/projects/app-service-diagnostics/src/app/shared/models/autohealing.ts
With this PR, we are updating the AutoHeal UI to have this functionality
- Support for adding multiple rules for Slow Requests (Request Duration) based on request path
- Support for specifying a path for the Status Codes rules
- Support for specifying a range of HTTP status codes
Choose a single HTTP Status Code rule or a range of Status codes
=> Autohealing updates for path and status code range

AngularApp/projects/diagnostic-data/src/lib/models/search.ts
Logic apps RP is now passing the "text" parameter to diagnostics backend. Hence enabling detector search feature in project shield.
=> Enable detector search for logic apps

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/urielements.service.ts
With this PR
- Forcing SAS Uri to be configured as an App Setting for Crash Monitoring feature. This is required so that sites using Local Cache are configuring the SAS URI correctly
- Calling a DAAS API to validate if the configured SAS URI is accessible from DAAS. If not, we are giving a message right before you submit a session
=> Forcing SAS URI as environment for Crash monitoring and validating SasURI

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.scss, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts
- Forcing to use SAS URI from environment variables everywhere
- Throwing a warning in AutoHeal page if SAS URI is not configured as an environment variable
@ShekharGupta1988  - Please check if this text looks ok
`Please reconfigure the storage account by clicking on the Custom Action section above. This 
ensures that SAS URI gets stored as an environment variable which is more secure than passing 
the SAS URI as a parameter to the DaaSConsole executable.`
=> Warning in AutoHeal if SAS URI not in Env Vars

AngularApp/projects/applens/src/app/shared/auth/aad-auth-guard.service.ts, AngularApp/projects/applens/src/app/shared/components/unauthorized/unauthorized.component.ts, ApplensBackend/Controllers/IncidentAssistanceController.cs
This PR is for two things:
1. In the current experience of getting temporary access, the user gets redirected to applens home page, and if they came with a deeplink, that is lost. This PR solves the problem by storing the deeplink in on localstorage and retreiving it once the user has gained temporary access. i.e. The user will be directed to the same page that they came for.
2. ICM Incident Assist currently follows Applens Access authorization. But since this is a wider feature and sometimes critical, we are allowing people within Microsoft to be able to interact with this even if they're not part of Applens access. i.e. The users will be authenticated against being in Microsoft tenant only.
=> Deeplink redirect post temporary access

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-arm-config.service.ts
Seeing some null reference exception from Application insights occuring 13 times for 12 users. This PR is to fix the exception:
https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%2290731d56-7842-11eb-b036-e33ad64f9edf%22,%22timestamp%22:%222021-02-26T14:54:44.477Z%22%7D/ComponentId/%7B%22Name%22:%22DiagnoseAndSolvePortal%22,%22ResourceGroup%22:%22DiagnoseAndSolve%22,%22SubscriptionId%22:%22c1972e9d-b3c7-4de4-acb3-681773b28ced%22%7D
Uncaught (in promise): TypeError: Cannot read property 'homePageText' of undefined
TypeError: Cannot read property 'homePageText' of undefined
at t.project (https://appservice-diagnostics.azurefd.net/main.3bb93b7fccfaccb9c294.js:1:5781441)
at t._next (https://appservice-diagnostics.azurefd.net/main.3bb93b7fccfaccb9 …
=> Fix null reference for homepageText attribute

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.scss, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts
- Disable CLR Profiler with ThreadStacks option in AutoHealing UI till the StackTracer issue is fully resolved
- Change the end time for Crash Monitoring from 30d to 20d to prevent a backend overflow bug when using Timer
=> Disable ThreadStacks in Autoheal and set time to 20d for CrashMon

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html
We are seeing increasing number of exceptions from this page for last 3 days:
https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22e4caa611-8586-11eb-88db-2f334d048792%22,%22timestamp%22:%222021-03-15T12:06:37.494Z%22%7D/ComponentId/%7B%22Name%22:%22DiagnoseAndSolvePortal%22,%22ResourceGroup%22:%22DiagnoseAndSolve%22,%22SubscriptionId%22:%22c1972e9d-b3c7-4de4-acb3-681773b28ced%22%7D
=> Fix null reference in autohealing rules

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/risk-tile/risk-tile.component.html
Bug fix for :
[Genie Bug Bash 2021] - Keyboard Accessibility - Landing Page - Links inside the tiles are not accessible via keyboard tabs
=> [Genie Bug Bash 2021] - Keyboard Accessibility - Landing Page - Links inside the tiles are not accessible via keyboard tabs

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.scss
Fixing for [7614078 - At zoom 400%,Controls and keyboard focus indicator are not appearing properly on the screen](https://msazure.visualstudio.com/Antares/_workitems/edit/7614078)
When zooming in, we will hide side-nav in category page and only show content. Like how side nav behavior for side-nav in home page
=> Shows controls and keyboards when zooming into 400%

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-memory-rule/autohealing-memory-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-requests-rule/autohealing-requests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-slowrequests-rule/autohealing-slowrequests-rule.component.ts, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-startup-time/autohealing-startup-time.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-statuscodes-rule/autohealing-statuscodes-rule.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/proactive-autohealing/proactive-autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/section-divider/section-divider.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-main/daas-main.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/timespan/timespan.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.html
Fixes for these bugs
1726 | [Genie Bug Bash 2021] - Screen Reader - Diagnostic Tools - Reads 'Proactive Tools' as a button | app-service-diagnostics-portal\2101-1 | New | Accessibility; Screen Reader | 2 | 3/25/2021, 10:09:24 PM
1720 | [Genie Bug Bash 2021] - Keyboard Accessibility - Select button in Crash Monitoring is not accessible | app-service-diagnostics-portal\2101-1 | New | Accessibility; Keyboard | 1 | 3/25/2021, 10:03:23 PM
9584705 | Bug | [Screen Reader - App Services -   Diagnose and solve problems]: Screen reader is not reading the error message   shown after deleting the value from required edit field on the page.
-- | -- | --
9584781 | Bug | [Keyboard Navigation - App …
=> Accessibility diag tools

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts
This PR is to enable datable to support data-table to rending cells with markdown. For now, if you want  to render some logs with highlight or customized text style, I recommend to use markdown(<markdown></markdown>) instead of embedded HTML, since some styles will not show up for embedded HTML
=> Rendering table cell with markdown

AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal.ts, AngularApp/projects/app-service-diagnostics/src/app/startup/services/portal.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
This PR is [BUG 1744 AKS Resource cannot open D&S blade in Mooncake - Add Alert whenever Diag Solve Homepage doesnt load](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1744/) 
I add three events(**PortalIFrameLoadingException/PortalIFrameLoadingSuccess/PortalIFrameLoadingStart**) into kusto logging so we can get overall sessions opening iFrame, sessions open successfully, sessions have exception when opening iFrame
=> Add log for portal service

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/detector.ts
This PR supports the IsVisible property in the RenderingProperties object. If the property is false then the object isn't rendered.
Related PR: https://github.com/Azure/Azure-AppServices-Diagnostics/pull/677
=> Support IsVisible flag in RenderingProperties

AngularApp/npm-shrinkwrap.json, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/documents-search.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-documents-search.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.html, AngularApp/projects/diagnostic-data/src/lib/components/documents-search/documents-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/documents-search-config.ts, AngularApp/projects/diagnostic-data/src/lib/models/documents-search-models.ts, AngularApp/projects/diagnostic-data/src/lib/services/generic-content.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/generic-documents-search.service.ts
For support topics where Deep Search is enabled for consumption from Azure Portal, the web search component makes a call to Deep Search API instead of Bing.
This ensures that the existing experience is unaltered.
=> Updated web search component to make calls to Deep Search for specific support topics

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html
Deep Search is currently not enabled for Dynamic Analysis. 
Further for Public portal, we search component takes care of the search. This removes the need for document-search.component
=> Removed document-search.component from detector-list-analysis as DeepSearch is not enabled for Dynamic Analysis

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
Web search delay was introduced to ensure that web results do not appear before detectors start rendering in dynamic analysis.
But as observed recently, this delay is too much, specially when we are expecting the web results. Hence reducing the delay from 10 seconds to 3 seconds.
=> Reducing the delay on web results 10 to 3 seconds

AngularApp/projects/diagnostic-data/src/lib/components/dynamic-data/dynamic-data.component.ts
This PR fixes a regression caused by the introduction of IsVisible flag. Now it renders responses from existing detector binaries correctly.
Tested locally with a modified runtimehost & compilehost with IsVisible removed.
=> Fix regression where nothing is rendered from existing detector binaries

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.ts
Seems like another [alert](https://portal.microsofticm.com/imp/v3/incidents/details/238822616/home) got trigger due to type of undefined. 
I fixed it and checked in home component all places where accessing `this._resourceService.resource` should already with null checking
=> Fix for type of undefined

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.scss
In this PR, I move table description from very top to under search bar, so it can align with Yao's design for Linux Log Viewer detector
=> Move table description under search bar

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-api.service.ts
It looks like we will get failed request if there is Api version appended, something like:
https://management.azure.com/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourcegroups/akstest/providers/microsoft.containerservice/managedclusters/aksperiscope?l=zh?api-version=2019-04-01
=> Revert resource Id url by parsing query param array

AngularApp/projects/app-service-diagnostics/src/app/shared/components/step-views/dropdown-step-view/dropdown-step.component.ts
Fixing [bug 1815](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1815)
```
TypeError: Cannot read property 'focus' of null     
at focus (webpack:///src/app/shared/components/step-views/dropdown-step-view/dropdown-step.component.ts:36:14)     
at value (webpack:///home/vsts/work/1/s/AngularApp/node_modules/@uifabric/utilities/lib/initializeComponentRef.js.pre-build-optimizer.js:31:35)     
at _setComponentRef (webpack:///home/vsts/work/1/s/AngularApp/node_modules/@uifabric/utilities/lib/initializeComponentRef.js.pre-build-optimizer.js:26:4)     
at webpack:///home/vsts/work/1/s/AngularApp/node_modules/@uifabric/utilities/lib/appendFunction.js.pre-build-optimizer.js:19:55     
at forEach …
```
=> Fixing bug 1815

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.html, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/fabric-feedback/fabric-feedback.component.scss
Fix Accessibility bug [[Usable - App Services - Feedback]: The text is getting overlapped while scrolling the "Feedback" blade down.](https://msazure.visualstudio.com/Antares/_workitems/edit/9602362)
=> Fix Accessibility bug

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/cxp-chat-caller.service.ts
We are seeing exception:
TypeError: t.optionalParameters.find is not a function
at find (webpack:///src/app/shared-v2/services/cxp-chat-caller.service.ts:41:66)
at call (webpack:///home/vsts/work/1/s/AngularApp/node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:195:15)
at __tryOrUnsub (webpack:///home/vsts/work/1/s/AngularApp/node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:133:21)
at next (webpack:///home/vsts/work/1/s/AngularApp/node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:77:25)
at _next (webpack:///home/vsts/work/1/s/AngularApp/node_modules/rxjs/_esm5/internal/Subscriber.js.pre-build-optimizer.js:54:17)
at next (webpack:///home/vsts/work/1/s/AngularApp/node_modules/rxjs/_esm5/internal/operators/map.js.pre-build-optimizer. …
=> Add array check for optional params in chat service

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-quick-link.service.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/configFailureFlow.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts
At present, all diagnostic tools are only supported for Function App SKUs other than consumption (SKU is not "Dynamic").  This change allows the network checker diagnostic tool to be used for consumption SKU Function Apps.
Additional changes needed to complete this change:
Local validation by navigating through various WebApps and Function Apps of various SKUs
=> Enabling network checker for Consumption SKU Function Apps

AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.html, AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/cxp-chat-launcher/cxp-chat-launcher.component.ts
Require explicit consent from customers to share/not share diagnostic information before they can start a chat.
Make the chat bubble and all elements on it keyboard accessible.
=> CXP Chat -> Explicit consent to share diagnostic information before starting chat

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/commonRecommendations.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/connectionFailureFlow.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js
1. getKuduApiAsync and postKuduApiAsync uses management api by default
2. add a new CommonRecommendations to place common recommendations, will create each flow's recommendation js file to separate recommendations from flow logic
=> Network Troubleshooter calls Kudu api via control plane

AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.html, AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.scss, AngularApp/projects/applens/src/app/modules/incidentassist/components/incidentvalidation/incidentvalidation.component.ts
We have already started posting solutions on ICM incidents.
This work is related to showing solutions to customers even before that when the CRI validation has failed and they visit **AppLens CRI correction page** to update the right information.
Once they provide the correct information, we show them any insights that show potential issues detected with their app.
It is possible customer finds this information relevant and never reactivates the CRI, thus creating deflection.
=> Adding AppLens Insights on CRI Correction page

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/portal-referrer-resolver/portal-referrer-resolver.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-checks.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/detector.ts
Add Network Troubleshooter to portal referrer for enabling integrated diagnostic experience for Network Troubleshooter
add a new `redirectFrom` queryParamter to indicate where the request was routed from
minor adjustments in network check component for integrated diagnostic experience
=> Add Network Troubleshooter to portal referrer

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.html, AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table-filter/fab-data-table-filter.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/detector.ts
This PR is followed by Michi's one to enable customize search place holder and pre-select table filter from detector code
To specify default selection option for a column, you can pass list of sting for option name you want to  select
```
var machineNameColumnOption = new TableColumnOption()
{
Name = "Instance",
SelectionOption = FileterSelectionOption.Single,
DefaultSelection = criticalInsightMachineName != null ? new List<string> { criticalInsightMachineName } : null,
MaxWidth = 120,
Visible = false,
};
```
To customize search place holder text, you can specify it with `SearchPlaceholder `  and need to set `AllowColumnSearch` to `true` as well
```
var tableRenderingProps = new TableRendering()
{
Description = downloadLinkMessage,
SearchPlaceholder = "Search By Logs",
AllowColumnSearch = …
```
=> Enable customize search place holder and pre-select options for data table

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.html, AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts
Hide confirmation message for solution action of blade / tab open as those are UI actions and a confirmation message is irrelevant.
=> Hide confirmation message for solution action of blade / tab open

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
What is the white screen problem?
When diagnostics blade is opened in case submission, and no detectors are mapped to the support topic or dynamic analysis is not enabled, customers see a white screen.
Below support topics were identified as showing white screen on case submission diagnostics blade:
ProductId | SupportTopicId | SupportTopicPath | Remarks
-- | -- | -- | --
16072 | 32749791 | Function App\Authentication and Authorization\OpenID Connect provider
16072 | 32630467 | Function App\Availability\Function App restarted | Functions Linux App
16072 | 32786284 | Function App\Availability\Outbound network connections from my app are   failing
16072 | 32786280 | Function App\Networking\Configuring hybrid connections with App Service | Functions Linux App
16072 | 32630463 | Function …
=> Enabling dynamic analysis by default to fix white screen problems

AngularApp/projects/diagnostic-data/src/lib/components/data-table-v4/data-table-v4.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/insight.ts
Three changes in this PR,
1. Fix "Cannot read property 'toLowerCase' of null" in Insight.component
2. Fix  if table is empty in first place, we will show no filters.
3. Based on [WI 10316548](https://msazure.visualstudio.com/Antares/_workitems/edit/10316548), currently when displaying insight title in analysis view, we will only it pick from basic Insight. In this PR, I adding logic to pick title from both basic insights as well as dynamic insights, so insight title will be aligned with the status respectively.
In analysis,
In detector view,
=> Enable for picking dynamic insight title for analysis view

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/server-farm.ts
@puneetg1983  Putting this PR for autoheal disablement as we discussed the other day. 
In this PR, "Diagnostic Tools" category card will only show for the following type of resources in D&S homepage:
1. Linux web app
2. Linux paid dedicated function app.
Please help review/test it accordingly and see if I am missing anything here.
=> Enable diagnostic tools only for linux web app and linux paid dedicated function app

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/collapsible-list/collapsible-list-fabric/collapsible-list-fabric.component.html, AngularApp/projects/diagnostic-data/src/lib/components/collapsible-list/collapsible-list-fabric/collapsible-list-fabric.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/collapsible-list/collapsible-list-fabric/collapsible-list-fabric.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.html, AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/solution-view-container/solution-view-container.component.scss
Changes:
1. Icons on various sections. Reduced spacing between sections.
2. Display web articles on top if no detector solutions found.
3. Expand Observations section by default when displaying articles on top.
4. Fixed the alignment issue in "Try these other options" section.
5. Timeout logic, if detectors do not return results after 10 seconds (configurable) then show article solutions on top.
6. Changing the wording of the top section from **"We think we found you a solution!"** to **"Try these potential solutions!"**
Enabling this experience **for only a couple of test subscription** (Antares-Demos and Khaled's private sub where most of our test apps exist) in one support topic Azure DevOps (for Sam's demo)
When detector solutions are found:
When detector solutions are either not …
=> Solution orchestrator updates

AngularApp/projects/applens/src/assets/enabledResourceTypes.json
To start with, the entry point will be like ARM Resource (later we will build an appname kind of experience when there is more clarity on how worker apps are searched)
Landing page and first sample detector:
This change is just to facilitate them to start developing detectors. Worker Apps is still a work in progress and we will add more features and icons (currently we are using the kubernetes icon for them).
=> Enable Worker App on AppLens

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/vnetDnsWordings.js
=> Fixes bug in Functions network validation  where it runs despite Kudu being unavailable.

AngularApp/projects/applens/src/app/app.module.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/modules/workerapp/workerapp-finder/workerapp-finder.component.html, AngularApp/projects/applens/src/app/modules/workerapp/workerapp-finder/workerapp-finder.component.scss, AngularApp/projects/applens/src/app/modules/workerapp/workerapp-finder/workerapp-finder.component.spec.ts, AngularApp/projects/applens/src/app/modules/workerapp/workerapp-finder/workerapp-finder.component.ts, AngularApp/projects/applens/src/app/modules/workerapp/workerapp.module.ts, AngularApp/projects/applens/src/app/shared/models/observer.ts, AngularApp/projects/applens/src/app/shared/models/resources.ts, AngularApp/projects/applens/src/app/shared/providers/resource.service.provider.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/workerapp.service.spec.ts, AngularApp/projects/applens/src/app/shared/services/workerapp.service.ts, AngularApp/projects/applens/src/app/shared/shared.module.ts, AngularApp/projects/applens/src/assets/enabledResourceTypes.json, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/ObserverClientService/DiagnosticObserverClientService.cs, ApplensBackend/Services/ObserverClientService/IObserverClientService.cs, ApplensBackend/Services/ObserverClientService/SupportObserverClientService.cs
This PR achieves three things:
**1. Observer integration in AppLens for Worker Apps.
2. Passing Geomaster information to diagnostics backend for Geomaster data provider for worker apps.
3. Worker apps search experience on the AppLens main landing page**
**Landing Page Experience**
User selects Worker App from dropdown
User Enters Worker App name and clicks Go
Detector view with data confirmation of Geomaster data and observer data:
=> Worker Apps in AppLens

AngularApp/projects/app-service-diagnostics/src/app/shared/components/portal-referrer-resolver/portal-referrer-resolver.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/portal-referrer-map.ts
As per load balancing team, they want to deep link a detector view with the category side nav info. This PR is to address the requirement.
=> Create deep link to detector page with category side nav

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Currently route query params are not sent for detector compilation so its hard to check your changes before actually publishing detector changes. This PR makes the change to include route query params during compilation to aid better testing.
=> Detector compilation with route query params

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-startup-time/autohealing-startup-time.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/collapsible-menu-item/collapsible-menu-item.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-v2/daas-v2.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/card-selection-v4/card-selection-v4.component.html
Fixes for these and some DAAS UI bugs.
<html>
<body>
ID | Title | State | Area Path | Tags | Comments | Changed Date
12480713 | [Screen reader - App Service - Startup Time]: Screen reader is not announcing the state that “Start time up” button is selected or not selected. | Approved | Antares\ANTUX | A11YMAS; A11ySev2; Accessibility; Benchmark; Benchmark-HCL-AppServiceWebApp-OCT2021; Diagnose and Solve Problems; HCL; MAS4.1.2; Win10-Firefox | 0 | 11/15/2021, 9:33:15 PM
12481736 | [Programmatic Access - App Service - Diagnostic tools]: Ensures <img> elements have alternate text or a role of none or presentation (.card-tile-image) | Approved | Antares\ANTUX | A11yAuto; A11YMAS; A11ySev2; Accessibility; Benchmark; Benchmark-HCL-AppServiceWebApp-OCT2021; …
=> Accessibilty and service health bugs

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-time-picker/detector-time-picker.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/abtesting.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/loader-detector-view/loader-detector-view.component.ts
This PR is for,
1) Remove logging for throttling issue [WI 2072](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2072)
2) Change min date in time-picker to last 30 days instead of last 1 month [WI 2081](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2081)
3) Disable A/B testing banner since traffic to preview slot is 100% now
=> Remove logging, Disable A/B testing banner, Change time-picker logic

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.ts
Cloud Services in ANT96 are still pointing to old KuduLite bits. I will remove this check after ANT 96.1 is deployed (Rough ETA is first week of Jan)
=> Enable Sessions button for Linux .NET Core apps

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
<html>
<body>
2144 | Portal kusto exceptions: dass/sessions route note registered: | app-service-diagnostics-portal\2101-1 | New | Service Health | 0 | 12/8/2021, 11:53:03 PM
</body>
</html>
=> Disable /daas/sessions call if we get 'no route registered'

AngularApp/projects/diagnostic-data/src/lib/components/solution/solution.component.html
Currently for ASE solutions also, we show "App:" which is incorrect
=> Change 'App:' to 'Name:' to generalize solutions 

AngularApp/projects/diagnostic-data/src/lib/components/step-views/step-view-lib.ts
Safari doesn't support regex lookbehind, which is breaking Diagnose and Solve for safari users. This is the PR to temporary fix the loading experience. 
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
Still need help from @yifguoMSFT and @puneetg1983  to find the alternative regex pattern to replace the negative lookbehind here:
const regex = new RegExp("(?<!\!)\[(.*?)]\((.*?)( +\"(.*?)\")?\)", "g");
=> Fix loading issue on safari

AngularApp/projects/app-service-diagnostics/src/app/home/home.module.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-v2/daas-v2.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/memorydump-tool/memorydump-tool.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/memorydump-tool/memorydump-tool.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts
There is a change done with ANT97 (for Linux Apps) in which a new route for checking the active session was added to KuduLite. The new route is `daas/sessions/active`. It looks like while making that change, the old route `daas/activesession` got accidently removed from KUDU code. Due to this, sites that are getting upgraded to ANT97 will fail to run Diagnostic Tools for Linux. This PR addresses will basically check for both the routes.
Secondly, with ANT98, we are changing the way DaaS sessions will be submitted which means we need to change the way some of the DAAS APIs are called. Also if an app is running on both ANT97 and ANT97, diagnostic tools wont work. To handle this, I will be updating the LinuxDiagnosticTools detector and that detector will check the instances on which the app …
=> Handle Platform versions for Linux Diagnostic tools

AngularApp/projects/app-service-diagnostics/src/app/home/components/support-topic-redirect/support-topic-redirect.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/components/diagnostic-tools/diagnostic-tools.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/resource-redirect/resource-redirect.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/logging/logging.service.ts, AngularApp/projects/app-service-diagnostics/src/app/startup/services/auth.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-support-topic.service.ts, AngularApp/projects/diagnostic-data/src/lib/models/detector.ts, AngularApp/projects/diagnostic-data/src/lib/services/generic-support-topic.service.ts
To support opening detector page with new SapSupportTopicId for ASC and help 2.0, we parse SapSupportTopicId along with SupportTopicId in startupInfo.
For Support topic service, SapSupportTopicId will take precedence over SupportTopicId to find the matched detector.
We still need to update chat service to check live chat eligibility for the passed SapSuppotTopicId. 
@nmallick1 will help update live chat support for SapSuppotTopicId.
=> Add sap id routing for D&S

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/user-active-pullrequests/user-active-pullrequests.component.ts
- When authors create new detectors/gist, they can go back and edit them via Active Pull Requests tab 
- Whenever branch is created for gist PR, the branch name would be dev/user-alias/gist/id instead of dev/user-alias/detector/id
- Ability to create deep link of branch query param with edit flow
=> Branch queryparam

AngularApp/projects/diagnostic-data/src/lib/utilities/uri-utilities.ts
This PR fixes removing branchInput query param when navigating from other places except for Active Pull Requests. When Navigating from side menu, we do not need this input as it can interfere with branch selection. Eg; when creating new detector we do not need this query param.
=> Remove extra query param when not needed

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts
the formula we are using to calculate this exposure works only for minimum 6% of the subs and not below that.
=> Update 10% of subs to see DownloadReport Button

AngularApp/projects/applens/src/app/shared/components/l1-side-nav/l1-side-nav.component.html, AngularApp/projects/applens/src/app/shared/components/l1-side-nav/l1-side-nav.component.scss
Adding padding for subitems in side menu:
=> Add padding for side menu subitems in Applens

AngularApp/projects/applens/src/app/shared/components/l1-side-nav/l1-side-nav.component.html
Fix side nav item format while collapsing the main menu:
=> Fix side nav collapse indentation

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing.component.html
ID | Title | State | Area Path | Tags | Comments | Changed Date
12480713 | [Screen reader - App Service - Startup Time]: Screen reader is not announcing the state that “Start time up” button is selected or not selected. | New | Antares\ANTUX | A11YMAS; A11ySev2; Accessibility; Benchmark; Benchmark-HCL-AppServiceWebApp-OCT2021; Diagnose and Solve Problems; HCL; MAS4.1.2; Regressed:27-12-21; Reopen; Win10-Firefox | 6 | 3/24/2022, 2:58:38 AM
=> Fix for [Screen reader - App Service - Startup Time]

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
While we still don't have the proper form of Diagnose and Solve fully enabled in China cloud, we need to provide this static view of text for AKS in China cloud just like how it was before as we are seeing issues where customer's are seeing the new UI of Diagnose and Solve and they are not able to successfully use it. 
This is a temporary solution until the coming weeks we can deploy an instance of appservice diagnostics in that cloud.
=> Edit the home page to show the static AKS text in China cloud.

AngularApp/projects/applens/src/app/app.module.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp-finder/staticwebapp-finder.component.html, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp-finder/staticwebapp-finder.component.scss, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp-finder/staticwebapp-finder.component.ts, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp.module.ts, AngularApp/projects/applens/src/app/shared/models/observer.ts, AngularApp/projects/applens/src/app/shared/providers/resource.service.provider.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/staticwebapp.service.ts, AngularApp/projects/applens/src/app/shared/shared.module.ts, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/ObserverClientService/DiagnosticObserverClientService.cs, ApplensBackend/Services/ObserverClientService/IObserverClientService.cs, ApplensBackend/Services/ObserverClientService/SupportObserverClientService.cs
This PR is for enabling searching Static Web App by app name or default host name via Observer
Now in landing page dropdown, we have a new option "Static Web App"
If multiple app with same name, it has the same experience as Web App and Container App,
In home page, it shows info fetched from Observer
=> Enabling searching static web app by app name or default host name

AngularApp/projects/app-service-diagnostics/src/app/home/components/home/home.component.html
While we still don't have the proper form of Diagnose and Solve fully enabled in China cloud, we need to provide this static view of text for AKS in China cloud just like how it was before as we are seeing issues where customer's are seeing the new UI of Diagnose and Solve and they are not able to successfully use it. 
This is a temporary solution until the coming weeks we can deploy an instance of appservice diagnostics in that cloud.
=> Edit the home page to show the static AKS text in China cloud. (#1501)

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html, AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/shared/providers/resource.service.provider.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, AngularApp/projects/applens/src/app/shared/services/resource.service.ts, AngularApp/projects/applens/src/app/shared/services/stamp.service.ts, AngularApp/projects/applens/src/assets/enabledResourceTypes.json, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/KustoService/IKustoQueryService.cs, ApplensBackend/Services/KustoService/KustoSDKClientQueryService.cs
Adding a few more features for stamps in AppLens.
Jarvis Dashboard Link and Kusto cluster name in overview section
Same in resource info panel
For a VMSS stamp
For a Cloud Service stamp
=> Stamp - Jarvis link, Kusto cluster mapping

AngularApp/projects/applens/src/app/app.module.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-diagnostic.service.ts, AngularApp/projects/applens/src/app/modules/main/main.module.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.html, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/models/alerts.ts, AngularApp/projects/applens/src/app/shared/models/resources.ts, AngularApp/projects/applens/src/app/shared/services/alert.service.spec.ts, AngularApp/projects/applens/src/app/shared/services/alert.service.ts, AngularApp/projects/applens/src/app/shared/services/applens-http-interceptor.service.spec.ts, AngularApp/projects/applens/src/app/shared/services/applens-http-interceptor.service.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, AngularApp/projects/applens/src/app/shared/shared.module.ts, AngularApp/projects/applens/src/assets/enabledResourceTypes.json, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts, ApplensBackend/Controllers/DiagnosticController.cs, ApplensBackend/Helpers/Constants.cs
Main component:
1. Check if user needs a case number (logic is in the backend). Then display user a case number field.
The case number field will be displayed only if durian is enabled for the certain product and the user needs case number to access.
2. As user enters the case number and resource name and tries to get in, we validate the information and display any error like this
Another scenario of bad case number
3. If everything is alright, user enters AppLens and can access detectors
=> Durian UI Changes

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
Fix for exception ``Cannot set properties of undefined (setting 'isVisible')``
[End To End Transaction](https://ms.portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22c1972e9d-b3c7-4de4-acb3-681773b28ced%22%2C%22ResourceGroup%22%3A%22DiagnoseAndSolve%22%2C%22Name%22%3A%22DiagnoseAndSolvePortal%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fc1972e9d-b3c7-4de4-acb3-681773b28ced%252FresourceGroups%252FDiagnoseAndSolve%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252FDiagnoseAndSolvePortal%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22cf795900-d5c6-11ec-81ad-4b0b10f152db%22%2C%22timestamp%22%3A%222022-05-17T09%3A50%3A3 …
=> Fix Form Exception

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.html, AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.scss, AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html
Changed some styles for resource information in home page to fix bugs 
1. Fix for ASE resource information not showing up
2. Fix when zoom into 300% resource info will be overlapping with each other 
3. Fix when resource information is too long will get truncated. Now it will push to right as much as can be to give enough space for showing whole information
=> Fix some resource info not showing

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
branch input would persist in the query params and cause errors when editing a different detector. this change clears the branch input query param when navigating away from the page
=> clear branch input

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/shared/models/observer.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/site.service.ts, AngularApp/projects/applens/src/app/shared/utilities/sku-utilities.ts, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/ObserverClientService/DiagnosticObserverClientService.cs, ApplensBackend/Services/ObserverClientService/IObserverClientService.cs, ApplensBackend/Services/ObserverClientService/SupportObserverClientService.cs
As feature ask [Add App Service Plan Pricing tier and worker size to Applens tool](https://msazure.visualstudio.com/One/_workitems/edit/7290649).
Jeff created a new API(/api/stamps/stamp/sites/site/sku) in Observer to get SKU/Worker Size/Worker Count. Converted to price tire and showing as same format as shown in portal.
=> Update SKU code getting from Observer

AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts
This PR is to fix the broken navigations in case submission flow caused by these routes:
Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'resource/subscriptions/8aeff191-4048-4d78-beac-a31e870464ae/resourcegroups/indigo-services-prd-rg/providers/microsoft.web/sites/partscatalogintegrationservice-pro/integratedSolutions/**analysis/searchResultsAnalysis/analysis/searchResultsAnalysis**/search/detectors/appchanges'
Error: Cannot match any routes. URL Segment: 'resource/subscriptions/8aeff191-4048-4d78-beac-a31e870464ae/resourcegroups/indigo-services-prd-rg/providers/microsoft.web/sites/partscatalogintegrationservice-pro/integratedSolutions/analysis/searchResultsAnalysis/analysis/searchResultsAnalysis/search/detectors/appchanges' …
=> Fix case submission flow broken navigation

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/models/user-setting.ts, AngularApp/projects/applens/src/app/shared/services/site.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts, ApplensBackend/Models/RecentResource.cs
1. Store query params (startTime,endTime, caseId, ect...) when updating recent resource. 
When click recent resource it will route to time period which fetching from cosmosDB instead of last 24 hours
2. Change time string format to **"YYYY-MM-DD HH:mm"** in time-picker and downtime selection to be consistency. And also allow to type as this format in date-picker
Todo, after this PR deployed. Also need to update time string format for downtime gist(DowntimesGist) and overview metric detector(applensoverviewmetrics_appservices)
=> Store recent resource query params and update time string format

AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
Fix the original behavior to only expand analysis category:
=> Fix side nav auto expansion

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts
Currently if DiagServer is enabled, the UI will make a call to /v2/sessions and this will fail with 404 if the storage account is not configured. With this change, we will only make the call if StorageAccount is configured thus avoiding any 404s. We are doing this so that 404s don't end up in customer's logs as that earlier ended up raising some tickets.
Also increasing the polling time for DaaS sessions from 30s to 60s
=> Avoid polling DiagServer sessions if Storage not configured

AngularApp/projects/app-service-diagnostics/src/app/genie/message-flow/genie-feedback/genie-feedback.component.ts, AngularApp/projects/applens/src/app/collapsible-menu/components/collapsible-menu-item/collapsible-menu-item.component.html, AngularApp/projects/applens/src/app/collapsible-menu/components/section-divider/section-divider.component.html, AngularApp/projects/applens/src/app/modules/containerapp/containerapp-finder/containerapp-finder.component.html, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html, AngularApp/projects/applens/src/app/modules/site/site-finder/site-finder.component.html, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp-finder/staticwebapp-finder.component.html, AngularApp/projects/diagnostic-data/src/lib/components/fabric-feedback/fabric-feedback.component.html, AngularApp/projects/diagnostic-data/src/lib/components/fabric-feedback/fabric-feedback.component.ts
[Bug 2317](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2317): [Keyboard Navigation - AppLens- Multiple Cheesecake] Tiles controls available under "Multiple sites with the name 'Cheesecake' found. Pick the correct one:" are not accessible using keyboard
[Bug 2327](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2327): [Keyboard Navigation - AppLens- Cheese cake app] Focus doesn't land on the first interactive control of 'Feedback' screen when feedback control is activated
[Bug 2337](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2337): [Keyboard Navigation - AppLens- Web App down] Focus order is incorrect while navigating on 'All …
=> Fix applens accessibility bugs

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-markdown/app-insights-markdown.component.html
Temporarily removing the AppInsights specific headers to ensure the rendered output is consistent with the rest of the detector rendering. If you think AppInsights specific renderings need to be distinguished, we can think about improving this later in long term.
**Earlier**
----
**Now**
----
=> Remove AppInsights Specific header rendering for consistency

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas/daas.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas/daas.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/java-flight-recorder/java-flight-recorder.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler/profiler.component.html
Linux Diagnostic tools are failing with an exception the first time the storage account is not configured. The PR fixes that issue and removes the unused variable.
=> Correcting intial load failure of Diagnostic tools for Linux

AngularApp/projects/app-service-diagnostics/src/app/diagnostic-tools/diagnostic-tools.routeconfig.ts, AngularApp/projects/app-service-diagnostics/src/app/home/home.module.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas/daas.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler/profiler.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-cpu-profiler/linux-node-cpu-profiler.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-cpu-profiler/linux-node-cpu-profiler.component.spec.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-cpu-profiler/linux-node-cpu-profiler.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-heap-dump/linux-node-heap-dump.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-heap-dump/linux-node-heap-dump.component.spec.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-node-heap-dump/linux-node-heap-dump.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-python-cpu-profiler/linux-python-cpu-profiler.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-python-cpu-profiler/linux-python-cpu-profiler.component.spec.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/linux-python-cpu-profiler/linux-python-cpu-profiler.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/tools-constants.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/shared.module.ts
Enabling Node heap dump, Node CPU profiling and Python CPU profiling tools for Linux Apps. We will control where these tools are showed via the LinuxDiagnosticTools detector in applens. 
> Currently they are showing only for two subscriptions and for ANT99 stamps.
=> Adding DiagServer diagnostic tools for Linux

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
Dropdown Id need to be a string starts with letter and only contains letters, digits and symbols (hyphen, underscore, colons)
=> Fix exception for "Failed to execute 'querySelector' on 'Document': '#1.5-list11' is not a valid selector"

AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html
Fix for accessibility bug [[Keyboard Navigation - AppLens- Welcome] 'App Lens (prod)' control available on the top of screen is not keyboard accessible](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2368)
=> Add focus for applens icon

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/utils/apollo-utils.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.ts
We are making change to our self help content pulling mechanism as follows:
- First we talk to the Apollo API. If Apollo API returns a response, we clean it up and render it.
- If Apollo API fails, then we fallback on the earlier API we have been using.
Some screenshots with scenarios:
1. WebApps analysis view:
2. WebApps detector view:
3. AKS analysis view:
=> Pull self help content from Apollo API

AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.html, AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.ts
Improvements include:
- Added a "None" options in dropdown to convey no team is selected by default.
- Reset the TestWithRealIncidents blade after team selection has changed.
- Other variables reset handling.
=> ICMSelfServe: Some improvements to UI view changes

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/utils/apollo-utils.ts
Additionally if apollo content is meaningless then we consider it as no content and fallback.
=> Fix links in apollo to open in new tab

AngularApp/projects/app-service-diagnostics/src/app/shared/services/appinsights/appinsights.service.ts, Backend/Controllers/AppSettingsController.cs, Backend/Services/EncryptionService/EncryptionService.cs
- Fixed NULL check which was causing apps using the integration feature for the first time to fail if the site has no ARM tags
- Setting the value of `useAppSettingsForAppInsightEncryption `by reading it from the app setting `AppInsights:UseCertificates` (also whitelisted this app setting). This was done because I found issues when UI is using cache version and API is returning latest status for useCertificate to true, a mismatch was happening, and this was causing feature to break
- Added some exception handling and improved some error logging.
=> AppInsights Encryption feature improvements and error handling

ApplensBackend/Configuration/Startup.cs, ApplensBackend/Services/Authorization/AuthorizationHandler.cs
In AppLens, because we used Dictionary and not ConcurrentDictionary for inmemory caching of user auth status, there is an intermittent issue that occurs sometimes due to multiple threads concurrently trying to modify the dictionary due to which user will get "Unauthorized access". Checking in AppInsights logs, nearly ~10 users see this intermittently at some point of time every week.
This PR fixes the issue.
=> Fix intermittent unauth issue and refactor code in auth handler

AngularApp/projects/diagnostic-data/src/lib/components/guage-graphic/guage-graphic.component.scss
Re-import the CSS for Gauge rendering.
=> Fix for Gauge CSS 

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.html, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-tile-v4/category-tile-v4.component.ts, AngularApp/projects/app-service-diagnostics/src/app/home/components/category-tile/category-tile.component.html, AngularApp/projects/app-service-diagnostics/src/app/home/components/category-tile/category-tile.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/models/category.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
Add deep link to most frequently used tools/detectors within the category tile on the home page.
Add logging to allow for easy data mining for understanding user behavior.
Home page for all other products remain unchanged.
=> Show deep links on category tile

AngularApp/projects/app-service-diagnostics/src/app/home/components/category-nav/category-nav.component.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/site-feature.service.ts, AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/sites-category.service.ts
Enabling Diagnostic Tools in portal for Logic App Standard.
Will be powered by Overview detector
=> Add Diagnostic tools for LogicApp standard on Diagnose And Solve portal.

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/flowMisc.js, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/network-check-flows/functionsFlow.js, AngularApp/projects/app-service-diagnostics/src/app/shared/models/network-troubleshooter/post-request-body.ts
Updated code with unwrap/wrap for management api requests. 
Added new method that uses NetworkTroubleshooter to run TCP Pings. Received a 200 response testing on Balag-win-ep2 app FunctionApp.
Prior to change : 
Run Kudu Bash command to TCP ping Host:Port 
Stream stdout, split by /r/n, capture results for all responses from TCP Ping
Now : 
Use NetworkTroubleshooter API to execute TCP Ping against host.
=> Use Network Troubleshooter to TCP Ping websites and wrap management requests

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/network-checks/diag-provider.ts
With the ARM endpoint available on production, it is necessary for us to update the route that the Angular application calls. I have tested this locally successfully
=> Fix Network Checker Route on Angular App

AngularApp/projects/applens/src/app/modules/ase/ase-finder/ase-finder.component.ts, AngularApp/projects/applens/src/app/modules/containerapp/containerapp-finder/containerapp-finder.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts, AngularApp/projects/applens/src/app/modules/site/site-finder/site-finder.component.ts, AngularApp/projects/applens/src/app/modules/stamp/stamp-finder/stamp-finder.component.ts, AngularApp/projects/applens/src/app/modules/staticwebapp/staticwebapp-finder/staticwebapp-finder.component.ts, AngularApp/projects/applens/src/app/shared/models/observer.ts, AngularApp/projects/applens/src/app/shared/services/ase.service.ts, AngularApp/projects/applens/src/app/shared/services/containerapp.service.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/services/site.service.ts, AngularApp/projects/applens/src/app/shared/services/stamp.service.ts, AngularApp/projects/applens/src/app/shared/services/staticwebapp.service.ts, AngularApp/projects/diagnostic-data/src/lib/utilities/resiliencyScoreReportHelper.ts
- Fixing SKU enum from Observer in AppLens as it's different than the one used by the Sku used in app-service-diagnostics. This was causing for AppLens to not show ResiliencyScoreReport download button for IsolatedV2 and IsolatedV3 apps.
- Removed Observer namespace as it was causing issue with the new ObserverSku and we couldn't see the value to keep it
- Fixing typo in report for a link that had .htm instead of .html
- Adding Message to ResiliencyScoreReportInPrivateAccess logging events in AppLens
=> Removing Observer namespace + new ObserverSku

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-search/detector-search.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/solution-orchestrator/solution-orchestrator.component.ts
Today if a product has Shield enabled but their RP does not pass the search term to our backend, then for the backend its basically a ListDetectors call and all detectors are returned, which are executed by Shield (without knowing that the RP messed up).
This will compare to catch this scenario in the Shield frontend and not run the all detectors list.
=> Fix for when an RP does not pass search parameter to Diagnostics backend

AngularApp/projects/app-service-diagnostics/src/app/globals.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/breadcrumb.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list-analysis/detector-list-analysis.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/generic-breadcrumb.service.ts, AngularApp/projects/diagnostic-data/src/lib/services/genie.service.ts
Add Go back button to enable go back from child detector to analysis or parent detector
In Diag&Solve blade,
In case submission
=> Add bread crumb to go back in portal

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.html, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/utilities/main-page-menu-options.ts
In PR [1774](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1774) we had made a change to fix a bug with fab-text-field that interrupts user typing. However as a result two-way binding is lost for the fields and we are unable to pre-populate the fields after Durian shows error.
This PR ensures that we are able to pre-populate those fields (using defaultValue), together with ensuring that the fix in the original last PR is maintained.
=> Some refactoring and fix for form autofill when Durian shows error and some refactoring

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.html, AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.scss, AngularApp/projects/applens/src/app/modules/incidentassist/components/template-management/template-management.component.ts, ApplensBackend/Services/IncidentAssistanceService/IncidentAssistanceService.cs, ApplensBackend/Services/SurveysService/SurveysService.cs, ApplensBackend/appsettings.Fairfax.json, ApplensBackend/appsettings.Mooncake.json, ApplensBackend/appsettings.USNat.json, ApplensBackend/appsettings.USSec.json, ApplensBackend/appsettings.json
This PR fixes three issues:
1. Default resource type for Durian to autofill in Applens main page after there is a user error.
2. ICM automation template management facing issues in text fields after Angular upgrade.
3. [Some recent changes](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1833) made to appsetting names may disrupt the functioning of ICM automation in Applens. Reverting those until a planned strategy.
Text fields have lost two-way binding after angular upgrade. Fixes those issues.
Fixes some issues occurring due to recent changes.
Tested locally by running updates to text fields and verifying in database.
=> Fixing emerging issues with some features

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-time-picker/detector-time-picker.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
This PR is for,
- Update error message for invalid time, showing error message related to reading startTime and endTime from query params in the detector page instead of hiding in the time-picker dropdown
- Remove comment code and replace **flatMap** as **mergeMap** since flatMap is deprecated
=> Showing error message for invalid time reading from query params

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
Adds logging of user's alias against the session id when they enter Applens. This helps in feature usage analysis and debugging when a certain user faces problems.
None
Logging
Can look into the logging events in browser network trace to confirm logging is happening. Eventually we will search for the logged event in AppInsights.
=> Log user alias at entry time in Applens

AngularApp/projects/diagnostic-data/src/lib/components/highcharts-graph/highcharts-graph.component.ts
This PR is for disabling configuring for tooltip background from detector code as it will break in the dark mode
[WI 2822: Graph tool tip in dark mode is not legible ](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2822)
Delete customized config for tooltip background color when updating graph options
1. Go to portal or Applens in local, 
2. Set theme to dark mode
3. Go to "SNAT Port Exhaustion" detector 
4. Hover over on any graph and check if tooltip is legible
=> Fix for tooltip background color config

AngularApp/projects/diagnostic-data/src/lib/components/time-series-graph/time-series-graph.component.ts
When calculating the time difference in minutes for data that's rendered on the Gantt Chart, the milliseconds in the timestamp results in inaccurate calculation and rendering of data on the Gantt Chart. Also, when duplicate date is passed to the Gantt Chart, it results in nothing being rendered on the chart. This fix removes milliseconds from datetime to ensure accurate calculation of timestamps differences and it also removes duplicate row data.
[AB#2632](https://dev.azure.com/app-service-diagnostics-portal/d760220e-01cd-406f-b520-62a6e0779471/_workitems/edit/2632)
~- [ ] New feature (non-breaking change which adds functionality)~
~- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)~
~- [ ] This change requires a documentation update~
- …
=> Remove Duplicate Row Data and Update Start and End time

AngularApp/projects/diagnostic-data/src/lib/components/fab-data-table/fab-data-table.component.ts
Fix for Event Viewer not getting clicked
Click on any of the Event log rows is not selecting the entry due to which the description cannot be viewed by end user
=> Fix for EventViewer not selecting cells

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts
Correcting definitions for MarkdownModule to fix custom styles in markdown. The line that I am removing was overriding the existing MarkdownModule definition
```
MarkdownModule.forRoot({
sanitize: SecurityContext.STYLE
}),
```
=> Correcting definitions for MarkdownModule to fix custom styles in markdown

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.html, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
Since we are planning to expand Durian to more products, we will have some scenarios where Durian configuration is not in sync between Applens and Runtimehost. This can cause some bad situations where the user is stuck. This PR adds a very critical logic to handle error gracefully even if there is a configuration mismatch. This particular change is to handle case number needed error by showing the case number field to the user.
Durian is enabled for any given product from Runtimehost and Applens separately. This can lead to situations where Runtimehost and Applens are not updated synchronously and while the Runtimehost needs a case number, Applens is not asking the user for one (as the frontend config is not yet updated). To handle this - **if the Runtimehost throws an error asking for a …
=> Handle case number needed error gracefully

AngularApp/projects/applens/src/app/modules/dashboard/dashboard-container/dashboard-container.component.ts
The issue is basically Applens does not show any resource information if ASC link is embedded:
This will happen for every CSS user workflow as they provide a case number which activates the embedding of ASC Link.
The core issue was that the resource object is not extensible and thus anything like this.resource['ASCLink'] breaks the code path.
This fix was to use object spread instead of object extension.
Fixes the issue.
I had a lot of fun debugging this and a lot of time.
=> Bug: Resource object is not extensible issue

AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-query-dialog/kusto-query-dialog.component.ts
The next version of DAAS is updating the /databasetest controller from GET to POST. This PR will check if the HTTP GET call fails, a fallback to POST will happen and once entire DAAS is updated, I will revert this code to just make a POST call.
=> Changing Request method to POST for databasetest route

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts, AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/create-storage-account-panel/create-storage-account-panel.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/shared-storage-account.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring-analysis/crash-monitoring-analysis.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/site.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/storage.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/urielements.service.ts
This PR was long pending. We had introduced new app setting `WEBSITE_DAAS_STORAGE_CONNECTIONSTRING ` which can contain the connection string for the storage account. All the DAAS backend tools are updated to honor this app setting. This was done primarily for two reasons:
1) It becomes easier for customers to automate any DAAS tool as now they can easily create a new APP setting WEBSITE_DAAS_STORAGE_CONNECTIONSTRING which points to the connection string directly vs. manually generating the SAS URI and then updating it in their config.
2) We were not following best practices for generating SAS URI as we were creating really long lived SAS URI and this is not recommended.
3) We wanted to have parity with Linux apps as they already use WEBSITE_DAAS_STORAGE_CONNECTIONSTRING.
- With this …
=> Switch to using DaaS Storage connection string instead of SAS URI

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-view/detector-view.component.html
This PR is for
1. Fixing in case submission, it is not redirecting to keystone detector
2. Hide detector description in case submission
[BUG 2973 Logic App Keystone Issue](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2973/?triage=true)
Add tolowercase() when comparing with keyword list and input keyword
1. Open case submission for any consumption logic app
2. In Problem Description, Type "TrustFailure" in summary, select problem type is "Connectors" and sub problem type is "HTTP", click "Next"
=> Fix for not showing keyword and hide description in case submission

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/documents-search.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-content.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-documents-search.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/web-search/web-search.component.ts, ApplensBackend/Configuration/Startup.cs, ApplensBackend/Configuration/StartupNationalCloud.cs, ApplensBackend/Controllers/BingAPIController.cs, ApplensBackend/Controllers/DiagnosticController.cs, ApplensBackend/Services/BingSearchService/BingSearchService.cs, Backend/Controllers/AppSettingsController.cs, Backend/Controllers/BingAPIController.cs, Backend/Services/BingSearchService/BingSearchService.cs, Backend/Startup.cs
Changes to how we call the Bing API to show web results.
ICM Incident from MSRC
Security issue fix for leaking API keys for bing and deep search API.
Moving the calling of Bing API from client to backend
Screenshots after testing:
Web apps genie
Web apps case submission (where no detector is mapped)
AKS genie
AKS Case submission (where no detector and no apollo document is matched)
=> MSRC Security issue: Prevent Bing API key leak

AngularApp/projects/app-service-diagnostics/src/app/shared/services/backend-ctrl.service.ts
We are sending the ARM token to our public UI controller. However, the controller doesn't need it. So we will stop sending it.
=> Stop sending ARM token to public UI controller

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.html, AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.scss, AngularApp/projects/applens/src/app/modules/dashboard/openai-chat/openai-chat.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/user-setting.service.ts, AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.html, AngularApp/projects/applens/src/app/shared/components/applens-header/applens-header.component.ts, AngularApp/projects/applens/src/app/shared/models/user-setting.ts, AngularApp/projects/applens/src/app/shared/services/applens-openai.service.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, AngularApp/projects/diagnostic-data/src/lib/models/chatbot-models.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts, ApplensBackend/Controllers/UserSettingsController.cs, ApplensBackend/Models/RecentResource.cs, ApplensBackend/Services/CosmosDBHandler/CosmosDBUserSettingHandler.cs, ApplensBackend/Services/CosmosDBHandler/ICosmosDBUserSettingHandler.cs, ApplensBackend/Services/CosmosDBHandler/NullableCosmosDBUserSettingsHandler.cs
Some enhancements and optimizations in AppLens ChatGPT.
Added a toggle feature for code completion.
- Adds the feature for user to provide feedback through upvote/downvote button.
- Fixes a bug in scrolling, now it will scroll all the way to the end of the chat while chatting.
- Decouples user chat gpt info from the normal user preferences to avoid slowing down Applens loading (when chats get longer). **Chat info will only be fetched when user visits ChatGPT**.
- Adds a toggle feature in user preferences section for enabling/disabling code completion.
Toggle feature for code completion
=> ChatGPT: Feedback, scrolls, decouple user prefs

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring-analysis/crash-monitoring-analysis.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts
Start time and Stop time get shifted by 1 day on Crash Monitoring. This change fixes the issue
<html>
<body>
2992 | Start time and Stop time get shifted by 1 day on Crash Monitoring | app-service-diagnostics-portal\2203-2 | Active | Service Health | 0 | 2/22/2023, 12:14:58 PM
</body>
</html>
=> Fix Start time getting shifted by a day

AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/tools/crash-monitoring/crash-monitoring.component.ts
Start time and Stop time get shifted by 1 day on Crash Monitoring. This change fixes the issue
<html>
<body>
2992 | Start time and Stop time get shifted by 1 day on Crash Monitoring | app-service-diagnostics-portal\2203-2 | Active | Service Health | 0 | 2/22/2023, 12:14:58 PM
</body>
</html>
=> Fix Start time getting shifted by a day - Part 2

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/detector-command-bar/detector-command-bar.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/download-report/download-report.component.ts
Adding Platform, AppType and ResourceSKU to the ResiliencyScoreReportDownloaded and DownloadReportDirectLinkDownloaded logging events as productName is not as reliable to use to differentiate the Platform and AppType.
N/A
To differentiate the product being use, productName is not enough as in certain scenarios will simply log microsoft.web/sites instead "AZURE WEB APP" or "Azure Web App Linux". Adding Platform, AppType and SKU to both ResiliencyScoreReportDownloaded and DownloadReportDirectLinkDownloaded logging events, will allow to filter by Platform and AppType.
DiagnoseAndSolvePortal Application Insights component in the customEvents table will have for ResiliencyScoreReportDownloaded or DownloadReportDirectLinkDownloaded  logging events, Plaform, AppType and  ResourceSku.
Query in …
=> Adding Platform, AppType and ResourceSKU to Events

AngularApp/projects/applens/src/app/modules/dashboard/favoite-detectors/favorite-detectors.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/breadcrumb.service.ts
This PR is for updating query params handling strategy to preserve query params for navigating from pinned detector and breadcrumb
=> Change query params handling strategy

AngularApp/projects/applens/src/app/modules/dashboard/dashboard.module.ts, AngularApp/projects/applens/src/app/modules/dashboard/services/applens-diagnostic.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-user-access/workflow-user-access.component.html, AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-user-access/workflow-user-access.component.spec.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/workflow-user-access/workflow-user-access.component.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, ApplensBackend/Configuration/Startup.cs, ApplensBackend/Controllers/DiagnosticController.cs, ApplensBackend/Controllers/WorkflowUsersController.cs, ApplensBackend/Services/CosmosDBHandler/CosmosDBWorkflowUsersHandler.cs, ApplensBackend/Services/CosmosDBHandler/ICosmosDBWorkflowUsersHandler.cs, ApplensBackend/Services/CosmosDBHandler/NullableCosmosDBWorkflowUsersHandler.cs, ApplensBackend/Services/WorkflowUsersCacheService/IWorkflowUsersCacheService.cs, ApplensBackend/Services/WorkflowUsersCacheService/WorkflowUsersCacheService.cs
Instead of changing the `Workflow:Users` app setting on all the endpoints, storing the workflow users in CosmosDb and giving a small UI to configure them in AppLens.
Only those users that are part of the existing `Workflow:Users` app setting will be able to add new users to CosmosDB.
=> Allow configuring workflow users by storing them in cosmosDB

AngularApp/projects/app-service-diagnostics/src/app/shared/components/generic-analysis/generic-analysis.component.ts
Showing a search bar if no searchTerm passed for case submission
[Failover mechanism: Display Shield search bar requesting a customer input  ](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_queries/query/a1fb713f-81e9-44e2-93a7-be6daf7c7ed5/)
=> Show search bar if no search term passed

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts
Fixes the issue where JSON deserialization fails due to double quote characters in input query for bing detector id.
We received a SEV 2 for this: https://portal.microsofticm.com/imp/v3/incidents/details/375755846/home
=> URL Encode the values in bing query object

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/ifelse-condition-step/ifelse-condition-step.component.html, AngularApp/projects/applens/src/app/modules/dashboard/workflow/ifelse-condition-step/ifelse-condition-step.component.scss, AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-node/kusto-node.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-query-dialog/kusto-query-dialog.component.html, AngularApp/projects/applens/src/app/modules/dashboard/workflow/kusto-query-dialog/kusto-query-dialog.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/models/kusto.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/node-styles.scss, AngularApp/projects/applens/src/app/modules/dashboard/workflow/services/workflow.service.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-step/switch-step.component.html, AngularApp/projects/applens/src/styles.scss, AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.scss, AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts
- With this PR, we are now enabling the Workflows View experience to all users and only restricting the workflow publishing.
- The other change is a checkbox that allows you to add DataTable output of Kusto Query to markdown.
- Increasing the size of the text in all alerts displayed by Workflow components.
- Apart from that, just changing the schema of workflowNodeData and moving all the Kusto related configuration in its own object. I have added model classes for SlotMapConfiguration but they are not used anywhere yet and will be working on those in the coming days.
Then during actual run phase
=> Kusto node related workflow changes and enabling Workflow view experience for everyone

AngularApp/projects/applens/src/app/modules/dashboard/tabs/tab-data/tab-data.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts
This PR is mainly for fixing two issues for switching detectors in Applens side-nav
1. Switching between detectors is slow and stick with last detector in some cases.
2. Non-web app side nav is not working between switching detectors.
For # 1 Switching between detectors is slow and stick with last detector in some cases,
I use [takeUntil](https://rxjs.dev/api/operators/takeUntil) operator to cancel previous observable by emitting a new value for  **stopDetectorResponseSubject** and switch to new Observable
For # 2 Non-web app side nav is not working between switching detectors,
Me and Nazeef look into and found in <tab-data> component there are null reference for logging, by fixing this side-nav back to work.
Go to any non-web resource, like …
=> Fix for null reference and cancel previous observable when switching between detectors

AngularApp/projects/applens/src/app/modules/main/main/main.component.html, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/models/resources.ts, AngularApp/projects/applens/src/app/shared/services/diagnostic-api.service.ts, AngularApp/projects/applens/src/app/shared/utilities/main-page-menu-options.ts, AngularApp/projects/applens/src/assets/enabledResourceTypes.json
Currently we rely on a config in frontend and a separate config in backend for Durian. Any sync issues between these configs can result in unwanted consequences. This PR aims to change this and make the frontend depend on backend (Runtimehost) config to check for which RPs, case number is enforced.
=> Ask the backend about case enforcement enabled RPs

AngularApp/projects/app-service-diagnostics/src/assets/scripts/monitoring.js, AngularApp/projects/app-service-diagnostics/src/index.html
This PR is for adding monitoring.js script to monitoring blank screen issue for our Angular project 
[WI 2953 Set up more alerts on the SCIFrame blade to catch scenarios when no detector is found, or no expected parameters are present](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2953)
Added monitoring.js scrpit, it will be running once scripted ready. For checking <sc-app> which it a tag created by Angular to make sure our page is not blank. 
If it is a blank screen we will log "PortalBlankPage" event into Kusto table so to get alert based on this event
=> Add monitoring script for checking blank screen

AngularApp/projects/diagnostic-data/src/lib/components/detector-container/detector-container.component.ts
This PR is for reverting changes made in [PR 1967 Fix for null reference and cancel previous observable when switching between detectors](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1967) which will make refresh and time-picker not working
=> Revert change for detecotr-container

AngularApp/projects/applens/src/app/modules/dashboard/network-trace-analysis/network-trace-analysis.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.html, AngularApp/projects/applens/src/app/modules/dashboard/side-nav/side-nav.component.ts
After launching the Network Trace Analysis tool on Applens, we received a feedback from one of its users about how they couldn't search for the tool using the search box on Applens. This was the main initiative behind this fix
- updates the search box functionality to search for tools in the Tools section
- ensures that the `Tools ` section is initially expanded 
- fetches the user id of users who get to use the network trace analysis tool and includes it as a query param in the iframe url This is needed for tracking the page view by aliases.
- Go to http://localhost:4200/
- In the search box nav, type `network`. The Network Trace Analysis title should be bold
=> Make Network Trace Analysis Tool Searchable

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/urielements.service.ts
The DAAS Site extension was updated to ensure all controllers that may return secrets should be marked as POST only. This change will retry the request with POST once the GET call fails with 403.
Once the Site Extension is updated everywhere, will remove this logic and just code for POST requests only. This is just an interim solution till the site extension gets updated everywhere.
https://github.com/Azure/DaaS/pull/101
=> Change DaaS service to retry POST on GET failure

AngularApp/projects/applens/src/app/modules/dashboard/workflow/switch-case-step/switch-case-step.component.ts
Fixing the Save Button not working when switch case is set on a User Input
=> Fix Switch case for UserInputs in Workflows

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
Current Durian implementation forgets the context of where user was going before they ended up with authorization failure. For example if a CSS user clicked a link for a detector (that did not contain casenumber), they are taken back to the main page to enter case number. But when they enter the case number they are taken to the default overview page in applens and not the detector whose link they came from.
This PR improves this experience by storing the user's destination path in localStorage/browser, and when they enter the correct case number, takes them to their original intended destination. It also preserves query parameters like startTime, endTime, form params etc.
Where user is asked to enter the case number
After entering the case number, user is taken directly to the intended …
=> Keep context of where user was going

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.html, AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
- Regular users of AppLens don't need to see pop up notification for pending deployments/PRs
Added isPPE flag to detect the env
Can be tested in staging ppe & staging prod
=> Disable pop up for prod

ApplensBackend/Services/OutageCommunicationService/OutageCommunicationService.cs
Comms query in ICM consuming high memory and are being throttled by ICM cluster
NA
Add kusto caching to comms query so that the data is cached for one day.
Wait for a day and see if the memory usage on ICM cluster has gone down, or execute the raw query with your ID against the ICM cluster and observe the memory usage.
=> Add Kusto caching to Comms query

AngularApp/projects/diagnostic-data/src/lib/components/collapsible-list/collapsible-list-fabric/collapsible-list-fabric.component.html, AngularApp/projects/diagnostic-data/src/lib/components/collapsible-list/collapsible-list-fabric/collapsible-list-fabric.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/detector-list/detector-list.component.html, AngularApp/projects/diagnostic-data/src/lib/components/fab-card/fab-card.component.html, AngularApp/projects/diagnostic-data/src/lib/components/fab-card/fab-card.component.ts
Changing ariaLabel for ChevronUp to include Name, Role, Value
Accessibility bug with Narrator not describing the ChevronUp correctly.
https://msazure.visualstudio.com/Antares/_workitems/edit/17535630
Passing detector title to fab-card, so that it can be used as part of the ariaLabel that contains:
DetectorTitle chevronup collapsed/expanded (Name, Role, Value)
1. Open the URL "http://ms.portal.azure.com/" in edge browser and login with valid credentials.
2. Search and select 'App Services' then will be navigated to 'App Services' page.
3. Select any already created app service and navigate to 'Custom domain' control in left pane and select it.
4. Navigate all controls under the 'Custom domain' blade.
5. Navigate to the 'Troubleshoot' control via tab key and select it using enter key.
6. …
=> Fixing Accessibility BUG 17535630

AngularApp/projects/diagnostic-data/src/lib/components/openai/openai.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
This PR changes logging in OpenaiComponent for InPrivate access from exception to a plain log.
When AppLens opens in InPrivate mode, any detector output involving OpenaiComponent throws exception. These errors are expected and should be either ignored or changed to a plain log.
This PR changes the logging type from exception to a plain log.
=> Change localStorage logging in OpenaiComponent for InPrivate access

AngularApp/projects/app-service-diagnostics/src/assets/scripts/monitoring.js
This PR is for checking blank screen for every 2s and logging if after 30s for 15 consecutive checks and iFrame is still blank
=> Add interval ping for checking

AngularApp/projects/app-service-diagnostics/src/styles.scss
Fix for dropdown not showing scroll when zoom in
No Scroll for dropdown
Having Scroll for dropdown
=> Fix for dropdown not showing scroll when zoom in

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts
It seems MSaaS API breaks down with any case number that is less than 15 digits.
Updating the validation here to prevent us from saying "MSaaS API is down" when it's just a bad case number.
The second issue that this PR fixes is related to using localStorage to keep context of where the user was going in applens when they come from a deep link. Here is the issue details:
If a user tries to open applens for Resource A and gets an error --> we would store Path A in local storage.
- Now if the user goes and adds a case number etc, we read the Path A, clear the localstorage and navigate to the path.
- However **if the user does not bother to fix the case number issue**, Path A will be persisted in their localstorage and when they come to AppLens normally, Path A will still be in storage and …
=> Durian changes: Updating minimum length and fixing deep link context issue

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts
Revert for [PR 1999](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1999) which keep detector content keep pushing left
Go to any detector with graph/table, check horizontal scroll bar should be not expanding anymore
Graph is keep pushing to left
=> Fix for keep pushing page

.gitignore, AngularApp/projects/applens/src/app/app.module.ts, AngularApp/projects/applens/src/app/modules/armresourceurlfinder/armresourceurlfinder.component.html, AngularApp/projects/applens/src/app/modules/armresourceurlfinder/armresourceurlfinder.component.scss, AngularApp/projects/applens/src/app/modules/armresourceurlfinder/armresourceurlfinder.component.spec.ts, AngularApp/projects/applens/src/app/modules/armresourceurlfinder/armresourceurlfinder.component.ts, AngularApp/projects/applens/src/app/modules/armresourceurlfinder/armresourceurlfinder.module.ts, AngularApp/projects/applens/src/app/modules/main/main/main.component.ts, AngularApp/projects/applens/src/app/shared/services/applens-http-interceptor.service.ts, AngularApp/projects/applens/src/app/shared/services/observer.service.ts, AngularApp/projects/applens/src/app/shared/utilities/main-page-menu-options.ts, ApplensBackend/Configuration/Startup.cs, ApplensBackend/Controllers/InsightsController.cs, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Helpers/Constants.cs, ApplensBackend/Services/ArmResourceService/ArmResourceRedisCache.cs, ApplensBackend/Services/ArmResourceService/ArmResourceService.cs, ApplensBackend/Services/ArmResourceService/ArmResourceServiceConfig.cs, ApplensBackend/Services/RedisCache/IRedisService.cs, ApplensBackend/Services/RedisCache/RedisServiceBase.cs, ApplensBackend/appsettings.json
The change is to:
- Add support for services in future to become 1P easily (i.e. we are able to identify arm url from the resource name)
- Since we dont have ARM/Resource Graph access, APIM has a kusto query that would help with the arm url resolution.
- In future, if any other service also has this support, we should be able to very quickly add them,
- This is needed to strengthen the security of our system with resource validation.
=> Making APIM as 1P service in Applens

AngularApp/projects/applens/src/app/app.module.ts, AngularApp/projects/applens/src/app/shared/auth/aad-auth-guard.service.ts
Today if the first ping we send to applens backend fails users are show a page that says applens backend is down but the url reads "authRequestFailed" which may be misleading as some people may think their auth is failing.
Renaming it to "downpage"
=> Rename the authRequestFailed to downpage to avoid confusion

AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.html, AngularApp/projects/diagnostic-data/src/lib/components/app-insights-enablement/app-insights-enablement.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/opt-insights-enablement/opt-insights-enablement.component.ts
Removing empty banner being displayed to non-beta subscriptions.
Non-beta subscriptions are seeing an empty banner
N/A
Added the check for beta subscriptions to app-insights-enablement component
1. In the Azure Portal, under a non-beta subscription, go to a Web App integrated with Application Insights which has profilers enabled and Code Optimization Insights.
2. Click on Diagnose and Solve problems then in Availability and Performance. This will load the Overview detector.
3.  In the Overview detector first it will try to show Application Insights there should not be an empty banner under the Application Insights banner.
=> Code optimizations fix empty banner

AngularApp/projects/app-service-diagnostics/src/app/resources/web-sites/services/web-sites.service.ts, AngularApp/projects/diagnostic-data/src/lib/models/search.ts
Project Shield has been enabled for Logic Apps Standard, but the detector search doesn't work because the resourceService.getPesId method returns null for AppType = WorkflowApp.
Made the change to return pesId for LA Standard.
**Before fix:**
**After fix:**
=> LogicAppsStandard pesId info for genie to work with detectors

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
It is possible that the DAAS Sessions will return the Reports link without the SCM host name. This happens because the logic to get the default host name in DaaS depends upon a sandbox property and that property may be empty if no requests came to that site
With this change, we are correctly populating the SCM host name if the DAAS API returns the relativepath without the full host name.
=> Append hostname if missing for Daas Reports

AngularApp/projects/applens/src/app/modules/ase/ase-finder/ase-finder.component.ts
ASE Finder is not preserving query params, due to which CSS users are getting case number not entered, even after it has been entered.
=> Preserve query params in ASE finder

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts
This PR just assumes that DiagServer for Linux is enabled everywhere as the DiagServer deployment in Linux went live long back
=> Force UI code to use DiagServer everywhere

ApplensBackend/Configuration/Startup.cs, ApplensBackend/Controllers/ResourceController.cs, ApplensBackend/Services/ArmResourceService/ArmResourceService.cs, ApplensBackend/Services/ArmResourceService/NullableArmResourceService.cs
There was a breaking change that was not compatible with national clouds. This is addressing that.
The reason for the breaking change is that ArmResourceService depends on KustoQueryService which is not enabled in n-clouds as we didn't have a use case for it but we may in the near future. In the mean time we want to work around this issue by creating a NullableArmResourceService that returns FakeResource for when APIM is selected in the drop down for selecting a resource.
This is tested by running Applens locally setting the startup to start from ApplensV3NationalClouds.
=> Address ArmResourceService for national clouds.

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas/daas.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/java-flight-recorder/java-flight-recorder.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/profiler/profiler.component.ts
Due to a case sensitivity issue, the UI for Diagnostic tools was not populating the correct state of the sessions. This PR fixes that issue.
=> Fix DaaS Tools UI for Vmss instances

AngularApp/projects/app-service-diagnostics/src/app/shared/services/optinsights/optinsights.service.ts, AngularApp/projects/diagnostic-data/src/lib/components/opt-insights-enablement/opt-insights-enablement.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
Adding Telemetry to measure when the button to open Code Optimizations blade is clicked and when we receive results from Code Optimizations
This will help us have telemetry for how many times we are showing insights to customers and how many times they are clicking on them to learn more details.
- Adding a AICodeOptimizerOpenOptInsightsBladewithTimeRange TelemetryEventName to measure when a user clicks in the insights, which will open Code Optimizations blade.
- Adding a check to only log  AICodeOptimizerInsightsReceived when results come in.
- When logging the total amount of results, adding an empty parameter so that the value of total amount of results it's not recognized as error.
1. Go to Azure Portal and click Application Insights.
2. Open the DiagnosticsAndSolvePortal Application …
=> Adding more logging for better telemetry

UITest/DiagPortalTest/DiagPortalTest.cs, UITest/DiagPortalTest/DiagPortalTest.csproj
For some reason, UI testing will be failed in PROD if enabling network monitoring for basic auth. 
"Unhandled exception. OpenQA.Selenium.DevTools.CommandResponseException: Fetch.continueRequest: Invalid InterceptionId"
In this PR change the logic to only login by form in PROD and update Selenium to latest version
=> Revert logic for login in UI testing

AngularApp/projects/app-service-diagnostics/src/app/fabric-ui/components/category-summary/category-summary.component.ts
Fix logic to check for resource name in Diagnose And Solve page. Resource name was not being displayed on the portal when navigating inside a category
NA
Fix logic to check for resource name in Diagnose And Solve page so that resource name is displayed inside a category.
Navigate into a category and you should be able to see the resource name.
=> Fix logic to check for resource name in Diagnose And Solve page

AngularApp/projects/app-service-diagnostics/src/app/shared/services/arm.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts
DAAS Backend API's  have been updated on 75% of the overall fleet so changing code logic to first try POST and then fallback to GET to avoid any 405 errors that customers may see in their logs.
Use POST first instead of GET and then fallback to GET if POST fails (for sites that are using older DAAS bits)
=> Switch to POST first for DAAS API

AngularApp/projects/diagnostic-data/src/lib/components/markdown-view/markdown-view.component.html, AngularApp/projects/diagnostic-data/src/lib/components/markdown-view/markdown-view.component.ts
This PR is to remove send email button in markdown
=> Remove markdown buttons

AngularApp/projects/diagnostic-data/src/lib/services/detector-control.service.ts
This PR is for fixing refreshing when click "refresh" button in the command bar in Portal
1. Go to D&S portal and go to any detector
2. In time picker, change the time duration
3. Click "refresh" button in the command bar
4. Check if detector is showing data within time period you specified.
=> Fix for refreshing in portal

ApplensBackend/Services/ArmResourceService/ArmResourceService.cs
This is a fix from a followup conversation on Applens channel.
For APIM or any service using ARM Resource service in applens, When we are able to get the ARM resource Id from the resource name using their Kusto query, there is no further need to validate the ARM url in our backend (using acis)
So adding the armId to durian cache to avoid acis validation
=> ARM Resource Service : Add resource to durian cache to skip ACIS validation

AngularApp/projects/diagnostic-data/src/lib/components/chat-ui/chat-ui.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/openai-chat/openai-chat.component.ts
This bug:
After fix:
Also added additional logging for a scenario where prompt size overflows chatgpt limit, we will retry with reducing the context length.
=> UI bug fix for Chat UI component and additional logging

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts, AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.html, AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts
With this change, workflow authors will be able to specify InternalOnly and Category metadata for workflows. 
Note: Category is not propagated properly to the backend code yet. Raising a PR for that as well.
=> Allows authors to specify category and InternalOnly for workflows

AngularApp/projects/applens/src/app/modules/dashboard/dashboard/dashboard.component.ts, AngularApp/projects/applens/src/app/shared/components/unauthorized/unauthorized.component.html, AngularApp/projects/applens/src/app/shared/services/applens-http-interceptor.service.ts, AngularApp/projects/diagnostic-data/src/lib/models/alerts.ts
Currently one scenario is not supported in Durian. This is the cross resource detector feature of Applens where user opens Applens for resource A, clicks a detector, which triggers some detectors for an underlying resource B (e.g. container apps detectors can triggers underlying AKS detectors, similarly for web apps on ASE). Durian can have issues with the confirmation for unrelated resource dialog box when the resource B detectors are fired and get unauthorized error. This PR aims to fix that.
Also, AppLens access SGs that were on MyAccess are now moving to CoreIdentity. This PR updates the url link of AppLens CSS Access group to the CoreIdentity page. Non-CSS Access group is not yet moved, will update that accordingly.
=> Durian cross resource detectors and updated SG

AngularApp/projects/applens/src/app/modules/dashboard/kustogpt/kustogpt.component.ts, AngularApp/projects/applens/src/styles.scss
Chat header was overlapping on chat UI samples when a header spanned multiple lines 
Reduce lines in chat header and reduce the font size
This is how it looked on a laptop screen
=> Adjust the size of the header to work on different screen resolution

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/link-interceptor.service.ts
Bail out early enough from link interceptor service if the path passed is a relative path.
=> Improve logic of link interceptor service slightly

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-api.service.ts
Post this change, the UI will make two ListDetectors call, one for workflows and one for detectors to fetch both. This is required for enabling workflows in public diagnose and solve blade.
This change will double the number of ListDetectors calls to our backend. I reviewed that code and most of the logic is getting served from the cache so this should not cause any issues but still I will inform on-calls and the team to keep an eye on ListDetectors latency and if this becomes a problem, we should revert this PR.
=> Enabling feature to get workflows and detectors both

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Currently, a user can use Applens to access any kusto cluster that they don’t have access to. The aim of this PR is to restrict unauthorized access to multiple kusto clusters.  
https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/2916/
- shows the unauthorized error message resulting from an unauthroized access to a kusto cluster by an Applens user.
- Create a new detector or edit an existing detector
- In the Develop tab, run a kusto query to access a cluster you don't have access to.
=> FE - Enforce Kusto Service Authorization Across Multiple Clusters

AngularApp/projects/diagnostic-data/src/lib/components/openai-chat-container/openai-chat-container.component.ts
Email subject for feedback email was using chat Header, the header can contain HTML tags and that messes up the subject making it look garbled..
Something like below
This PR will use chat identifier as the feedback subject instead of the chat header.
=> Fix subject of feedback email message for Chat

AngularApp/projects/diagnostic-data/src/lib/components/form/form.component.ts
Looks like a change I introduced to fix issue with forms in child detector caused the URL length to keep extending.
Without this change, it works fine. Verified for both regular form detector and Forms in child detector.
=> Fixed issue where url keeps extending

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/content.service.ts
Enabling secure bing search method for our best partner AKS as well. This was earlier blocked due to AKS RP not passing query parameters to our backend but now they are so....
=> Enabling secure bing search method for AKS as well

AngularApp/projects/app-service-diagnostics/src/app/shared/services/generic-api.service.ts
This PR enables workflows back and filters out the duplicate items for scenarios where resource types may not be passing query params to AppLens backend
@SharmaAjay19 - As you know how to reproduce the AKS scenario, can you validate that this PR is indeed fixing the issue that AKS ran in to ?
=> Enable workflows back and handle duplication

AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.html
Currently hyperlinks in markdown generated by workflow nodes are not honoring the linkInterceptorService logic due to which the links are either broken or not opening in a new window
With this change, linkInterceptorService will start intercepting links for Diagnose and Solve workflow nodes
=> Fix Hyperlinks for markdown nodes for Workflows

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
Add logging for detectors matching in case submission to help with reporting needs.
Add logging for detectors matching in case submission to help with reporting needs.
Add logging for detectors matching in case submission to help with reporting needs.
=> Add logging for detectors matching in case submission

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
Apollo API behavior has changed in the past months where it returns a dummy article for nearly 80-85% of our requests that we make to fetch self-help content to show in case submission. This is due to some configuration changes on their side that were needed for Help 2.0 to work. We had been falling back on the Legacy MPAC API in these scenarios but that API has the risk of returning stale content. So, to get the real content from Apollo, we are now required to make the call using partial resource uri so that we can get the actual self-help content and not the dummy article.
=> Updating Apollo self-help content call to adjust with Apollo API

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/configure-storage-account/configure-storage-account.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.html, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas-validator.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas/daas/daas.component.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/models/daas.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/daas.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared/services/urielements.service.ts
ElasticPremium instances have allotted and pre-warmed instances and app may not be allocated to run on pre-warmed instances and DaasRunner may not be running on those instances. The end result is that when someone submits a DaaS session for pre-warmed instance, the session will fail for that instance as DaasRunner will not be running to pick that instance. To fix the problem, we only show the allotted instances in DAAS Tools.
ICM:399254805
We needed to somehow identify all the allotted instances to the app. For this we use this logic 
- We get all processes from all instances (pre-warmed and allocated) `/instances/{InstanceId}/processes`
- Then, we check the `machineName` returned in the API call to identify which instance is "really" allotted to the app. The ARM API may return same …
=> Show only allocated instances for DaaS for Elastic Premium SKU

AngularApp/projects/app-service-diagnostics/src/app/shared/components/daas-sessions/daas-sessions.component.ts
For DAAS currently we are making **/extensions/daas/sessions/list** and **/extensions/daas/v2/sessions/list** to retrieve Sessions for Linux Web Apps and the first call is un-necessary and could result in 400 BAD requests for apps that have not picked up the latest DiagnosticServer or KuduLite bits. 
While this logic will get resolved once the Linux Web Apps will pick up the latest site extension bits but the UI can also avoid making this call till the latest bits are picked up everywhere.
=> Avoid multiple /sessions/list calls for DaaS Linux Web App

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.html, AngularApp/projects/applens/src/app/modules/dashboard/workflow/create-workflow/create-workflow.component.ts
The workflow Develop tab experience is broken currently because of a missing NULL check. This PR just fixes that bug. Also including a fix where the `Download` and `Upload `buttons text was changed to `Detector Copilot(Preview)`
- [x ] Bug fix (non-breaking change which fixes an issue)
Was missing null check for workflows that do not have Support Topic mapped to them.
=> Fix Workflow Authoring experience

AngularApp/package.json, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts
This PR is for,
- Enable generate source map for Applens
- Add logging for support-topic
[WI 3569 Store source maps for Applens deployment to a storage account](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/3569)
=> Add sourcemap for Applens

AngularApp/projects/diagnostic-data/src/lib/components/opt-insights-enablement/opt-insights-enablement.component.ts, AngularApp/projects/diagnostic-data/src/lib/services/telemetry/telemetry.common.ts
A previous deployment unintentionally removed two required changes:
- Logging events for when a user clicked on Code Optimizations insights:
- TelemetryEventNames.AICodeOptimizerOpenOptInsightsBladewithTimeRange
- Using moment.utc() to calculate time
This PR is readding those changes.
TelemetryEventNames.AICodeOptimizerOpenOptInsightsBladewithTimeRange is required to estimate from our side how many users interacted with Code Optimizations
Using moment.utc() responds to a change in the portal project done by XiaoXu several months ago, to better estimate times.
- It adds TelemetryEventNames.AICodeOptimizerOpenOptInsightsBladewithTimeRange and logs it whenever a user clicks on Code Insights results (openOptInsightsBladewithTimeRange()) which in turn will redirect them to the Code …
=> Re-adding telemetry and correct time usage

ApplensBackend/Controllers/IncidentAssistanceController.cs, ApplensBackend/Controllers/SurveysController.cs
The App Lens Incident APIs have been configured without authentication.  
An example of this is shown below where a customers incident information could be retrieved with an HTTP GET request.
```
GET /api/icm/getIncident/407454838 HTTP/1.1
Host: applens.trafficmanager.net
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Sat, 22 Jul 2023 11:11:49 GMT
Server: Microsoft-IIS/10.0
Set-Cookie: ARRAffinity=0eb22d20c19edaf9580d00da8793ef25da2f8fb32f441bf713accbe41900887b;Path=/;HttpOnly;Secure;Domain=applens.trafficmanager.net
Set-Cookie: ARRAffinitySameSite=0eb22d20c19edaf9580d00da8793ef25da2f8fb32f441bf713accbe41900887b;Path=/;HttpOnly;SameSite=None;Secure;Domain=applens.trafficmanager.net
Request-Context: appId=cid-v1:448da79b-5c62-499d-b02f-83fd00681ad2
Content-Security-Policy: …
```
=> Fix - Use ApplensAccess Policy for IncidentAssistance and Survey Endpoints

AngularApp/projects/applens/src/app/modules/dashboard/onboarding-flow/onboarding-flow.component.ts
Due to some async issue, `this.queryResponse` object is not populated correctly in the onboarding component for workflows. This PR just ensures that the `owners.txt` get populated from the `workflowPublishBody` in case `this.queryResponse`  is NULL and if grad publish is happening for workflow detectors.
Underneath somewhere an aync issue exists so this is just a band-aid fix to take care of that problem.
=> Ensure owners.txt populated for workflows

AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.html, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.scss, AngularApp/projects/app-service-diagnostics/src/app/auto-healing/autohealing-custom-action/autohealing-custom-action.component.ts
Elastic Premium Apps do not have Always-On and Scale Controller does the job of warming up the main site's worker process, but it is not consistently doing this for the SCM Site due to which DaasRunner.exe may not be running when an Auto-Heal Condition is satisfied. Functions team is aware of this issue, and they have some optimization planned in ANT-101 but till then, disabling the option to configure Auto-Heal to run diagnostics in Auto-Heal UI for Elastic Premium apps.
This PR should be reverted once the functionality to warmup the Kudu site is addressed by Scale Controller team.
=> Disable AutoHeal option for Diagnostics for Elastic Premium

AngularApp/projects/applens/src/app/shared/services/applens-openai-chat.service.ts, ApplensBackend/Extensions/AuthServiceCollectionExtensions.cs, ApplensBackend/Hubs/OpenAIChatCompletionHub.cs
Our Copilots talk to the backend via SignalR over WSS. This PR adds security on the SignalR connection negotiation call so only authenticated clients/users can interact with the Copilots.
This PR changes nothing in terms of the existing experience, only adds security.
=> Authentication on SignalR connection for Copilot

AngularApp/projects/applens/src/app/modules/dashboard/workflow/detector-node/detector-node.component.html, AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.html, AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.scss, AngularApp/projects/diagnostic-data/src/lib/components/workflow-node/workflow-node.component.ts, AngularApp/projects/diagnostic-data/src/lib/components/workflow-result/workflow-result.component.html, AngularApp/projects/diagnostic-data/src/lib/components/workflow-result/workflow-result.component.ts, AngularApp/projects/diagnostic-data/src/lib/models/workflow.ts
Changes required to the UI project to support adding full detector output of a detector to a workflow node
The UI PR to go along with backend changes PR - https://dev.azure.com/msazure/One/_git/AAPT-Antares-AppServiceDiagnostics/pullrequest/8581708
The below checkbox has to be checked if Detector Author wants the detector output to be part of workflow node
=> Ensure Detector output is part of Detector node

AngularApp/package.json
Adding `npm run build-asd-no-cdn` for building app-service-diagnostic for N-cloud that not requires for CDN
=> Add command for not using CDN for n-cloud

AngularApp/projects/app-service-diagnostics/src/app/shared-v2/services/support-topic.service.ts, AngularApp/projects/app-service-diagnostics/src/app/shared-v2/utils/apollo-utils.ts
Show the entire static self help document in case submission and not just the H3 content. Got a request from SPMs for this change.
Show the entire static self help document in case submission and not just the H3 content. Got a request from SPMs for this change.
=> Show all Apollo self help content in case submission for AKS and WebApps
